-- Texas Exam Prep — content seed, chunk 1 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.modules (id, course_id, title, position, status)
select '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Insurance Fundamentals', 1, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.modules (id, course_id, title, position, status)
select 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Policy Structure and Contract Law', 2, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.modules (id, course_id, title, position, status)
select '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Property Coverages', 3, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.modules (id, course_id, title, position, status)
select '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Casualty Coverages', 4, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.modules (id, course_id, title, position, status)
select '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Texas Statutes and Rules', 5, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Risk, Peril and Hazard',
       'risk-peril-and-hazard', 'Three words the exam treats as distinct and everyday speech does not.', 1,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', c.id, $lesson$# Three words, three meanings

In ordinary speech *risk*, *peril* and *hazard* are near-synonyms. You could
say "the risk of fire", "the peril of fire" or "a fire hazard" over coffee and
nobody would stop you.

The exam stops you. It treats them as three separate ideas, and a run of
questions turns on nothing harder than telling them apart. They are worth ten
minutes now because every later topic assumes them.

The one-line version:

- **Risk** is the uncertainty.
- **Peril** is the thing that causes the loss.
- **Hazard** is what makes the peril more likely, or worse when it happens.

## Risk

**Risk is uncertainty about loss.**

Notice what that does *not* say. It does not say the loss is likely, or large,
or imminent. It says the outcome is not known in advance. A building with
sprinklers, an alarm and a spotless history still carries risk, because nobody
can promise it will not burn.

The exam cares about one division above all others, because only one side of
it is insurable.

**Pure risk** offers two outcomes: a loss, or no loss. A house either burns or
it does not. A driver either has a collision or does not. There is no version
of the story where you come out ahead. **Pure risk is insurable.**

**Speculative risk** offers three: a loss, no loss, or a *gain*. Opening a
restaurant. Buying shares. Betting on a horse. **Speculative risk is not
insurable.**

> If a person could profit from the event, an insurer will not cover it.

That single sentence answers a surprising number of questions. When a stem
describes a situation and asks whether it is insurable, find out whether
anyone stands to gain. If they do, the answer is no.

The reason is not squeamishness about gambling. It is that insurance works by
pooling many similar exposures and predicting the total — which only holds if
losses happen *to* people rather than being chosen *by* them.

## Peril

**A peril is the cause of loss itself.**

Fire. Windstorm. Hail. Theft. Collision. Vandalism. When a policy sets out
what it covers, it is listing perils, and two structures recur:

- **Named perils.** The policy lists the causes it covers. If a cause is not
  on the list, there is no coverage. The burden sits with the insured to show
  the loss came from a listed peril.
- **Open perils** (you will also see "all risk" or "special form"). Every
  cause is covered *except* those the policy excludes. The burden flips: the
  insurer must show the loss came from an excluded cause.

That reversal of burden is the point, and it is tested. Open-perils coverage is
broader not because the list of covered causes is longer but because the
policy stops trying to list them.

A related idea travels with perils: **proximate cause** — the unbroken chain
of events from the peril to the damage. If a windstorm breaks a window and
rain then ruins the carpet, the proximate cause is the windstorm, even though
water did the visible damage. Coverage follows the proximate cause, not the
last thing that happened.

## Hazard

**A hazard is a condition that makes a peril more likely, or a loss worse.**

A hazard is not itself the cause. Oily rags in a basement do not damage
anything. They make fire — the peril — more likely, and worse when it comes.

The exam expects three categories, and the last two are where people lose
marks.

**Physical hazard** is a tangible condition of the property or its use. Oily
rags. An icy front step. Storing fireworks in a shop. Anything you could point
at.

**Moral hazard** is *dishonesty in the insured*. A person who has arranged a
convenient fire before, or who would inflate a claim, or who insures a
business that has stopped making money. The insurer's exposure rises because
of who this person is, not because of anything on the premises.

**Morale hazard** is *indifference caused by being insured*. Not dishonesty —
carelessness. Leaving a car unlocked because the policy will pay. Skipping the
roof repair because it is covered anyway. The person is not planning to cause
a loss; they have simply stopped trying hard to prevent one.

The distinction in one line: **moral is dishonesty, morale is carelessness.**

Some texts add a fourth, **legal hazard** — conditions in the legal
environment, such as a jurisdiction whose courts award unusually large
verdicts, that increase the size of losses independently of anything the
insured does.

## Loss

Rounding out the set: a **loss** is the reduction, decrease or disappearance
of value. It is what actually happened, after the hazard made the peril more
likely and the peril occurred.

## How this is examined

Questions in this area are rarely difficult once the vocabulary is straight.
They are usually one of four shapes.

**"Which of the following is a hazard?"** — with perils among the distractors.
Ask yourself: is this thing the *cause* of a loss, or a *condition that makes
a cause more likely*? Fire is a peril. A frayed extension cord is a hazard.

**"Moral or morale?"** — the most common trap in the whole section. Look for
intent. Dishonesty, fraud, a motive to cause a loss → moral. Laziness,
indifference, "it's insured anyway" → morale.

**"Is this insurable?"** — apply the profit test. Any chance of gain makes it
speculative and uninsurable.

**Named versus open perils** — ask who has to prove what. Named: the insured
proves the cause is covered. Open: the insurer proves it is excluded.

## Check yourself

Before moving on, answer these without looking back.

1. A restaurant owner whose business is failing takes out a large fire policy.
   Which kind of hazard is that, and why?
2. A homeowner stops locking the back door because they now have a theft
   policy. Which kind of hazard, and why?
3. Is the possibility that a stock you bought will fall in value a pure risk
   or a speculative risk? Is it insurable?
4. Under an open-perils form, who has to prove what?

## Answers

Work through the four above before reading these.

1. **Moral hazard.** The motive is dishonesty: a failing business is worth
   more to its owner burnt than trading, so the insurer's exposure rises
   because of who this person is.
2. **Morale hazard.** No intent to cause a loss — only carelessness that
   appeared once the policy did.
3. **Speculative**, because a gain is possible. Therefore not insurable.
4. **The insurer** must prove the cause of loss falls under an exclusion. The
   insured only has to show a loss occurred.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'How Insurance Works',
       'how-insurance-works', 'Why insurers can predict losses they cannot predict individually, and which risks they will not touch.', 2,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', c.id, $lesson$# The trick at the centre of insurance

An insurer cannot tell you whether *your* house will burn down this year.
Nobody can. Yet it will quite confidently tell you how many of one hundred
thousand similar houses will burn, and price your policy accordingly.

That is not a paradox, and the exam wants you to be able to say why.

## The law of large numbers

**The more similar exposures you observe, the closer actual losses come to
expected losses.**

Toss a coin four times and you might get four heads. Toss it four thousand
times and you will get close to half. Nothing about any individual toss became
more predictable; the *aggregate* did.

Insurance runs on exactly this. One house is unpredictable. A hundred thousand
similar houses are not. The insurer does not need to know which ones will
burn — only how many, near enough to set a price that covers the losses, the
expenses and a margin.

Two words in that sentence are doing heavy lifting. **Similar**: houses, not a
mixture of houses and oil refineries. **Many**: a handful of exposures gives
you no more certainty than one.

## What makes a risk insurable

The exam expects a list. Different textbooks phrase it differently, but the
substance is consistent, and each item is really a way of protecting the law
of large numbers.

**A large number of similar exposure units.** Without them the mathematics
does not work.

**The loss must be definite and measurable.** You must be able to say when it
happened, where, from what cause, and what it cost. "My business felt less
successful this year" is none of those things.

**The loss must be accidental** from the insured's standpoint — fortuitous,
outside their control. This is the same principle that makes speculative risk
uninsurable, seen from another angle.

**The loss must not be catastrophic to the insurer.** If a single event could
wipe out every exposure at once, pooling has not spread anything. This is why
flood and earthquake sit outside standard property policies, and why Texas
handles windstorm on the coast through a separate association.

**The chance of loss must be calculable.** You need data, or the price is a
guess.

**The premium must be economically feasible.** If the honest premium approaches
the value of the thing insured, nobody sensible buys it. A policy costing
$90,000 a year to insure a $100,000 building has no market.

## Adverse selection

**Adverse selection is the tendency of those most likely to suffer a loss to
be the most eager to buy insurance.**

People who live on a floodplain want flood cover more than people on a hill.
Someone who has just felt a lump wants health cover more urgently than someone
who has not. Left alone, an insurer's pool fills up with exactly the exposures
it can least afford, and the pool stops resembling the population the price
was based on.

Nearly every piece of underwriting machinery exists to resist this:
applications, inspections, waiting periods, exclusions, pre-existing condition
clauses, and the underwriter's right to decline.

Do not confuse it with **moral hazard**, which the exam likes to place
nearby. Adverse selection happens *before* the policy, in who chooses to buy.
Moral hazard happens *after*, in how the insured behaves once covered.

## Where the premium goes

A premium has to cover three things: expected losses, the insurer's expenses
(commissions, salaries, taxes), and a margin for profit and contingencies. The
loss portion is often called the **pure premium**, and the amount added for
expenses and profit the **loading**.

This is worth knowing because it explains an answer that otherwise looks
strange: an insurer can be paying out less than it collects and still be
losing money, once expenses are counted.

## Risk management before insurance

Insurance is one response to risk, not the only one. The exam tests the full
set, usually by asking which one a described action represents.

- **Avoidance** — do not take the risk at all. Do not buy the building.
- **Retention** — accept it and pay losses yourself. A deductible is retention.
- **Reduction** (or control) — lower the frequency or severity. Sprinklers,
  training, locks.
- **Transfer** — move it to someone else. Insurance is transfer; so is a hold
  harmless agreement in a contract.
- **Sharing** — spread it across a group, as partners or a pool do.

A common stem describes a business installing a sprinkler system and asks
which technique that is. It is *reduction*, not transfer — the sprinklers do
not move the risk to anybody, they make the loss smaller.

## How this is examined

**"Which of the following is not a characteristic of an insurable risk?"** —
usually with "the loss must be catastrophic" or "the insured must be able to
cause the loss" among the options. Work down the list.

**Law of large numbers questions** turn on the word *similar* or the word
*more*. The prediction improves with more exposures, and only if they resemble
one another.

**Adverse selection versus moral hazard** — ask when it happens. Before the
policy is written, it is adverse selection.

**Risk-management technique questions** describe an action and want the label.
Deductible → retention. Sprinklers → reduction. Buying a policy → transfer.
Not opening the business → avoidance.

## Check yourself

1. An insurer writes one hundred thousand homeowners policies instead of one
   hundred. What has improved, and what has not?
2. Why are floods difficult to insure through an ordinary property policy?
3. A contractor adds a clause making the client responsible for certain
   losses. Which risk-management technique is that?
4. A homeowner chooses a $2,500 deductible instead of $500. Which technique?

## Answers

1. The *predictability of the total* has improved. The predictability of any
   single house has not changed at all — that is the whole point of the law of
   large numbers.
2. One event damages an enormous number of exposures simultaneously, so the
   losses are not independent and the pool does not spread them. It is the
   "not catastrophic to the insurer" condition failing.
3. **Transfer** — the risk is moved to another party by contract. Insurance is
   not the only form of transfer.
4. **Retention** — they have chosen to carry more of each loss themselves.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Insurable Interest and Indemnity',
       'insurable-interest-and-indemnity', 'Who is allowed to insure what, and the rule that you may be made whole but never better off.', 3,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', c.id, $lesson$# Two rules that stop insurance becoming gambling

Insurance moves money to people after bad things happen. Two principles keep
that from becoming a betting shop, and between them they decide a great many
exam questions.

**Insurable interest** decides *who may buy*.
**Indemnity** decides *how much they may collect*.

## Insurable interest

**You may only insure something you would genuinely lose by.**

That is the whole rule. Everything else follows from it.

### Why it exists

Without the rule, anyone could take out a fire policy on a stranger's
warehouse and then hope for a fire. That gives a stranger a financial reason
to want the warehouse to burn — and gives the insurer no way to distinguish a
customer from an arsonist. Requiring an interest removes the motive.

It is also what separates insurance from a wager in law. A bet creates a risk
that did not exist before. Insurance transfers one that already did.

### When it must exist — the detail that is tested

Property and life insurance answer this differently, and the difference is
examined constantly.

**Property and casualty: at the time of the loss.**

You can insure a building and later sell it. If it burns after the sale, the
claim fails — not because you never had an interest, but because you no longer
had one when the loss happened.

**Life: when the policy is taken out, and not necessarily after.**

A woman insures her husband's life. They divorce. She remains the beneficiary
and the policy pays. The interest existed at inception, which is all life
insurance requires.

A neat way to hold it: **property asks "do you lose by this now?"; life asks
"did you have reason to buy this then?"**

### Who has one

- An **owner**, in their own property.
- A **lender or mortgagee**, up to the amount still owed. A bank holding a
  $200,000 mortgage has an interest of $200,000, not the value of the house.
- A **business**, in a key employee, or in property it holds for others.
- A **spouse**, in the other spouse's life; a parent in a dependent child's.
- A **tenant**, in improvements they have paid for.
- A **bailee** — a garage, a dry cleaner — in customers' property in their
  care.

### How much interest

Your interest is limited to what you stand to lose. A part-owner of a building
cannot insure the whole of it for their own benefit, and a lender cannot
recover more than the outstanding balance. This flows straight into the second
principle.

## Indemnity

**Indemnity means restoring the insured to the financial position they were in
immediately before the loss — no worse, and no better.**

The second half is the part that gets tested. If a loss could leave you better
off, somebody eventually arranges a loss.

Several familiar policy mechanisms are indemnity doing its work:

- **Actual cash value** settlements, which deduct depreciation so a
  twenty-year-old roof is not replaced with a new one at the insurer's expense.
- **Policy limits**, capping recovery at the amount insured.
- **Deductibles**, leaving part of every loss with the insured.
- **Other insurance clauses**, so two policies covering the same loss share it
  rather than each paying in full.
- **Subrogation**, letting the insurer step into the insured's shoes and
  recover from whoever caused the loss — which stops the insured collecting
  twice, once from the insurer and again from the wrongdoer.

### Where indemnity is deliberately set aside

The exam likes exceptions, and there are three worth knowing.

**Valued policies** pay an agreed amount regardless of actual value, used where
value is hard to establish after the fact — fine art, antiques.

**Replacement cost** coverage pays to replace without deducting depreciation,
which technically leaves the insured better off. It is sold anyway because
underinsurance after a total loss is a worse problem than the one it creates.

**Life insurance** is not a contract of indemnity at all. A life has no
measurable value, so the policy pays a stated sum. This is why insurable
interest is only required at inception.

## How this is examined

**"When must insurable interest exist?"** — the single most common question in
this area. Property: at the time of loss. Life: at inception.

**Fact patterns about lenders.** A mortgagee's interest is the balance
outstanding, not the property's value.

**"Which of these is not a contract of indemnity?"** — the answer is life
insurance, or a valued policy.

**Questions about collecting twice.** Subrogation and other-insurance clauses
both exist to prevent it; recognise them as indemnity in action.

## Check yourself

1. A man insures his house, then sells it. Two months later it burns. Does his
   policy respond? Why?
2. A bank holds a $150,000 mortgage on a $400,000 home. What is the extent of
   its insurable interest?
3. A woman insures her husband's life. They divorce, and she keeps paying the
   premiums. He dies. Does the policy pay?
4. An insurer pays a claim, then sues the driver who caused it. What is that
   called, and which principle does it serve?

## Answers

1. **No.** Property insurance requires an insurable interest **at the time of
   the loss**, and he no longer had one.
2. **$150,000** — the amount outstanding. A lender's interest is what it stands
   to lose, not what the property is worth.
3. **Yes.** Life insurance requires the interest only **when the policy is
   taken out**. It does not have to survive the marriage.
4. **Subrogation**, and it serves **indemnity** — without it the insured could
   recover twice for the same loss.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
