-- Texas Exam Prep — content seed, chunk 3 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Terms the Other Lessons Assume',
       'terms-the-other-lessons-assume', 'Nine terms the blueprint names that do not belong to any one topic — and the three distinctions inside them that get tested.', 7,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', c.id, $lesson$# The vocabulary that sits between the other lessons

GK.II and GK.V are lists of **terms**, and the exam asks about them by name.
Most of them belong to a topic with a lesson of its own. These nine do not —
they are the connective tissue, and a question about one of them is usually a
definition question that you either know or do not.

Several are treated at more length later, where they do real work. This lesson
is where you find them under the name the blueprint uses.

## Direct and indirect loss

**A direct loss is physical damage to property caused by a peril.** Fire burns
the restaurant.

**An indirect loss is the financial consequence of that damage.** The
restaurant earns nothing for five months while it is rebuilt.

Indirect loss is also called **consequential loss**, and the two terms are
interchangeable on the exam.

The distinction matters because **they are covered by different coverages**. A
standard property form pays the direct loss. The indirect loss needs
**business income** and **extra expense** coverage, which is bought separately.
An insured who rebuilds and discovers the policy paid nothing for five months
of lost trading has bought one and not the other.

Examples of indirect loss: lost business income, extra expense, loss of rents,
additional living expense, spoilage following a power failure, loss of use.

> Fuller treatment: Module 3, *Commercial Property and the Package Policy*.

## Salvage value

**Salvage value is what damaged property is worth in its damaged state.**

It matters in two directions, and the exam tests the second.

**As a deduction.** Where the insurer pays a partial loss and the insured keeps
the damaged property, the salvage value may reduce the payment — the insured
still has something of value, and indemnity says they are restored, not
enriched.

**As the insurer's property.** Where the insurer **pays the loss in full**, it
generally acquires the right to the salvage. A total-loss vehicle paid out at
actual cash value becomes the insurer's to sell; a warehouse of smoke-damaged
stock paid in full becomes the insurer's to dispose of.

**Salvage rights follow payment.** That is the sentence to carry. The insurer
that pays for the item owns what is left of it, and any recovery reduces the
net cost of the claim — which is the same logic as subrogation, applied to
property instead of to a wrongdoer.

Do not confuse it with:

- **Market value** — what the property would sell for **undamaged**, which
  reflects location and demand as well as the structure.
- **Actual cash value** — replacement cost less depreciation.

> Fuller treatment of the valuation methods: lesson 4, *Valuing a Loss*.

## Vacancy and unoccupancy

Two words that mean the same thing in conversation and different things here.

**Unoccupied** — **the people are gone, the contents remain.** A family away
for three months. The building still looks lived in and still contains
everything worth stealing.

**Vacant** — **both the people and the contents are gone.** An empty house
between tenants.

**Vacancy is the one that restricts coverage.** After a building has been
vacant beyond a stated period — commonly **60 consecutive days** — several
perils are typically suspended: **vandalism and malicious mischief, glass
breakage, theft, sprinkler leakage** and **water damage**. Some forms also
reduce payment on any loss that does remain covered.

The underwriting logic is worth knowing because it explains the rule: an empty
building attracts vandalism, and a slow leak or a small fire runs for weeks
before anybody notices. The exposure genuinely changes.

The insured's fix is to tell the insurer and buy a **vacancy permit**.

> Fuller treatment: Module 3, *Dwelling Policies*.

## Blanket and specific insurance

**Specific insurance names an amount for one item at one location.**
$400,000 on the building at 14 Oak Street.

**Blanket insurance covers two or more items, or two or more locations, under
a single limit.** $1,200,000 across three warehouses, wherever the stock
happens to be.

The advantage of blanket is that it follows the property. A shifting inventory
insured specifically is over-insured at one site and under-insured at another
on any given day; insured blanket, the whole limit is available wherever the
loss occurs.

The price of it: blanket cover normally requires a **statement of values** and
a **high coinsurance percentage** — often 90% or 100% — because the insurer is
exposed at every location at once and needs the insurance-to-value discipline
that a specific limit would have provided.

> Fuller treatment: Module 3, *Commercial Property and the Package Policy*.

## Absolute, strict and vicarious liability

The blueprint names these as **three separate items**, so learn them as three.
Many texts treat "absolute" and "strict" as synonyms; this course keeps them
apart because the exam lists them apart.

**Absolute liability** — liability **that cannot be escaped by any defence**.
The defendant is liable for the harm, full stop. The classic examples are
**statutory**: workers' compensation, where the employer pays for a workplace
injury regardless of fault and regardless of the employee's own carelessness;
and some ultrahazardous activities such as **blasting**, where no amount of
care is a defence.

**Strict liability** — liability **without proof of fault**, but not
necessarily without any defence. The claimant need not show negligence; they
must still show the thing caused the harm. **Product liability** is the
standard example: a defective product makes the manufacturer liable whether or
not it was careless, though the manufacturer may still argue the product was
misused or altered. **Keeping a wild animal** is another.

The practical difference: **under strict liability the claimant is relieved of
proving fault; under absolute liability the defendant is relieved of nothing.**

**Vicarious liability** — liability for **somebody else's** negligence,
because of a relationship. An **employer** for an employee acting within the
scope of employment; a **vehicle owner** for a permissive driver; a **parent**
for a child in some circumstances.

The examinable feature: **the vicariously liable party did nothing wrong.** The
employer was not careless. Liability attaches because of the relationship, not
because of any act.

> Fuller treatment of negligence and its defences: lesson 6, *Negligence and
> Liability*.

## Binders

**A binder is temporary evidence that coverage is in force**, issued while the
policy is prepared.

- It may be **oral or written**.
- It carries the **same terms as the policy it anticipates**.
- It is **temporary** — it ends when the policy issues, when the insurer
  declines and gives notice, or at its own expiry.
- **An agent with binding authority binds the insurer**, even if the
  underwriter would have declined the risk. A broker generally cannot; a
  broker represents the buyer.

> Fuller treatment: Module 2, *The Declarations Page*.

## Certificates of insurance

**A certificate of insurance is evidence that a policy exists**, issued to
somebody who is not the insured — a landlord, a general contractor, a lender,
a client.

**It creates no coverage.** It summarises coverages, limits and dates as of
the day it was issued, and it becomes stale the moment anything changes. A
holder who wants actual rights under the policy must be added as an
**additional insured** by endorsement.

**Binder, certificate, policy** is the sequence to keep straight: a binder is
temporary **coverage**, a certificate is **proof** of somebody else's
coverage, and the policy is the contract.

## Endorsements

**An endorsement is a written amendment that adds to, deletes from or
otherwise changes the policy.** Called a rider in life insurance.

- It must be **in writing and attached**. A producer's promise does not amend
  a policy.
- It **takes precedence over conflicting printed policy language**, being the
  more specific and more recent statement of what was agreed.
- It may **broaden** coverage, **restrict** it, or merely **clarify** it.

## Deposit premium and audit

Some premiums cannot be calculated in advance, because they depend on
something not yet known — **payroll**, **sales**, **receipts**, or the number
of vehicles or employees.

For those policies:

1. The insurer estimates the exposure and charges a **deposit premium** at
   inception.
2. At the end of the policy period it conducts a **premium audit** of the
   actual figures.
3. It then issues an **additional premium** or a **return premium**.

**The insured must permit the audit and keep the records**, which is a policy
condition, not a courtesy. Refusing the audit can let the insurer estimate the
premium itself, usually unfavourably.

This is how **workers' compensation** and much **general liability** and
**commercial auto** business is rated. A business whose payroll doubles during
the year has not been underinsured — it has been under-*charged*, and the
audit corrects it.

> Fuller treatment: Module 4, *Workers' Compensation and Employers'
> Liability*.

## How this is examined

**Direct versus indirect loss**, and that they need different coverages.

**Salvage rights follow payment** — pay in full, own the remains.

**Vacant means the contents are gone too**, and it is vacancy that suspends
perils.

**Blanket covers several items or locations under one limit**, and demands a
higher coinsurance percentage.

**Vicarious liability attaches to somebody who did nothing wrong.**

**A binder creates coverage; a certificate does not.**

**An endorsement overrides conflicting printed language.**

**A deposit premium is an estimate, trued up by audit.**

## Check yourself

1. A fire closes a shop for four months. Name the direct loss and the indirect
   loss, and say which coverage pays each.
2. An insurer pays the full actual cash value on a stolen car that is later
   recovered, badly damaged. Who owns the wreck?
3. A homeowner spends six months abroad, leaving the house furnished. Vandals
   break in at month five. Vacant or unoccupied, and does it matter?
4. A wholesaler moves stock between four depots weekly. Blanket or specific,
   and what will the insurer require?
5. An employee, driving carefully, is hit by another vehicle while making a
   delivery and injures a pedestrian. On what basis might the employer be
   liable?
6. A contractor gives a property owner a certificate of insurance. Does the
   owner have coverage?
7. A contractor's payroll estimate was $400,000; the actual figure was
   $700,000. What happens at the end of the period?

## Answers

1. The **direct loss** is the fire damage to the building and contents, paid
   by the property coverage. The **indirect loss** is four months of lost
   trading, paid by **business income** (and extra expense), which must be
   bought separately.
2. **The insurer.** Salvage rights follow payment — having paid the loss in
   full, the insurer takes the salvage.
3. **Unoccupied** — the contents remained. It matters because the vacancy
   provisions, which suspend vandalism and related perils, apply to **vacant**
   buildings; an unoccupied one is generally still covered.
4. **Blanket**, so the single limit follows the stock. The insurer will
   require a **statement of values** and a **high coinsurance percentage**,
   commonly 90% or 100%.
5. **Vicariously** — the employee was acting within the scope of employment.
   Note the employer did nothing wrong; on these facts the employee may not
   have either, which is why the other driver's liability is the live issue.
6. **No.** A certificate is evidence of somebody else's coverage and creates
   none. The owner needed **additional insured** status by endorsement.
7. A **premium audit** determines the actual payroll and the insurer issues an
   **additional premium** for the difference.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'a5bd1b75-770f-55a0-b5b3-a6ca2cf5cea1', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'The Declarations Page',
       'the-declarations-page', 'What a policy is made of, and why the first page is the one that answers most questions.', 1,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', c.id, $lesson$# The page that identifies this policy from every other one

Every policy in property and casualty is assembled from the same four parts.
Learn the four, and a question about an unfamiliar form becomes a question
about which part you are being shown.

## The four parts

Remembered as **DICE**:

- **D**eclarations — who, what, where, when, how much
- **I**nsuring agreement — what the insurer promises
- **C**onditions — the rules both sides must follow
- **E**xclusions — what is not covered

Plus **endorsements**, which amend any of the four.

The order matters logically as well as mnemonically. The insuring agreement
makes a broad promise; the exclusions carve pieces out of it; the conditions
say what each side must do to keep the promise alive; and the declarations
attach all of it to one named insured, one property, one period and one set
of numbers.

## What is on the declarations

**The declarations page is the only part of the policy unique to this
insured.** Everything else is printed the same for everybody who buys the
form. The declarations are typed.

They carry:

- **The named insured** and mailing address.
- **The policy period** — inclusive dates *and times*. Most policies begin
  and end at 12:01 a.m. standard time at the insured's address, which is why
  a policy running to "1 June" does not cover a fire at noon on 1 June.
- **The description of the property or operation** insured — address,
  construction, occupancy, or for auto, the year, make and vehicle
  identification number.
- **The coverages purchased and their limits.**
- **The deductibles.**
- **The premium.**
- **The forms and endorsements attached**, by number. This list is how you
  prove what the policy actually consists of.
- **The mortgagee or loss payee**, where one has an interest.
- **The producer** and the insurer.

A useful way to hold it: **the declarations answer "who, what, where, when
and how much." The rest of the policy answers "under what circumstances."**

## Where the declarations come from: the application

The declarations are the insurer's restatement of the **application**. The
application is the insured's request for coverage and the insurer's primary
source of underwriting information, and the answers in it are
**representations** — statements believed true when made. Sign it, and it is
usually made part of the policy by reference.

Two consequences the exam likes:

- **Read the declarations when the policy arrives.** They are the insured's
  chance to catch an error before a claim does. An address, a limit or a
  deductible that does not match what was asked for is fixed by endorsement,
  not by argument at claim time.
- **A wrong answer on the application follows you onto the declarations.**
  If the application understated the square footage, the declarations show
  the wrong value and the coinsurance clause will be measured against the
  wrong number.

## Endorsements

**An endorsement is a written amendment that adds to, deletes from or
otherwise changes the policy.** Also called a rider, mostly in life
insurance. It must be in writing and attached; a producer's promise does not
amend a policy.

What the exam wants:

- An endorsement **takes precedence over conflicting printed policy
  language**. It is the more specific and more recent statement of what the
  parties agreed.
- Endorsements can **broaden** coverage (adding a peril, scheduling an item),
  **restrict** it (excluding a hazard the underwriter will not accept), or
  merely **clarify** it.
- They usually carry a premium change, and appear on the declarations by
  form number.

## Binders

**A binder is temporary evidence that coverage is in force**, issued while
the policy is prepared.

- It may be **oral or written**, though a written one is what anybody sensible
  uses. Many states, and most insurers' own rules, require written
  confirmation within a set period.
- It carries the **same terms as the policy it anticipates** — it is not a
  separate, thinner contract.
- It is **temporary**. It ends when the policy is issued, or when the insurer
  declines and gives notice, or at its own expiry.
- An agent with **binding authority** can bind the insurer on the spot. A
  broker generally cannot; a broker represents the buyer.

That last point is the one that gets tested: **a binder issued by an agent
with binding authority creates coverage even if the insurer would later have
declined the risk.**

## Certificates of insurance

**A certificate of insurance is evidence that a policy exists** — issued to
somebody who is *not* the insured and who needs proof: a landlord, a general
contractor, a lender, a client.

It is not a policy and it is not a binder. **It creates no coverage.** It
summarises coverages, limits and dates as of the day it was issued, and it
becomes stale the moment anything changes. A certificate holder who wants
actual rights under the policy needs to be added as an **additional insured**
by endorsement — a certificate alone does not do it.

## How this is examined

**"Which part of the policy contains X?"** Limits, dates, named insured,
deductible, mortgagee → declarations. The promise to pay → insuring
agreement. Duties after a loss, cancellation, appraisal, other insurance →
conditions. What is not covered → exclusions.

**Binder questions**, testing that it is temporary, may be oral, and binds
the insurer to the same terms as the policy.

**Certificate questions**, testing that it confers no coverage on the holder.

**Endorsement precedence** — where an endorsement conflicts with the printed
form, the endorsement governs.

## Check yourself

1. Which part of the policy names the mortgagee?
2. A policy period reads "1 March 2026 to 1 March 2027". Is a loss at 3 p.m.
   on 1 March 2027 covered?
3. An agent with binding authority binds coverage by phone. The insurer's
   underwriter would have declined the risk. Is there coverage?
4. A contractor gives a property owner a certificate of insurance. The
   contractor's policy is cancelled a week later and a loss occurs. Does the
   owner have coverage under the certificate?
5. An endorsement says "windstorm excluded"; the printed form lists windstorm
   as a covered peril. Which governs?

## Answers

1. The **declarations**.
2. **No.** Coverage ended at 12:01 a.m. on 1 March 2027. The policy period is
   inclusive of its start and exclusive of anything after its stated end time.
3. **Yes.** Binding authority is the authority to obligate the insurer;
   whether the underwriter would have chosen the risk is a matter between
   agent and insurer.
4. **No.** A certificate is evidence of coverage as of its issue date and
   creates none of its own. The owner needed additional insured status.
5. The **endorsement**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '81867de3-86a9-5968-bbae-bc683f8aa8b6', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

commit;
