-- Texas Exam Prep — content seed, chunk 4 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Insuring Agreement, Conditions and Exclusions',
       'insuring-agreement-conditions-and-exclusions', 'The promise, the rules attached to it, and the reasons an insurer says no.', 2,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', c.id, $lesson$# The promise and everything that qualifies it

The declarations tell you whose policy this is. These three parts tell you
what it does.

## The insuring agreement

**The insuring agreement is the insurer's promise.** It is usually a short
paragraph, and it is the broadest statement in the contract — everything
after it narrows.

It answers three questions: what is covered, against what, and on what
trigger.

### Named peril and open peril

This is the most-tested distinction in property insurance.

**A named peril policy covers only the perils it lists.** If the cause of
loss is not on the list, there is no coverage. Fire, lightning, windstorm,
hail, explosion, riot, aircraft, vehicles, smoke, vandalism, theft.

**An open peril policy covers every cause of loss except those excluded.**
Also called "all risk" or "special form" — though "all risk" is a misleading
name, because no policy covers everything. The exclusions define it.

**Where the burden of proof sits is the reason this matters.**

- Under a **named peril** form, **the insured** must show the loss was caused
  by a listed peril.
- Under an **open peril** form, **the insurer** must show the loss falls
  within an exclusion.

That shift is worth more to an insured than the list of perils is, and it is
the answer to "why does an open peril form cost more?"

### Occurrence and claims-made

In liability insurance the insuring agreement also states a **trigger**.

- An **occurrence** policy responds to injury or damage that **happens during
  the policy period**, no matter when the claim is made. A 2026 policy still
  answers a claim brought in 2034 for a 2026 injury.
- A **claims-made** policy responds to claims **first made during the policy
  period**, subject to a **retroactive date**. Injury before the retroactive
  date is not covered no matter when the claim arrives.

Claims-made forms need **tail coverage** — an extended reporting period — when
the policy ends, or claims arriving after expiry have nothing to attach to.

## Conditions

**Conditions are the rules of the contract** — what each side must do, and
what happens if they do not. They appear as a numbered list, and a great many
exam questions live here.

The recurring ones:

- **Duties after a loss** — notice, proof of loss, protecting property,
  cooperating. Covered in its own lesson.
- **Cancellation and non-renewal** — who may end the policy, how, and with
  how much notice.
- **Other insurance** — how this policy shares with another covering the same
  loss.
- **Subrogation** — the insurer's right to step into the insured's shoes and
  pursue whoever caused the loss.
- **Appraisal** — how a dispute over the *amount* of a loss is resolved.
- **Assignment** — the policy may not be transferred to somebody else without
  the insurer's written consent. Insurance is a **personal contract**: the
  insurer agreed to cover *this* insured, and selling the building does not
  sell the policy with it.
- **Abandonment** — property may not be abandoned to the insurer. The insured
  cannot dump a damaged item on the insurer's doorstep and demand the limit.
- **Liberalization** — if the insurer broadens the form during the policy
  period without extra premium, existing insureds get the broader coverage
  automatically.
- **Inspection and audit** — the insurer may inspect the property and examine
  the books, which matters where premium depends on payroll or sales.
- **Concealment, misrepresentation or fraud** — the policy is void where the
  insured has concealed or misrepresented a material fact.

**Conditions are promises, and breaking one can cost the claim.** That is the
practical difference between a condition and an exclusion: an exclusion says
the loss was never covered; a breached condition says it was, and the insured
forfeited it.

## Exclusions

**Exclusions remove coverage the insuring agreement would otherwise have
given.** They are not arbitrary. Each one exists for a reason, and the exam
asks about the reason as often as the exclusion.

### Why insurers exclude things

- **The loss is not fortuitous.** Wear and tear, deterioration, rust,
  inherent vice, mechanical breakdown. These are certainties on a long enough
  timescale, so they are maintenance, not risk.
- **The loss is catastrophic.** Flood, earthquake, war, nuclear hazard. The
  law of large numbers fails where one event hits every policy at once.
- **Coverage belongs in another policy.** Auto exposures are excluded from
  homeowners; professional liability from the CGL; workers' compensation from
  employers' general liability. Excluding here is not refusing to insure — it
  is directing the risk to the form built for it.
- **The loss is intentional.** No policy covers damage the insured caused on
  purpose. This is public policy, not underwriting.
- **The risk needs separate underwriting or pricing.** Business pursuits in a
  home, high-value jewellery, aircraft. Often the exclusion can be bought back
  by endorsement.

### Standard exclusions worth recognising

- **Ordinance or law** — the extra cost of rebuilding to a current building
  code. The code changed; the policy insured the building as it was.
- **Earth movement** and **water damage** (surface water, flood, sewer
  backup) — both usually available by endorsement or separate policy.
- **Wear and tear, latent defect, inherent vice**.
- **Intentional loss**.
- **War**, **nuclear hazard**, **governmental action** (seizure, destruction
  by order).
- **Neglect** — failing to save property at and after the loss.

### Limitations are not exclusions

A **limitation** caps coverage rather than removing it. A homeowners policy
covering theft of jewellery up to $1,500 has not excluded jewellery; it has
limited it. The fix is different too — a limitation is raised by **scheduling
the property**, an exclusion is removed by **buying it back**.

## How this is examined

**Named peril versus open peril**, and specifically **who must prove what**.

**"Why is this excluded?"** — match the exclusion to its reason:
non-fortuitous, catastrophic, covered elsewhere, intentional, separately
underwritten.

**Occurrence versus claims-made**, usually with a date sequence and a
retroactive date.

**Conditions as forfeiture** — the insured who waits eight months to report,
or refuses to submit to examination under oath, or assigns the policy without
consent.

**Ordinance or law**, which reliably catches people, because the rebuilding
cost feels like part of the fire loss and is not.

## Check yourself

1. A loss is caused by something not listed as a covered peril, under a named
   peril form. Who has failed to prove what?
2. An insured sells an insured building and hands the buyer the policy. Is
   the buyer covered?
3. A restaurant's walk-in freezer fails from age and the food spoils. Covered
   under an open peril form? Why or why not?
4. A claims-made policy has a retroactive date of 1 January 2024. A claim is
   made in March 2026 for an injury in 2023. Covered?
5. A fire destroys 60% of a building. The city requires the remainder be
   demolished and the replacement built to current code, adding $80,000.
   Which exclusion is in play?

## Answers

1. **The insured** has failed to prove the loss was caused by a covered
   peril. Under a named peril form that burden is theirs.
2. **No.** Insurance is a personal contract and the assignment condition
   requires the insurer's written consent.
3. **No.** Mechanical breakdown and wear and tear are excluded — the loss is
   not fortuitous. Equipment breakdown coverage is the form that answers it.
4. **No.** The injury predates the retroactive date.
5. **Ordinance or law.** The policy insured the building that existed, not the
   one the current code requires.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2da74bbd-1d0b-54d0-8416-3d7bdc7a7cea', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2c031b02-af62-5980-b6b9-fbeeece995c1', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Who Is an Insured',
       'who-is-an-insured', 'Named insured, first named insured, additional insured, mortgagee — four different things the exam refuses to let you blur.', 3,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2c031b02-af62-5980-b6b9-fbeeece995c1', c.id, $lesson$# Four kinds of people with rights under one policy

"The insured" is not one category. The exam separates them, and each has a
different set of rights.

## The named insured

**The named insured is the person or entity listed on the declarations.**
They own the policy. They have the full set of rights: to receive the
proceeds, to make changes, to cancel, to receive notices, to pay the premium.

Under most personal forms the definition reaches further than the name
printed. A homeowners policy typically extends "insured" to **residents of
the household who are relatives**, and to **other residents under 21 in the
care of an insured**. A student living away from home who is still a resident
of the household usually stays covered.

A personal auto policy typically extends to the named insured and **spouse if
a resident of the same household**, to **family members**, and to **anyone
using a covered auto with permission** — permissive use being the reason
lending the car lends the insurance with it.

## The first named insured

Where several names appear, **the first one has duties and rights the others
do not**. The exam tests this directly, especially in commercial lines.

The first named insured:

- **receives cancellation and non-renewal notices** on behalf of all,
- **is responsible for the premium**,
- **may cancel the policy**,
- **may request changes** to it,
- **receives any return premium**, and
- **is responsible for premium audits** where the policy is auditable.

So a notice of cancellation sent to the first named insured is effective
against every insured on the policy.

## Additional insureds

**An additional insured is somebody added to the policy by endorsement who
gains coverage for their liability arising out of the named insured's work or
premises.**

Typical: a general contractor added to a subcontractor's CGL; a landlord
added to a tenant's policy; a lender added to a commercial policy.

Three points:

- **It takes an endorsement.** A certificate of insurance does not create
  additional insured status, however often somebody treats it as if it does.
- **The coverage is limited in scope.** The additional insured is covered for
  liability connected to the named insured's operations — not for everything
  they do.
- **They do not own the policy.** They cannot cancel it or change it, and in
  most forms they are not entitled to notice of cancellation unless the
  endorsement says so.

## Mortgagee rights

Where property secures a loan, the lender has an **insurable interest** and
is named on the declarations as **mortgagee** (in auto and personal property,
the equivalent is a **loss payee**).

**The standard mortgage clause gives the mortgagee rights independent of the
insured's conduct.** This is the part that gets examined:

- **Loss payment.** Payment for damage to the building is made to the insured
  and mortgagee **jointly**, as their interests appear.
- **The mortgagee is protected from the insured's acts.** If the insured
  commits an act that voids their own coverage — concealment,
  misrepresentation, an increase in hazard, even arson — **the mortgagee is
  still paid**, provided the mortgagee had no part in it. This is the
  distinguishing feature of a *standard* (or union) mortgage clause.
- **The mortgagee gets its own notice.** The insurer must notify the
  mortgagee of cancellation or non-renewal, typically with its own notice
  period, separate from the insured's.
- **The mortgagee may pay the premium** and submit its own proof of loss if
  the insured fails to.
- **The insurer gains subrogation against the insured.** Where the insurer
  pays the mortgagee on a claim it would have denied to the insured, it
  receives the mortgagee's rights against the insured to that extent.

Contrast the **open mortgage clause** (or loss payable clause), which merely
directs payment to the lender and gives it **no rights beyond the insured's**.
If the insured's coverage is void, so is the lender's. "Standard protects the
mortgagee from the insured's acts; open does not" is the whole distinction.

## Loss payees and additional interests

A **loss payee** is named to receive payment for damage to specific property
in which it has an interest — a finance company on a vehicle, a lessor on
equipment. Payment rights, not the broader protections of a standard mortgage
clause.

An **additional interest** or **interested party** is merely notified of
policy changes; it receives no payment rights at all.

## How this is examined

**First named insured duties** — who gets notice, who pays, who can cancel.

**Standard versus open mortgage clause**, nearly always through a fact
pattern where the insured did something that voids their coverage and the
question is whether the lender is paid.

**Additional insured versus certificate holder** — the certificate confers
nothing.

**Permissive use** in auto: the friend who borrows the car is an insured.

**Resident relatives and students away at school** in homeowners.

## Check yourself

1. A commercial policy names three entities. To whom must the insurer send
   notice of cancellation?
2. An insured deliberately burns down a mortgaged building. There is a
   standard mortgage clause. Is the mortgagee paid?
3. Same facts, but an open loss payable clause. Is the lender paid?
4. A subcontractor's certificate of insurance names the general contractor as
   certificate holder. A claim arises from the sub's work. Is the general
   contractor an insured?
5. A neighbour borrows the insured's car with permission and causes an
   accident. Whose policy responds first?

## Answers

1. The **first named insured** — notice to them is effective for all.
2. **Yes**, provided the mortgagee had no part in the arson. The insurer then
   acquires the mortgagee's rights against the insured.
3. **No.** An open clause gives the lender no rights greater than the
   insured's, and the insured has none.
4. **No.** Certificate holder status confers no coverage; an additional
   insured endorsement was needed.
5. **The car owner's.** Auto liability follows the car, and a permissive user
   is an insured under the owner's policy.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2c031b02-af62-5980-b6b9-fbeeece995c1', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '50ab4b8b-d265-58a3-b2b7-3c9c700dc9f8', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Duties After a Loss',
       'duties-after-a-loss', 'What the insured must do, what the insurer must do, and the difference between notice of claim and proof of loss.', 4,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '50ab4b8b-d265-58a3-b2b7-3c9c700dc9f8', c.id, $lesson$# The obligations that survive the loss

A covered loss is not the same as a paid claim. Between the two sits a list of
duties, and failing one can cost the insured the payment.

## The insured's duties

The list is close to identical across property forms:

1. **Give prompt notice** to the insurer or its agent. In theft, also notify
   the **police**. In credit card forgery, also notify the **card issuer**.
2. **Protect the property from further damage.** Make reasonable emergency
   repairs and keep the receipts — reasonable costs of protecting the property
   are usually payable.
3. **Prepare an inventory** of damaged personal property, showing quantity,
   description, cost and the amount of loss claimed.
4. **Exhibit the damaged property** as often as reasonably required, and allow
   the insurer to inspect it.
5. **Submit a signed, sworn proof of loss**, usually within 60 days of the
   insurer's request.
6. **Cooperate** — produce records, answer questions, and **submit to
   examination under oath** if asked, separately from other insureds.
7. **Do not admit liability or make voluntary payments** (liability forms).
   Forward every demand, notice and legal paper to the insurer at once.

**Numbers 2 and 7 are the ones candidates get wrong.** Protecting the property
is a duty, not a courtesy — the "neglect" exclusion removes coverage for
damage the insured let happen by failing to act. And admitting fault at the
scene interferes with the insurer's right to defend.

## Notice of claim versus proof of loss

Two different things, tested as though they are one.

| | Notice of claim | Proof of loss |
| --- | --- | --- |
| What | Tells the insurer a loss occurred | States the amount and circumstances |
| Form | Usually may be oral; written is better | **Signed and sworn**, in writing |
| When | **Promptly** / as soon as practicable | Usually **within 60 days of the insurer's request** |
| Purpose | Lets the insurer investigate while evidence is fresh | Lets the insurer verify and quantify |

A proof of loss states the time and cause of loss, the interests of everybody
in the property, other insurance, changes in title or occupancy, and the
amount claimed.

## The insurer's obligations

The duties run both ways. An insurer must:

- **Investigate** the claim promptly and reasonably.
- **Defend** the insured against covered liability claims — including suits
  that are groundless, false or fraudulent. **The duty to defend is broader
  than the duty to pay**, and defence costs are generally paid *in addition
  to* the limit of liability.
- **Pay covered claims** within the time the policy and state law require.
- **Give notice** of cancellation or non-renewal as required.
- **Act in good faith.** An insurer that denies a claim without a reasonable
  basis exposes itself to more than the policy limit.

The duty to defend **ends when the limit of liability is exhausted** by
payment of judgments or settlements. That is the practical reason a liability
limit is worth more than it looks.

## Loss settlement and consent to settle

**Loss settlement provisions say how much is paid** — actual cash value,
replacement cost, or something else. Where a form pays replacement cost, it
normally pays **actual cash value first** and the **holdback** (the
depreciation) only once the repair or replacement is actually complete.
An insured who never rebuilds gets ACV.

**Consent to settle** is a liability provision. Two versions:

- **The insurer may settle at its discretion.** Standard in most commercial
  and personal liability forms. The insured has no veto, which can be
  uncomfortable when a settlement implies fault.
- **Consent to settle required** — the insurer may not settle without the
  insured's agreement. Usual in professional liability, where a settlement
  damages a reputation and may be reportable.

Where consent is required, forms often include a **"hammer clause"**: if the
insured refuses a settlement the insurer recommends, the insurer's liability
is capped at what the settlement would have cost, and the insured funds
anything above it.

## Appraisal

Where the insured and insurer agree the loss is covered but disagree on
**how much**, the **appraisal** condition resolves it.

Either party may demand it. Each selects a competent, independent appraiser;
the two appraisers select an **umpire**. An agreement between **any two of
the three** sets the amount. Each party pays its own appraiser and they share
the umpire's cost equally.

**Appraisal settles amount, not coverage.** A dispute about whether the peril
is covered is not an appraisal question, and demanding appraisal does not
waive the insurer's right to deny the claim on coverage grounds.

## How this is examined

**"What must the insured do after a theft?"** — notify the insurer *and* the
police.

**Notice versus proof of loss**, usually by asking which must be sworn, or
which has a 60-day clock.

**Voluntary payments** — the insured who pays the claimant out of pocket and
asks to be reimbursed.

**Duty to defend is broader than the duty to pay**, and defence costs sit
outside the limit until the limit is exhausted.

**Appraisal**, testing that it decides amount and not coverage, and that two
of three agreeing is enough.

**Replacement cost holdback** — the insured who takes the ACV cheque and does
not rebuild.

## Check yourself

1. An insured's car is stolen. What two notifications are required?
2. A storm breaks a window. The insured leaves it open for three weeks and
   rain ruins the floor. Is the floor damage covered?
3. Is a proof of loss required to be in writing?
4. A policy has a $500,000 limit. A covered suit costs $120,000 to defend and
   settles for $500,000. What has the insurer paid in total?
5. The insured says a fire loss is $90,000; the insurer says $60,000. Both
   agree fire is covered. What provision applies, and who decides?
6. A homeowner with replacement cost coverage suffers a $40,000 loss on
   property with an ACV of $28,000, and does not rebuild. What is paid?

## Answers

1. The **insurer** and the **police**.
2. **No.** The insured breached the duty to protect the property from further
   damage; the neglect exclusion applies.
3. **Yes** — it must be written, signed and sworn.
4. **$620,000.** Defence costs are paid in addition to the limit.
5. **Appraisal.** Each side appoints an appraiser, the appraisers choose an
   umpire, and agreement by any two of the three sets the amount.
6. **$28,000**, the actual cash value. The replacement cost holdback is
   payable only once the property is actually repaired or replaced.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '50ab4b8b-d265-58a3-b2b7-3c9c700dc9f8', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

commit;
