-- Texas Exam Prep — content seed, chunk 5 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '89857f27-1358-579a-b69e-dbca1ba1bf2a', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Cancellation and Non-renewal',
       'cancellation-and-nonrenewal', 'Who may end a policy, how much warning is owed, and how the return premium is worked out.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '89857f27-1358-579a-b69e-dbca1ba1bf2a', c.id, $lesson$# Ending a policy early, and letting one run out

Two different events, with two different sets of rules. The exam checks that
you know which is which.

- **Cancellation** ends a policy **before** its expiry date.
- **Non-renewal** lets a policy **reach** its expiry date and decline to offer
  another term.

## Cancellation by the insured

**The insured may cancel at any time, for any reason.** Notice to the insurer
is all that is required; no waiting period applies to the insured.

Where several names appear, only the **first named insured** may cancel.

## Cancellation by the insurer

The insurer's freedom is much narrower, and narrows further the longer the
policy has been in force.

**During the first 60 days** — often called the underwriting or "new business"
window — an insurer may generally cancel for **any lawful reason**, because it
is still deciding whether it wanted the risk. Notice is still required.

**After that window**, most forms and most states restrict the insurer to a
short list of reasons:

- **Non-payment of premium.**
- **Material misrepresentation or fraud** in obtaining the policy or in
  presenting a claim.
- **A substantial change in the risk** that increases the hazard.
- **Loss of reinsurance** or a similar regulatory ground.
- **Violation of the policy's terms or of insurance law.**

### Notice periods

The general pattern, which a specific state's law may vary:

- **Non-payment of premium** — a short notice, commonly **10 days**.
- **Any other reason** — a longer notice, commonly **30 days**.
- **Non-renewal** — commonly **30 days** before expiry.
- **The mortgagee** gets its own notice, on its own clock.

> **Texas sets its own numbers.** Chapter 551 of the Texas Insurance Code
> governs declination, cancellation and non-renewal in Texas, and its periods
> and permitted reasons are what a Texas exam question is testing. Learn the
> general pattern here; learn the Texas figures in the Texas statutes module.

Notice must be **in writing**, sent to the first named insured at the address
shown on the declarations. Mailing is generally sufficient — proof of mailing
is proof of notice, and the insurer does not have to show the insured read it.

## Return premium: flat, pro rata and short rate

When a policy ends early, unearned premium comes back. **How much depends on
who cancelled.**

**Flat cancellation** — the policy is cancelled **before it takes effect** or
before any premium is earned. **The entire premium is returned.**

**Pro rata** — the insured is charged only for the exact time the policy was in
force. **Used when the insurer cancels**, because the insured did not choose
to end it and should not be penalised.

> Earned premium = annual premium × (days in force ÷ days in the policy term)

**Short rate** — the insured is charged for the time in force **plus a penalty**
for the insurer's unrecovered expenses. **Used when the insured cancels.**
The return is less than pro rata.

The rule to hold: **insurer cancels → pro rata; insured cancels → short rate.**
The party who caused the early ending bears the cost of it.

### Worked example

An annual policy costs **$1,200** and is cancelled after **90 days** of a
365-day term.

- **Pro rata** (insurer cancelled): earned = $1,200 × 90/365 = **$295.89**.
  Return = **$904.11**.
- **Short rate** (insured cancelled): earned is the pro rata figure *plus* a
  penalty from the insurer's short-rate table, so the return is **less than
  $904.11**.

You are unlikely to be asked to compute a short-rate penalty — the table is
the insurer's. You are very likely to be asked **which method applies**.

## Non-renewal

Non-renewal is not a judgement on the insured in the way cancellation is. The
policy ran its course; the insurer is declining to offer another.

- **Notice is required** — commonly 30 days before expiry — and must be in
  writing.
- **No notice generally means the policy renews**, which is the practical
  reason insurers take the deadline seriously.
- Many states require the insurer to **state the reason** on request.
- A change in terms at renewal — a higher deductible, a new exclusion — often
  triggers the same notice requirement as a non-renewal, because the insured
  needs time to shop.

## Related terms

**Declination** is a refusal to issue in the first place. No policy ever
existed, so cancellation rules do not apply — but the statutes that regulate
declination often do.

**Rescission** treats the policy as though it never existed, usually for
material misrepresentation, and returns the premium. It is not cancellation:
cancellation ends coverage going forward, rescission unwinds it from the
start.

**Lapse** is the ending of a policy for non-payment without further action.

## How this is examined

**Pro rata versus short rate** — nearly always by asking who cancelled.

**Notice periods**, most often 10 days for non-payment and 30 for other
reasons.

**Permitted reasons after the underwriting window** — a question offering
"the insurer no longer likes the risk" as a reason to cancel a three-year-old
policy is testing whether you know that is not one.

**Cancellation versus non-renewal versus declination.**

**Who may cancel** where several insureds are named.

## Check yourself

1. An insurer cancels a policy at the 200-day mark of an annual term. Pro
   rata or short rate?
2. A policy has been in force four years. The insurer wants to cancel because
   the underwriter has re-evaluated the class of business. Permitted?
3. An insured cancels an $1,800 annual policy after six months. Will the
   return premium be more or less than $900?
4. The insurer decides not to renew but sends no notice. What is the usual
   consequence?
5. A policy is cancelled the day before its effective date. What is returned?

## Answers

1. **Pro rata.** The insurer cancelled.
2. **No.** After the underwriting window the insurer is limited to the
   permitted grounds; second thoughts about the class is not one.
3. **Less than $900.** The insured cancelled, so short rate applies and a
   penalty is deducted from the pro rata return.
4. **The policy renews.** Failing to give notice within the required period
   obliges the insurer to offer another term.
5. **The entire premium** — a flat cancellation.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '89857f27-1358-579a-b69e-dbca1ba1bf2a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '52333f53-7203-52c7-90e1-39181aad19a7', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Other Insurance, Subrogation and Supplementary Payments',
       'other-insurance-subrogation-and-supplementary-payments', 'How two policies covering one loss divide it, how the insurer recovers from whoever caused it, and what a liability policy pays on top of the limit.', 6,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '52333f53-7203-52c7-90e1-39181aad19a7', c.id, $lesson$# Three conditions that all protect the same principle

Indemnity says an insured is restored, not enriched. Two of these conditions
enforce it. The third is the exception that proves the rule.

## Other insurance

**When more than one policy covers the same loss, the insured still collects
only once.** The other insurance condition decides how the insurers divide
it.

### Pro rata

**Each insurer pays the share its limit bears to the total of all limits.**
The standard method for property insurance.

> Insurer's share = (its limit ÷ total of all limits) × the loss

Two policies, $300,000 and $100,000, covering a $40,000 loss:

- Total limits = $400,000
- The $300,000 policy pays 300/400 × $40,000 = **$30,000**
- The $100,000 policy pays 100/400 × $40,000 = **$10,000**

The insured collects **$40,000** — the loss, not $80,000.

### Contribution by equal shares

**Each insurer pays equal amounts until the loss is paid or its limit is
exhausted**, after which the rest continue. Common in liability insurance.

A $90,000 loss against limits of $100,000 and $50,000: each pays $45,000.
Had the loss been $120,000, the smaller policy would stop at $50,000 and the
larger would pay $70,000.

### Primary and excess

**One policy pays first and the other only after the first is exhausted.**
Not sharing — a queue.

The exam's standard illustrations:

- **Auto liability follows the car.** The owner's policy is **primary**; the
  driver's own policy is **excess**.
- A **homeowners** policy is primary for premises liability; a **personal
  umbrella** sits excess above it.
- **Non-owned** auto coverage in a business auto policy is typically excess
  over the vehicle owner's insurance.

### Excess and escape clauses

An **excess clause** says this policy pays only above other collectible
insurance. An **escape clause** says it pays nothing at all where other
insurance exists. Where two policies both claim to be excess, courts usually
make them share; where an escape clause would leave the insured with nothing,
it is often disregarded.

## Subrogation

**Subrogation is the insurer's right, after paying a claim, to step into the
insured's position and pursue whoever caused the loss.**

Three reasons it exists, all worth knowing:

1. **It preserves indemnity.** Without it, an insured could collect from the
   insurer and then sue the wrongdoer and end up ahead.
2. **It puts the cost on the party at fault**, not on the insurer's pool of
   policyholders.
3. **It holds premiums down**, since recoveries return to the pool.

### The rules

- **The insurer's rights are no better than the insured's.** If the insured
  had no claim against the third party, neither has the insurer.
- **The insured must not prejudice the right.** Signing a waiver of recovery
  *after* a loss can void coverage. Signing one *before* a loss — a hold
  harmless in a lease or construction contract — is usually permitted, and
  the exam likes this before-and-after distinction.
- **The insured must cooperate** in the recovery action.
- **Recovery order.** The insured is generally made whole first: money
  recovered goes to the insured's uninsured loss (including the deductible)
  before the insurer recoups.
- **No subrogation against your own insured.** An insurer cannot subrogate
  against a party insured under the same policy.

Subrogation applies to **property and liability** insurance, which are
contracts of indemnity. It does **not** apply to life insurance or to most
personal accident coverage, which are valued contracts — there is no
"wrongdoer to recover from" in the indemnity sense, and no over-recovery to
prevent.

## Supplementary payments

**Supplementary payments are amounts a liability policy pays in addition to
its limit of liability.** This is the exception to indemnity's tidiness: the
insurer pays these because defending the claim is in its own interest.

The list is stable across liability forms:

- **Defence costs** — attorney's fees and the expense of investigating and
  defending, including claims the insurer believes to be groundless.
- **The cost of bonds to release attachments**, up to the policy limit.
- **The premium on appeal bonds** — the insurer pays the premium, not the
  face amount of the bond.
- **The premium on bail bonds** arising from a covered accident, subject to a
  stated maximum (commonly $250 in auto forms).
- **Reasonable expenses incurred by the insured at the insurer's request**,
  including lost earnings up to a stated daily amount (commonly $250).
- **Post-judgment interest** on the entire judgment, and **pre-judgment
  interest** where awarded.
- **Court costs** taxed against the insured.

Two things to keep straight:

- **The insurer pays the premium for a bond, not the bond itself.** A
  question offering "the insurer posts a $100,000 appeal bond" is testing
  exactly this.
- **Supplementary payments stop when the limit is exhausted.** Once the
  insurer has paid its limit in judgments or settlements, the duty to defend
  ends and so do these.

## How this is examined

**Pro rata calculations** with two limits and one loss — the arithmetic is
easy; the trap is answering with the total of both payments as though the
insured collected twice.

**Primary versus excess in auto**, through the borrowed-car fact pattern.

**Waiver of subrogation before versus after a loss.**

**Defence costs outside the limit**, and the moment they stop.

**Bond premium versus bond amount** in supplementary payments.

## Check yourself

1. A $60,000 loss is covered by policies with limits of $200,000 and
   $100,000, both pro rata. What does each pay, and what does the insured
   receive?
2. After a fire caused by a contractor's negligence, the insured signs a
   release of the contractor and then claims on the policy. What is the
   likely result?
3. A friend borrows the insured's car and causes an accident. Which policy is
   primary?
4. A liability policy has a $300,000 limit. The insurer spends $75,000
   defending a suit that settles for $300,000. What is the total outlay, and
   what happens to a second suit arriving the next week?
5. An insurer pays a $10,000 claim on which the insured bore a $1,000
   deductible, then recovers $6,000 from the party at fault. Who gets what?

## Answers

1. The $200,000 policy pays 200/300 × $60,000 = **$40,000**; the $100,000
   policy pays **$20,000**. The insured receives **$60,000** — the loss.
2. Coverage is likely **void** for that loss. The insured destroyed the
   insurer's subrogation right after the loss occurred.
3. **The car owner's policy** is primary; the driver's own policy is excess.
4. **$375,000** — defence costs are in addition to the limit. The limit is
   now exhausted, so the insurer has **no duty to defend** the second suit.
5. The insured is generally made whole first, so the **$1,000 deductible**
   comes back to the insured and the insurer keeps **$5,000**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '52333f53-7203-52c7-90e1-39181aad19a7', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

commit;
