-- Texas Exam Prep — content seed, chunk 6 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Elements of a Contract',
       'elements-of-a-contract', 'The four things every contract needs, and the six ways an insurance contract is unlike most others.', 7,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', c.id, $lesson$# Why a policy is a contract, and what kind

An insurance policy is a legally enforceable agreement. The exam asks two
separate questions about that: what makes it enforceable at all, and what
makes it a peculiar sort of contract.

## The four elements

Every contract, insurance or otherwise, requires all four. Miss one and there
is no contract.

### 1. Offer and acceptance — "agreement"

One party proposes terms; the other accepts them.

**In insurance, the applicant makes the offer.** This catches people out,
because it feels as though the insurer, with its brochures and rate tables,
is the one offering. It is not. The applicant offers by submitting a
completed application **with the initial premium**; the insurer accepts by
**issuing the policy** — or by **binding coverage**, where the agent has
binding authority.

A **counter-offer** is a rejection of the original offer plus a new one. If
the insurer issues a policy on terms different from those applied for — a
higher premium, an added exclusion — it has made a counter-offer, and the
applicant is free to decline.

### 2. Consideration

**Each side must give up something of value.**

- **The insured's consideration** is the premium *and* the statements made in
  the application.
- **The insurer's consideration** is the promise to pay covered losses.

Note that the insurer's consideration is a *promise*, not money. It is the
promise that makes the contract binding, which is why an insurer that never
has a claim has still given full consideration.

### 3. Competent parties

**Both parties must be legally capable of contracting.** Generally this
excludes minors, persons legally declared incompetent, and those under the
influence of drugs or alcohol at the time of contracting. The insurer must
also be competent — that is, **licensed and authorised** to transact
insurance in the state.

### 4. Legal purpose

**The contract must not be for an illegal purpose or contrary to public
policy.** Insuring a smuggling operation, or insuring property in which you
have no insurable interest so that you profit from its destruction, fails
here. **Insurable interest is the legal purpose requirement doing its work**
in insurance — without it, the contract is a wager.

Some texts add a fifth, **legal form**, meaning the policy must meet the
form requirements the state imposes. Where a question offers four elements,
they are the four above.

## The distinguishing characteristics

An insurance contract has six features that mark it out. These are reliably
examined, usually by giving a definition and asking for the word.

**Adhesion.** One party writes it; the other takes it or leaves it. The
insured does not negotiate clause by clause.

> **The consequence is the rule you must know: ambiguity is construed against
> the drafter.** Where a policy term can reasonably be read two ways, the
> reading favourable to the insured wins — because the insurer chose the
> words. This principle, *contra proferentem*, is the single most useful
> thing to take from this lesson.

**Aleatory.** The exchange of value is **unequal and depends on chance**. An
insured pays $1,200 and may collect nothing, or may collect $400,000. A
non-aleatory contract — buying a car — exchanges roughly equal value both
ways.

**Unilateral.** **Only one party makes a legally enforceable promise.** Once
the premium is paid, the insured has promised nothing further; the insurer
alone is bound to perform. The insured who stops paying is not sued for
breach — the policy simply lapses.

**Conditional.** **Performance depends on conditions being met.** The insurer
pays only if a covered loss occurs and the insured has met their duties —
notice, proof of loss, cooperation.

**Personal.** **The contract is with a person, not a thing.** It follows the
insured, not the property, which is why it may not be assigned without the
insurer's consent. Selling the building does not sell the policy.

**Utmost good faith** (*uberrimae fidei*). **Both parties rely on the other's
honesty to a degree ordinary commerce does not require.** The insurer cannot
inspect every fact about the risk, so it relies on the applicant's disclosure;
the insured relies on the insurer's promise to pay a claim years away. This is
the principle beneath representations, warranties and concealment.

A useful check: **A**dhesion, **A**leatory, **U**nilateral, **C**onditional,
**P**ersonal, **U**tmost good faith.

## Agency: why the agent's knowledge is the insurer's

An agent represents the **insurer**. A broker represents the **insured**.
That difference decides who is bound by what.

An agent's authority comes in three forms:

- **Express** — what the agency agreement actually says: solicit, bind, issue
  certain policies, collect premiums.
- **Implied** — what is reasonably necessary to carry out the express
  authority, though unstated. Renting an office, advertising.
- **Apparent** (ostensible) — what a reasonable member of the public would
  believe the agent has, from the insurer's own conduct. An agent still
  holding the insurer's signs, forms and rate manuals after termination can
  bind the insurer to a third party who reasonably relies on them.

Two doctrines follow, and they are examined often:

**Waiver** — the **voluntary surrender of a known right**. An insurer that
accepts a late premium without objection has waived the timeliness of
payment for that occasion.

**Estoppel** — a party is **barred from asserting a right** because their own
earlier conduct led the other to rely on the opposite, to their detriment. An
adjuster who tells the insured not to bother with a formal proof of loss
estops the insurer from later denying the claim for want of one.

**Knowledge of the agent is knowledge of the insurer.** Where an applicant
tells the agent something material and the agent omits it from the
application, the insurer is generally held to have known it.

## How this is examined

**"Who makes the offer?"** The applicant.

**"What is the insured's consideration?"** The premium *and* the statements in
the application.

**Matching definitions to the six characteristics**, most often aleatory,
unilateral and adhesion.

**"Ambiguity is resolved in favour of whom, and why?"** The insured, because
the policy is a contract of adhesion.

**Apparent authority** through a terminated-agent fact pattern.

**Waiver versus estoppel** — voluntarily giving up a right versus being
barred from asserting one.

## Check yourself

1. An applicant submits a completed application with the first premium. Who
   has made the offer, and how does the other party accept?
2. A policy term is capable of two reasonable readings. Which is applied?
3. Which characteristic explains why a policy cannot be assigned to the buyer
   of the insured building?
4. An insured stops paying premium. Can the insurer sue for breach of
   contract? Why or why not?
5. An adjuster tells an insured "don't worry about the proof of loss, we have
   what we need". The insurer later denies the claim for lack of a proof of
   loss. What doctrine applies?
6. An applicant tells the agent about a prior fire loss; the agent leaves it
   off the application. Is the insurer deemed to know?

## Answers

1. **The applicant** made the offer. The insurer accepts by **issuing the
   policy**, or by **binding** coverage through an agent with binding
   authority.
2. The reading **favourable to the insured** — the contract is one of
   adhesion and ambiguity is construed against the drafter.
3. **Personal.** The contract is with the insured, not the property.
4. **No.** The contract is **unilateral**: only the insurer made an
   enforceable promise. The policy lapses instead.
5. **Estoppel.** The insurer's own conduct induced the insured's reliance.
6. **Yes.** Knowledge of the agent is imputed to the insurer.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'a90c9574-8282-5029-ad55-ef10beb16b2c', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'b31412b7-f995-5d58-b589-adb0290d6c73', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Representations, Warranties and Concealment',
       'representations-warranties-and-concealment', 'Four ways an insured can say something wrong, and only some of them cost the policy.', 8,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'b31412b7-f995-5d58-b589-adb0290d6c73', c.id, $lesson$# Saying, not saying, and promising

Utmost good faith is the principle. These four terms are how it is enforced,
and the exam separates them carefully.

## Representations

**A representation is a statement believed to be true when made.**

Nearly every answer on an application is a representation. The standard is
honesty and reasonable belief, not certainty — an applicant who says the roof
is twelve years old and honestly believes it, when it is fourteen, has made a
representation that turned out inaccurate, not a lie.

**A misrepresentation is a false representation.** On its own it is not
enough to void a policy. Two more things are needed:

- **It must be material** — significant enough that the insurer would have
  declined the risk, charged more, or issued different terms had it known the
  truth. An error in a middle initial is not material. An undisclosed prior
  arson conviction is.
- **The insurer must have relied on it** in deciding to issue.

**Material misrepresentation makes a policy voidable at the insurer's
option**, not automatically void. The insurer may rescind, usually returning
the premium — or may choose to continue the policy.

## Warranties

**A warranty is a statement guaranteed to be true.** It is a promise, not a
belief, and it becomes part of the contract.

The standard is absolute. A warranty that turns out untrue is a **breach of
contract**, and the insurer may void the policy — at least in strict theory —
**without showing materiality**.

Two kinds:

- **Affirmative warranty** — a statement of fact **at the time the policy is
  issued**. "A functioning sprinkler system is installed."
- **Promissory** (continuing) **warranty** — a promise that something **will
  remain true throughout the policy period**. "The sprinkler system will be
  maintained in working order."

> **In practice, most states have softened this.** Because the consequences
> of a strict warranty are so harsh, statute in many states treats an
> applicant's statements as representations rather than warranties unless the
> policy says otherwise, and requires materiality before a policy can be
> avoided. Texas's own rules on this sit in the Texas statutes module; learn
> the general doctrine here and the state's modification there.

**Warranties are more common in commercial lines than personal lines**, where
the insurer is relying on the insured to maintain a specific protective
feature that was priced into the premium.

## Concealment

**Concealment is the deliberate withholding of a material fact the applicant
knew and was obliged to disclose.**

The distinction from misrepresentation is that concealment is **silence**
rather than a false statement. The elements:

- The fact was **material**;
- the applicant **knew** it; and
- the withholding was **intentional**.

That last element is why concealment is harder to prove than
misrepresentation and, when proved, treated more seriously. **Material
concealment makes the policy voidable.**

The boundary the exam probes: **an applicant need not volunteer everything,
but must answer asked questions honestly and must not hide a known material
fact.** Failing to mention a hobby nobody asked about is generally not
concealment. Failing to mention that the building has been condemned is.

## Fraud

**Fraud is an intentional deception to induce another to part with something
of value.** It requires a knowingly false statement of material fact, made
with intent to deceive, relied upon, causing loss.

Fraud is the most serious of the four and the only one that is also a
**crime**. It reaches beyond the application: **claim fraud** — inflating a
loss, claiming property never owned, staging an accident — is fraud whether
or not the original application was honest.

**Fraud makes the policy void**, and it is the one ground on which most
policies remain avoidable no matter how long they have been in force.

## Putting the four side by side

| | What it is | Requires intent? | Effect |
| --- | --- | --- | --- |
| **Representation** | A statement believed true | No | None, if honest |
| **Misrepresentation** | A false representation | No | Voidable **if material and relied on** |
| **Warranty** | A statement guaranteed true | No | Breach — voidable, in strict theory without materiality |
| **Concealment** | Silence about a known material fact | **Yes** | Voidable |
| **Fraud** | Intentional deception for gain | **Yes** | **Void**; also a crime |

Two sentences to carry:

- **Representation = believed true. Warranty = guaranteed true.**
- **Misrepresentation = saying something false. Concealment = not saying
  something true.**

## Incontestability, and why property insurance is different

Life and health policies carry an **incontestable clause**: after a stated
period, usually two years, the insurer may no longer contest the policy for
misstatements on the application.

**Property and casualty policies generally have no such clause.** They are
short-term contracts, renewed and re-underwritten each period, so the
insurer's remedy for a misstatement does not need a deadline. Where a
question offers "incontestability" as an answer to a P&C fact pattern, that
is usually the distractor.

## How this is examined

**Representation versus warranty**, by the believed/guaranteed distinction.

**Misrepresentation versus concealment**, by whether the insured spoke or
stayed silent.

**"Is this material?"** — would the insurer have acted differently had it
known?

**Void versus voidable.** Fraud voids. Material misrepresentation and
concealment make the policy voidable *at the insurer's option*, which means
the insurer may also choose to keep it in force.

**Claim fraud** as distinct from application fraud.

## Check yourself

1. An applicant states the building's roof was replaced in 2019. It was 2017.
   They genuinely misremembered. What is this, and what is the consequence?
2. An applicant knows the property has an open code violation and says
   nothing. No question was asked about it. What is this?
3. A commercial policy is issued on a warranty that a burglar alarm will be
   maintained. The insured disconnects it and a fire — unrelated to the alarm
   — destroys the building. On strict warranty doctrine, what may the insurer
   do?
4. An insured inflates a genuine $8,000 theft claim to $20,000. Which of the
   four is this?
5. Is a property policy subject to an incontestable clause?

## Answers

1. A **misrepresentation**. Whether the insurer may avoid the policy depends
   on whether the two-year difference was **material** and relied on — on
   these facts, probably not.
2. **Concealment** — a known material fact intentionally withheld.
3. Strictly, **void the policy for breach of warranty**, without needing to
   show the breach caused the loss. Many states have modified this by statute
   to require materiality or a causal connection.
4. **Fraud** — specifically claim fraud, and a crime as well as a ground to
   void.
5. **No.** Incontestability is a life and health provision; P&C policies are
   re-underwritten each term.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'b31412b7-f995-5d58-b589-adb0290d6c73', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

commit;
