-- Texas Exam Prep — content seed, chunk 7 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'ef483d9c-5d98-5706-a47a-44f107b8b92b', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Underwriting Information, the FCRA and Privacy',
       'underwriting-information-fcra-and-privacy', 'Where an underwriter''s information comes from, and the two federal laws that govern how it is used.', 9,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'ef483d9c-5d98-5706-a47a-44f107b8b92b', c.id, $lesson$# What the underwriter knows, and the rules on knowing it

Underwriting is the selection and pricing of risk. It runs on information,
and the collection of that information is regulated.

## Sources of underwriting information

**The application.** The primary source, and the one the insured controls.
Answers are representations.

**The agent's report.** The producer's own observations and recommendation,
submitted alongside the application. The agent has seen the property and the
applicant; the underwriter has not.

**Inspection reports.** A physical inspection of the property — construction,
occupancy, protection, exposure. Standard on commercial risks and on
higher-value dwellings.

**Consumer reports and investigative consumer reports.** Purchased from a
consumer reporting agency. The distinction between the two matters and is
covered below.

**Loss history databases.** Industry-wide claim databases let an underwriter
see prior claims on the applicant and, in property, on the **address**, which
is why a claim made by a previous owner can affect a new buyer's premium.

**Motor vehicle records.** Driving history from the state, in auto
underwriting.

**Credit-based insurance scores**, where state law permits their use.

**Financial statements and payroll or sales records**, in commercial lines,
both for underwriting and for the premium audit.

**Claim files and the insurer's own experience** with the applicant.

## The Fair Credit Reporting Act

**The FCRA governs the collection and use of consumer report information**,
including its use in insurance underwriting. Its purpose is accuracy and
fairness, and it gives the consumer rights against both the insurer and the
reporting agency.

### The two kinds of report

**A consumer report** contains information on creditworthiness, credit
standing, character, general reputation or mode of living, drawn from records
and databases.

**An investigative consumer report** obtains that information through
**personal interviews** — with neighbours, friends, associates, employers.

The extra step brings an extra duty: **where an investigative consumer report
may be ordered, the applicant must be told in writing, generally within three
days of the request**, and told that they may ask for a complete disclosure of
its nature and scope.

### Adverse action

**If an insurer declines, cancels, non-renews or charges more because of
information in a consumer report, that is an adverse action**, and the
insurer must:

- **notify the applicant** that the adverse action was taken,
- **identify the consumer reporting agency** that supplied the report,
  including its name, address and telephone number, and
- **state that the agency did not make the decision** and cannot explain it.

The consumer may then obtain a **free copy** of the report from the agency
and **dispute anything inaccurate**. The agency must **reinvestigate**,
generally within 30 days, and correct or delete what it cannot verify. If the
consumer still disagrees, they may file a **statement of dispute** that
accompanies the file.

Most adverse information may be reported for **seven years**; a bankruptcy for
**ten**.

The rule to carry: **the insurer must tell the applicant where the
information came from, and the agency — not the insurer — must fix it.**

## Privacy: the Gramm-Leach-Bliley Act

**GLBA governs how financial institutions, insurers included, handle
non-public personal information.** Where the FCRA is about accuracy, GLBA is
about disclosure and sharing.

Three obligations:

**The privacy notice.** The insurer must give a clear notice of its privacy
practices **at the time the relationship is established** and **annually**
thereafter. It must say what is collected, what is disclosed and to whom.

**The opt-out.** Before disclosing non-public personal information to a
**non-affiliated third party**, the insurer must give the consumer a
reasonable opportunity to **opt out**. Note the shape of it: **opt-out, not
opt-in** — sharing is permitted unless the consumer objects.

Exceptions where no opt-out applies: disclosures necessary to service the
account, process a transaction, or comply with law — including reporting to
regulators and to claim databases.

**The safeguards rule.** The insurer must maintain administrative, technical
and physical safeguards protecting the security and confidentiality of
customer information.

GLBA also addresses **pretexting** — obtaining someone's financial
information under false pretences — which it prohibits.

### The two distinctions to hold

| | FCRA | GLBA |
| --- | --- | --- |
| Concerned with | **Accuracy** of consumer reports and fairness in their use | **Privacy** of non-public personal information |
| Trigger | Adverse action based on a report | Establishing and maintaining the relationship |
| Consumer's tool | Free copy, dispute, reinvestigation | Privacy notice and opt-out |

## Other privacy rules worth recognising

**HIPAA** governs protected health information, which reaches P&C where
medical records are obtained on an injury claim.

**The Do Not Call registry and CAN-SPAM** govern solicitation by telephone
and email.

**Terrorism and sanctions screening** obliges insurers to check parties
against government lists before transacting.

## How this is examined

**Consumer report versus investigative consumer report** — the personal
interview is the whole distinction.

**Adverse action duties** — what the insurer must disclose and to whom the
consumer complains.

**Who corrects an inaccurate report?** The consumer reporting agency, not the
insurer.

**Opt-out versus opt-in** under GLBA.

**Matching the law to the purpose** — FCRA for accuracy, GLBA for privacy.

## Check yourself

1. An underwriter orders a report that will involve interviewing the
   applicant's neighbours. What kind of report is it, and what must the
   applicant be told?
2. An insurer charges a higher premium because of a credit-based insurance
   score. What must it tell the applicant?
3. The applicant believes the report contains an error. Whom do they contact,
   and what must that party do?
4. An insurer wishes to share customer information with an unaffiliated
   marketing company. What must it do first?
5. How long may most adverse information remain on a consumer report?

## Answers

1. An **investigative consumer report**. The applicant must be told **in
   writing, generally within three days** of the request, and told they may
   request disclosure of its nature and scope.
2. That an **adverse action** was taken based on a consumer report; the
   **name, address and telephone number** of the reporting agency; and that
   the agency did not make the decision and cannot explain it.
3. The **consumer reporting agency**, which must **reinvestigate** (generally
   within 30 days) and correct or delete information it cannot verify.
4. Provide a **privacy notice** and a reasonable **opportunity to opt out**.
5. **Seven years**; ten for a bankruptcy.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'ef483d9c-5d98-5706-a47a-44f107b8b92b', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.III'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '65f6bec4-114d-558c-9035-89adbd274ada', 'd6bff6c2-390e-518f-a728-b2a8ee99e87c', c.id, 'Territory and the Terrorism Risk Insurance Act',
       'territory-and-the-terrorism-risk-insurance-act', 'Where a policy works geographically, and the federal backstop that made terrorism insurable again.', 10,
       'draft', 11
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '65f6bec4-114d-558c-9035-89adbd274ada', c.id, $lesson$# Two provisions about where and what

Both are small, both appear in the blueprint twice — once under policy
provisions and contract law, once under casualty policy provisions — and both
are easy marks if you have read them once.

## Territory

**The territory (or policy territory) provision states where coverage
applies.** A policy is not worldwide unless it says so.

The usual definition in general liability and auto forms covers:

- **The United States**, including its territories and possessions;
- **Puerto Rico**; and
- **Canada**.

That is the core. Forms then extend it in two ways:

- **International waters or airspace**, but only in transit between places in
  the territory above.
- **Anywhere in the world** for a narrow set of exposures — typically
  **products** manufactured or sold in the territory that cause injury
  elsewhere, and the **independent activities of a person temporarily
  outside** the territory on the insured's business — **provided the suit is
  brought within the territory**.

That proviso is the examined point. **A worldwide extension usually still
requires that the lawsuit be brought in the United States (or Canada).** A
product made in Texas that injures somebody in Germany is covered if the suit
is filed in a US court; a German judgment obtained in a German court
generally is not.

Property forms take a different approach: **coverage attaches to described
premises**, and property away from the premises is covered only by specific
extensions or by an inland marine form, which is where property genuinely in
transit belongs.

In **personal auto**, the territory is the United States, its territories and
possessions, Puerto Rico and Canada. **Mexico is not included** — a driver
going to Mexico needs a Mexican policy from a Mexican insurer, because Mexico
does not recognise foreign auto insurance. This is a favourite question.

## The Terrorism Risk Insurance Act

### Why it exists

Before September 2001, terrorism was not excluded from most commercial
property and liability policies — it was simply not thought about, and was
covered by silence. The losses that followed made insurers move to exclude
it, and reinsurers to withdraw. Commercial property development stalled where
lenders required terrorism coverage that no longer existed.

**TRIA, enacted in 2002 and extended several times since, is a federal
backstop: the government shares in insured losses from certified acts of
terrorism, so that private insurers can afford to offer the coverage.**

It is a **reinsurance programme**, not an insurance policy. Nobody buys a
policy from TRIA.

### How it works

**Certification.** Losses are covered by the programme only for an act of
terrorism **certified by the Secretary of the Treasury**, in consultation with
other federal officials. Certification requires that the act be violent or
dangerous to human life, property or infrastructure, committed as part of an
effort to coerce the United States civilian population or influence policy,
and that aggregate insured losses **exceed a statutory trigger**.

**Mandatory offer.** **An insurer writing commercial property and casualty
insurance must offer terrorism coverage** on terms not differing materially
from the rest of the policy. This is the obligation that matters to a
producer.

**The insured may decline.** Coverage is not compulsory for the buyer.
Where the insured rejects it, the insurer may attach a terrorism exclusion.
**The rejection should be in writing**, and the premium for the coverage must
be **separately stated** so the insured knows what they are accepting or
declining.

**Loss sharing.** Each insurer retains a deductible calculated as a
percentage of its own earned premium. Above that, the federal government pays
a share of losses and the insurer the remainder, subject to an annual
aggregate cap on the whole programme.

### What it does and does not cover

- It applies to **commercial** lines. Personal lines are outside the
  programme, although personal policies are generally silent on terrorism and
  so tend to cover it.
- **Nuclear, biological, chemical and radiological** losses are generally
  excluded from the coverage offered, unless the underlying policy covers
  them.
- **Domestic as well as foreign** acts have been certifiable since the 2007
  reauthorisation removed the requirement that the act be committed on behalf
  of a foreign interest.
- **Workers' compensation is different.** A workers' compensation insurer
  **may not exclude terrorism at all**, because state law requires the policy
  to cover statutory benefits whatever the cause. The insured has no right to
  decline it there.

That last point is the trap. **Everywhere else the insured may reject
terrorism coverage; in workers' compensation they may not.**

## How this is examined

**Mexico** in personal auto territory.

**The worldwide products extension**, and the requirement that suit be
brought within the policy territory.

**The mandatory offer** — the insurer must offer, the insured may decline,
the premium must be separately stated, the rejection should be written.

**Certification by the Secretary of the Treasury**, not by the insurer or the
state regulator.

**Workers' compensation cannot exclude terrorism.**

## Check yourself

1. An insured drives from Houston to Monterrey. Does the personal auto policy
   respond to an accident there?
2. A product manufactured in the United States injures a consumer in France,
   who sues in a French court. Is the CGL's worldwide extension likely to
   respond?
3. Who certifies an act of terrorism for TRIA purposes?
4. A commercial insured does not want terrorism coverage. May the insurer
   simply leave it out of the quote?
5. May a workers' compensation policy exclude terrorism?

## Answers

1. **No.** Mexico is outside the policy territory; a Mexican policy from a
   Mexican insurer is required.
2. **No.** The extension generally requires the **suit to be brought within
   the policy territory**.
3. **The Secretary of the Treasury**, in consultation with other federal
   officials.
4. **No.** The insurer must **offer** the coverage with the premium
   separately stated; the insured then declines, preferably in writing.
5. **No.** Statutory benefits must be paid whatever the cause, so terrorism
   cannot be excluded from workers' compensation.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '65f6bec4-114d-558c-9035-89adbd274ada', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.VI'
on conflict (lesson_id, topic_id) do nothing;

commit;
