-- Texas Exam Prep — content seed, chunk 9 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Commercial Property and the Package Policy',
       'commercial-property-and-the-package-policy', 'How a commercial package is assembled, the three causes of loss forms, and the income coverages that pay when the building is standing but the business is not.', 3,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', c.id, $lesson$# Building a commercial policy out of parts

Personal lines sells finished packages. Commercial lines sells components,
and the producer assembles them.

## The Commercial Package Policy

**A CPP is two or more commercial coverage parts issued under one policy.**
Its architecture:

1. **Common policy declarations** — insured, term, premium, coverage parts.
2. **Common policy conditions** — cancellation, changes, inspections,
   examination of books, transfer of rights. These apply to every part.
3. **Two or more coverage parts**, each with its own declarations, forms and
   conditions.

The available parts include **commercial property, general liability,
commercial auto, crime, inland marine, boiler and machinery (equipment
breakdown)** and **farm**.

**A single coverage part is a monoline policy; two or more make a package.**
The package earns a discount and removes the gaps and overlaps that separate
policies produce.

**Workers' compensation is written separately**, not as a CPP part.

## The commercial property coverage part

Three things must be assembled:

1. **A coverage form** — what property is covered.
2. **A causes of loss form** — what perils.
3. **Conditions and any endorsements.**

### The building and personal property coverage form

The workhorse. It insures three categories, each separately scheduled on the
declarations:

**Building** — the structure, completed additions, fixtures (including
outdoor fixtures), permanently installed machinery and equipment, and
materials and supplies used to maintain it.

**Your business personal property** — the insured's own contents at the
described premises: furniture, stock, machinery, leased property the insured
is responsible for, and **the insured's use interest in improvements and
betterments** made to a leased building.

**Personal property of others** — property in the insured's care, custody or
control. **Payment goes to the owner**, not to the insured.

The **coinsurance** clause applies, usually at 80%, 90% or 100%, and the
calculation is the one from Module 1.

### Extensions and additional coverages

Typically included: **debris removal** (a percentage of the loss plus the
deductible, with an additional amount available); **preservation of
property**; **fire department service charge**; **pollutant clean-up and
removal**, capped annually; **newly acquired or constructed property** for a
limited period and amount; **personal effects**; **property off premises**;
**outdoor property**; and **valuable papers and records** at a limited
amount.

### Reporting forms and blanket insurance

**Specific insurance** names an amount for one item at one location.

**Blanket insurance** covers **two or more items, or two or more locations,
under a single limit**. The advantage is flexibility: a shifting inventory
across three warehouses is fully covered wherever it sits, rather than being
underinsured at one and over at another. Blanket cover normally requires a
**statement of values** and a high coinsurance percentage.

**Reporting forms** suit a fluctuating inventory: the insured reports values
periodically and the premium is adjusted. Under-reporting is penalised at
claim time in proportion to the shortfall.

**Agreed value** suspends coinsurance where the insurer has accepted a
statement of values.

## The three causes of loss forms

This is the most-tested part of commercial property.

**Basic** — a named peril list: fire, lightning, explosion, windstorm or
hail, smoke, aircraft or vehicles, riot or civil commotion, vandalism,
sprinkler leakage, sinkhole collapse, volcanic action.

**Broad** — everything in Basic **plus** falling objects; weight of snow, ice
or sleet; and water damage from the accidental discharge of a system. It also
adds **collapse** as an additional coverage.

**Special** — **open peril**: every cause of loss except those excluded. The
burden shifts to the insurer. Special also adds coverage for **theft**, which
Basic and Broad do not include.

> **"Special form" means open peril, not "extra".** A question describing a
> loss from an unusual, unexcluded cause is testing whether you know Special
> is the only one of the three that answers it.

An **earthquake** form and a **flood** form exist separately, because neither
is included in any of the three.

## Business income and extra expense

These are **indirect** or **consequential** loss coverages. Direct damage
coverage rebuilds the building; these pay for the trading that could not
happen while it was being rebuilt.

**Business income** (formerly business interruption) pays:

- **the net income the business would have earned**, plus
- **continuing normal operating expenses**, including payroll where covered.

Three conditions frame it: there must be **direct physical loss** to covered
property, **by a covered cause of loss**, at the **described premises**,
causing a **necessary suspension** of operations.

The **period of restoration** begins **72 hours after the physical loss**
(where a waiting period applies) and ends when the property **should** have
been repaired with reasonable speed — not when it actually was. An insured
who takes eight months over a four-month rebuild is paid for four.

**Extra expense** pays the additional costs of **continuing** operations —
renting temporary premises, hiring equipment, expedited shipping. A business
that cannot afford to stop, such as a dairy or a newspaper, buys extra
expense rather than business income; many buy both on a combined form.

Related: **contingent business income** covers loss caused by damage to
**somebody else's** property — a sole supplier or a dominant customer.
**Civil authority** coverage pays where access to the premises is prohibited
by an authority because of damage to nearby property.

## Equipment breakdown

Formerly boiler and machinery. **It covers the sudden and accidental
breakdown of pressure, mechanical and electrical equipment** — and the
resulting damage.

It matters because **mechanical breakdown and electrical arcing are excluded
from every standard property form**, so without this coverage a burst boiler
or a failed transformer is uninsured. It typically covers the damaged
equipment, other property damaged by the breakdown, spoilage, expediting
expenses and business income.

**Inspection is part of the product.** The insurer's engineers inspect
boilers and pressure vessels, often satisfying the jurisdiction's statutory
inspection requirement, and the loss-prevention value is a substantial part of
what the premium buys.

## Builders risk

**Covers a structure under construction**, against loss during the build.

- The limit should equal the **completed value** of the structure.
- **Materials, supplies and equipment** intended to become part of the
  building are covered on site, and often in transit and at temporary
  storage.
- Insurable interest may belong to the **owner, the contractor, or both**,
  and the policy is usually written to name all interested parties.
- **Coverage ends** when the building is accepted, occupied for its intended
  purpose, or the policy expires — whichever comes first. At that point a
  standard property policy takes over.

## Cyber first-party coverage

**First-party cyber coverage pays the insured's own losses from a cyber
event**, as distinct from cyber *liability*, which pays what the insured owes
others.

What it typically covers: **data restoration** and system repair; **business
interruption** from a network outage; **cyber extortion** and ransomware
payments; **breach response costs** — forensics, notification of affected
individuals, credit monitoring, public relations; and **funds transfer
fraud**, where an employee is deceived into sending money.

It exists because standard property forms were written around physical damage
to tangible property, and **electronic data is generally not "tangible
property"** under them. Many forms now exclude cyber events explicitly, so the
coverage is bought deliberately or not at all.

## How this is examined

**Basic versus Broad versus Special**, and specifically that **only Special is
open peril** and **only Special includes theft**.

**Blanket versus specific insurance.**

**Business income versus extra expense** — replacing lost earnings versus
funding continued operation.

**The period of restoration ends when repairs *should* have been completed.**

**Equipment breakdown fills the mechanical breakdown exclusion.**

**Builders risk is written at completed value** and ends at occupancy.

## Check yourself

1. A commercial policy carries the Broad causes of loss form. Stock is stolen
   overnight. Covered?
2. An insured stores inventory across four warehouses, with amounts shifting
   weekly. Blanket or specific?
3. A fire closes a restaurant for five months, though competent repairs would
   have taken three. Business income is $40,000 a month. What is paid,
   broadly?
4. A transformer fails and burns out, damaging nearby equipment. Which
   coverage responds, and why not the property form?
5. A builders risk policy is written for $2m on a building whose completed
   value is $2m. Construction finishes and the owner moves in. What happens to
   the coverage?
6. A ransomware attack encrypts a firm's records and halts trading for a
   week. Which coverage responds?

## Answers

1. **No.** Theft is covered only under the **Special** form.
2. **Blanket**, so the single limit follows the inventory wherever it sits.
3. Roughly **three months** — about **$120,000**. The period of restoration
   ends when repairs **should** have been completed with reasonable speed.
4. **Equipment breakdown.** The standard property forms exclude mechanical
   breakdown and electrical arcing.
5. **It ends** on occupancy for the intended purpose; a standard commercial
   property policy must take over.
6. **First-party cyber coverage** — data restoration, cyber extortion and
   network business interruption. Electronic data is generally not tangible
   property under a standard form.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'fdcf9975-9bd5-5b6a-8eec-66bbd30eddd0', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Inland Marine',
       'inland-marine', 'Coverage for property that moves, property that is unusually valuable, and property no standard form handles well.', 4,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', c.id, $lesson$# Insurance for things that will not stay still

The name is historical and misleading. **Inland marine has almost nothing to
do with water.**

## Where the name comes from

Marine insurance is the oldest form of insurance, covering cargo at sea. As
goods moved inland by rail and road, marine underwriters followed the cargo
off the ship — insuring it over land as well. That extension became **inland**
marine, and over time it absorbed a much wider category: **property that
moves, property that is held by somebody other than its owner, and property
that a standard fire policy cannot value properly.**

**Ocean marine** remains separate, covering hull, cargo, freight and
protection and indemnity on the water.

## What qualifies

The distinguishing feature of an inland marine risk is one of:

- **The property moves** — goods in transit, a contractor's tools, a
  salesman's samples.
- **The property is portable and high value** — jewellery, cameras, musical
  instruments, fine art.
- **The property is instrumental to transport or communication** — bridges,
  tunnels, pipelines, radio towers. These do not move at all, and are insured
  here because they were historically classed as "instrumentalities of
  transportation."
- **The property is in somebody else's care** — a bailee holding customers'
  goods.

## Why anybody buys it

Four advantages over a standard property form:

- **Coverage is usually open peril** rather than named peril.
- **Coverage follows the property anywhere**, rather than attaching to
  described premises.
- **Valuation can be agreed in advance**, which matters enormously for a
  painting or an antique whose actual cash value would be argued about for
  months.
- **There is normally no coinsurance clause** on scheduled items.

**"Floater"** is the common name, because the coverage floats with the
property.

## Personal inland marine

### The personal articles floater

**Schedules high-value personal items individually**, each with a stated
value. The standard categories:

- jewellery
- furs
- cameras and photographic equipment
- musical instruments
- silverware
- golfer's equipment
- fine arts
- stamp and coin collections

Written as a **scheduled personal property** endorsement to a homeowners
policy, or as a stand-alone floater.

Why it is bought: the homeowners policy has **special limits** on exactly
these categories, most of them applying **to theft**. Scheduling removes the
sub-limit, broadens the perils to open peril, usually **removes the
deductible**, and pins the value in advance.

Two details that get tested:

- **Fine arts are normally written on a valued basis**, and typically carry a
  **breakage exclusion** unless it is bought back.
- **Newly acquired property** of a scheduled class is usually covered
  automatically for a limited period — commonly 30 days — provided the
  insurer is notified and premium paid.

### The personal property floater

Covers **all** the insured's personal property on an open peril, worldwide
basis, rather than a schedule of named items. Less common, and expensive.

## Commercial inland marine

### Nationwide marine definition

Regulators publish a **nationwide marine definition** setting out what may be
written as inland marine. It exists to stop insurers writing ordinary fire
business on inland marine forms to escape rate regulation. **Controlled**
lines are filed classes; **uncontrolled** lines may be written on
individually negotiated terms.

### The common commercial floaters

**Contractor's equipment floater** — mobile tools, machinery and equipment,
on site and in transit.

**Installation floater** — materials and equipment from the time they leave
the supplier until installed and accepted. The contractor's counterpart to
builders risk.

**Motor truck cargo** — the carrier's liability for goods it is hauling.

**Transportation / trip transit** — goods in transit generally, or one
specific shipment.

**Bailee's customers** — a dry cleaner, a repair shop, a warehouse. **Covers
the customers' property in the insured's care, and typically pays whether or
not the bailee was negligent**, because arguing about fault with a customer
whose suit you burned is bad business.

**Accounts receivable** — the sums the insured cannot collect because the
records were destroyed, plus the cost of reconstructing them and the extra
collection expense.

**Valuable papers and records** — the cost of reconstructing documents,
manuscripts and records. It pays for **reconstruction**, not for the
information's abstract worth.

**Electronic data processing** — computer hardware, software and data, on an
open peril basis, typically including **mechanical breakdown and electrical
disturbance**, which standard property forms exclude.

**Signs, jewellers block, furriers block, physicians and surgeons
equipment**, and **theatrical property** are further named classes.

**Instrumentalities of transportation and communication** — bridges, tunnels,
pipelines, power transmission lines, radio and television towers.

### Bailee terminology

- A **bailee** holds another's property. A **bailor** owns it.
- A **bailee's customers form** covers the customers' goods regardless of
  fault.
- **Legal liability** forms cover only what the bailee is legally responsible
  for — cheaper, and much less useful when the customer is angry.

## How this is examined

**"Which of these is an inland marine risk?"** — look for movement,
portability with high value, bailment, or an instrumentality of
transportation.

**Why schedule jewellery?** — to remove the homeowners special limit, broaden
to open peril, agree the value and drop the deductible.

**Bailee's customers pays regardless of negligence.**

**Accounts receivable and valuable papers pay for reconstruction**, not for
the debt or the information as an asset.

**A bridge is inland marine**, which feels wrong until you know the history.

## Check yourself

1. A photographer owns $30,000 of camera equipment used at client sites. What
   form, and why not the homeowners policy?
2. A dry cleaner's premises burn, destroying customers' garments. The cleaner
   was not negligent. Which form pays the customers?
3. Why does a floater usually have no coinsurance clause?
4. A contractor's excavator is damaged while being towed between sites. Which
   floater?
5. A fire destroys a firm's ledgers and it cannot collect $200,000 of debts.
   Which coverage, and what does it pay?

## Answers

1. A **personal articles floater** or a commercial camera floater. The
   homeowners policy limits cameras, covers them on a named peril basis away
   from home, and would settle on actual cash value.
2. A **bailee's customers form**, which pays regardless of the bailee's
   negligence.
3. Because scheduled items carry **agreed or stated values** — the insurer has
   already accepted the value, so there is nothing for a coinsurance clause to
   police.
4. A **contractor's equipment floater**.
5. **Accounts receivable** coverage — the uncollectible sums, the cost of
   reconstructing the records, and the extra collection expense.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'fb29d783-0b17-5cac-abd6-ab8e2df510b8', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
