-- Texas Exam Prep — content seed, chunk 10 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'The National Flood Insurance Program',
       'the-national-flood-insurance-program', 'Why flood is excluded everywhere else, and how the federal programme fills the gap.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', c.id, $lesson$# The peril the private market would not write

Flood is excluded from homeowners, dwelling and commercial property forms
alike. The exclusion is not arbitrary, and understanding why explains
everything else about the programme.

## Why flood is uninsurable privately

Flood fails the tests of an insurable risk from Module 1:

- **The losses are not independent.** A flood does not damage one house; it
  damages every house on the flood plain at once. The law of large numbers
  needs many unrelated exposures, and a flood plain is one exposure with many
  addresses.
- **Adverse selection is extreme.** Only people who expect to flood buy flood
  insurance, so the pool consists almost entirely of bad risks.
- **The loss is close to predictable** for the highest-risk properties — not
  a risk so much as a schedule.

So in **1968 Congress created the National Flood Insurance Program**,
administered by **FEMA**. The federal government takes the risk the private
market would not.

## How a community participates

**The NFIP is a bargain between the federal government and the community, not
just with the individual.**

A community must **adopt and enforce flood plain management ordinances** —
building elevation requirements, construction standards, development
restrictions — to reduce future flood losses. In exchange, **federally backed
flood insurance becomes available to property owners in that community**.

**No participating community, no NFIP policy.** An owner in a non-participating
community must find private coverage or go without.

Two phases:

- **The emergency programme** — an interim phase with **limited amounts** of
  coverage available while flood mapping is completed.
- **The regular programme** — full limits, once the community has a flood
  insurance rate map and has adopted the required ordinances.

## The waiting period

**There is normally a 30-day waiting period** between application and the
policy taking effect. It is the programme's defence against somebody buying
cover as the river rises.

The exceptions are worth knowing:

- **No waiting period where flood insurance is required by a lender** in
  connection with making, increasing, extending or renewing a loan.
- **A one-day wait** where coverage is bought following a change in the flood
  map.
- A shortened wait for property **affected by wildfire on federal land**.

## What a flood is

The programme's definition is specific, and questions are built on it. A
flood is a **general and temporary condition of partial or complete
inundation of two or more acres of normally dry land, or of two or more
properties**, from:

- overflow of inland or tidal waters,
- unusual and rapid accumulation or runoff of surface water,
- mudflow, or
- collapse of land along a body of water from erosion or an unusually severe
  storm.

Two consequences:

- **Water entering one building alone is generally not a flood** — a burst
  pipe, a backed-up sewer, a leaking roof. Two acres or two properties is the
  threshold.
- **Mudflow counts; landslide generally does not.** Mudflow is liquid mud
  flowing; a landslide is earth movement, excluded.

## What is covered

Two separate coverages, bought separately:

**Building property** — the structure and its foundation, electrical and
plumbing, furnaces and water heaters, built-in appliances, permanently
installed carpet, and detached garages (within a portion of the limit).

**Personal property (contents)** — furniture, clothing, portable appliances,
washers and dryers, and a limited amount for valuables.

**Contents are not automatically included.** An owner who buys building
coverage only has no coverage for anything inside. That is a favourite
question.

### Limits

Under the **regular programme**, the maximum amounts available are:

| | Building | Contents |
| --- | --- | --- |
| **Residential** | **$250,000** | **$100,000** |
| **Non-residential / commercial** | **$500,000** | **$500,000** |

These are **programme maximums**, not appraised values. Anybody needing more
buys **excess flood** from the private market.

### Loss settlement

- **Replacement cost** is available on a **single-family dwelling that is the
  insured's principal residence**, insured to at least 80% of replacement
  cost.
- **Everything else is actual cash value** — contents always, and buildings
  that are secondary homes, rentals or commercial.

## What is not covered

- **Contents in a basement**, beyond a very short list of building items.
  Finished basements are largely uninsurable under the programme.
- **Additional living expense and loss of use** — the NFIP pays for the
  property, not for the disruption.
- **Currency, precious metals and valuable papers.**
- **Property outside the building** — landscaping, decks, patios, fences,
  septic systems, swimming pools.
- **Vehicles**, which belong on an auto policy's other-than-collision
  coverage.
- **Business interruption.**

## Zones, maps and requirements

FEMA publishes a **Flood Insurance Rate Map** for each participating
community, dividing it into **flood zones**.

- **Zones A and V** are **Special Flood Hazard Areas** — the 100-year flood
  plain, meaning a 1% annual chance of flooding. **V zones are coastal**, with
  additional wave action.
- **Zones B, C and X** are moderate or minimal risk, where coverage is
  cheaper and often bought voluntarily.

**Mandatory purchase:** a building in a Special Flood Hazard Area with a
**federally backed or federally regulated mortgage** must carry flood
insurance. This is the single largest driver of NFIP sales.

**Write Your Own.** Private insurers issue and service NFIP policies under
their own names, with the **federal government carrying the risk**. The
producer sells what looks like a private policy; the terms, limits and rates
are the programme's.

## How this is examined

**The 30-day waiting period** and its exceptions.

**The two-acre / two-property definition** of a flood.

**Contents must be bought separately.**

**The $250,000 / $100,000 residential limits.**

**Replacement cost applies only to a principal residence**; everything else is
ACV.

**Community participation is a precondition.**

**Basements, landscaping and living expense are not covered.**

## Check yourself

1. A homeowner buys an NFIP policy on 1 May. The river floods on 20 May. Is
   there coverage?
2. A burst water main floods only the insured's basement. Is this a "flood"
   under the programme?
3. An owner buys $250,000 of building coverage. A flood destroys $60,000 of
   furniture. What is paid?
4. A rental house owned as an investment suffers flood damage to a 15-year-old
   roof. Replacement cost or actual cash value?
5. A community declines to adopt flood plain management ordinances. Can its
   residents buy NFIP coverage?
6. What is the maximum building coverage on a commercial property?

## Answers

1. **No** — the 30-day waiting period has not run, and no exception applies.
2. **No.** A flood requires inundation of **two or more acres or two or more
   properties**; water in one building from a burst main is not one.
3. **Nothing.** Contents coverage must be purchased separately.
4. **Actual cash value.** Replacement cost is limited to a single-family
   dwelling that is the insured's **principal residence**.
5. **No.** Community participation is a precondition.
6. **$500,000**, with a further $500,000 available for contents.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6d2171b2-6a44-5f41-b8c4-52bd93262d4a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', '4d5887f6-82b0-535b-bfd5-541974214ccd', c.id, 'Other Property Policies',
       'other-property-policies', 'Earthquake, mobile homes, watercraft, farmowners and windstorm — five smaller forms the blueprint names explicitly.', 6,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', c.id, $lesson$# Five risks the standard forms send elsewhere

The blueprint lists these by name, so they are examined by name. Each exists
because a standard homeowners or commercial form either excludes the peril or
cannot handle the property.

## Earthquake

**Earth movement is excluded from every standard property form**, for the same
reason as flood: the losses are correlated. One earthquake damages every
building in a region simultaneously.

Coverage is bought back by **endorsement** to a homeowners or commercial
policy, or written as a **separate policy**.

What to know:

- **The exclusion is broader than "earthquake".** Earth movement includes
  **landslide, mudslide, subsidence, sinkhole collapse and earth sinking,
  rising or shifting**. Buying earthquake coverage does not necessarily buy
  all of these back.
- **Fire following an earthquake is covered by the standard policy.** The
  earth movement exclusion is generally written so that **ensuing fire** is
  not excluded. This is a long-standing rule and a reliable exam point.
- **The deductible is a percentage**, not a flat sum — commonly **2% to 20%
  of the coverage limit**, and it is applied to the limit rather than to the
  loss. On a $400,000 dwelling, a 10% deductible is $40,000 before anything is
  paid.
- **Multiple shocks within a stated period** — commonly 72 hours — count as
  **one occurrence**, so one deductible applies rather than several.

## Mobile homes

A mobile or manufactured home cannot be written on a standard homeowners
policy: it is built to different standards, depreciates like a vehicle rather
than appreciating like a house, and can be moved.

**A mobile homeowners policy is a package**, structured like a homeowners
policy with property and liability sections, but with changes:

- **Loss settlement is normally actual cash value**, reflecting that the unit
  depreciates. Replacement cost may be available by endorsement on newer
  units.
- **Transportation and permission to move** must be arranged. Coverage while
  the home is being moved is typically added by endorsement, often with a
  limited amount and a requirement that the insurer be notified beforehand.
- **Eligibility** usually requires the unit to be of a minimum size, designed
  for year-round living, and at a fixed location.
- **Skirting, awnings, carports and attached structures** may need to be
  listed to be covered.

## Watercraft

Homeowners policies cover **small, low-powered boats** and very little else.
The typical arrangement covers a boat only up to a modest length and
horsepower, on a narrow peril basis, with liability excluded for larger or
faster craft.

Anything beyond that needs a **boatowners or yacht policy**:

- **A boatowners policy** is a package for smaller pleasure craft, covering
  the hull, motor, trailer and equipment, plus liability and medical payments.
- **A yacht policy** covers larger vessels and is structured on ocean marine
  principles: **hull** coverage on the vessel, **protection and indemnity**
  for liability, plus medical payments and coverage for the boat's trailer
  and equipment.

Points that are examined:

- **Navigational limits.** The policy specifies the waters in which the
  vessel is covered, and often a **lay-up period** during which it must be out
  of the water — coverage is reduced or restricted outside those terms.
- **Protection and indemnity is the marine world's liability coverage**, and
  is broader than a general liability form in respect of crew and other
  maritime exposures.
- **Ocean marine perils** — the traditional list includes perils of the sea,
  fire, jettison, piracy and barratry (wrongful acts by the master or crew).

## Farmowners

**A farmowners policy is a package covering both the farm residence and the
farming operation** — the agricultural equivalent of a homeowners policy, and
the reason farms are ineligible for a homeowners policy.

It combines, in one contract:

- **The dwelling and its contents**, on much the same basis as a homeowners
  policy.
- **Farm structures** — barns, silos, outbuildings, fences, corrals.
- **Farm personal property** — machinery, equipment, tools, harvested crops,
  feed, seed, fertiliser, and **livestock**.
- **Farm liability**, which is broader than personal liability because the
  farm is a business. It covers the farming operation, and typically **farm
  employees**, whose injuries would otherwise fall outside a personal policy.

Specific features:

- **Livestock coverage** is usually written on a **named peril** basis and
  frequently includes perils peculiar to the exposure — **electrocution,
  attack by dogs or wild animals, accidental shooting, drowning** and **loading
  and unloading**.
- **Scheduled versus blanket** treatment of farm personal property works as it
  does in commercial property: blanket for a shifting inventory of feed and
  grain, scheduled for named machines.
- **Crop insurance is separate**, largely federal, and is not part of a
  farmowners policy.
- **Mobile agricultural equipment in transit** may need inland marine.

## Windstorm

Wind is a **covered peril** on standard property forms in most of the country.
In coastal areas it is frequently **excluded or heavily deductible**, because
the exposure is concentrated: one hurricane damages an entire coastline.

Where the private market withdraws, coverage comes from a **residual market**
— a state-created insurer of last resort. Two mechanisms appear:

- **A windstorm pool or association**, writing wind and hail coverage in a
  designated coastal area.
- **A FAIR Plan** — Fair Access to Insurance Requirements — writing basic
  property coverage for those unable to obtain it in the voluntary market,
  usually because of location or property condition rather than the owner's
  conduct.

Both are funded by **compulsory membership of the insurers writing in the
state**, which is why they are described as the market insuring itself.

Recurring features:

- **A separate, percentage windstorm or hurricane deductible**, applied to the
  coverage limit.
- **A named-storm trigger**, where the percentage deductible applies only to
  storms the weather service has named.
- **Insurance-to-value and building-code requirements** as conditions of
  eligibility.
- **A waiting period** and a suspension of new business once a storm is
  approaching.

> **Texas is one of the states where this matters most.** The Texas Windstorm
> Insurance Association and the Texas FAIR Plan Association are creatures of
> the Texas Insurance Code, with their own eligibility rules, limits,
> deductibles and claim deadlines. Those specifics belong to the Texas
> statutes module and are examined there. What belongs here is the general
> shape: wind excluded on the coast, a residual market filling the gap, funded
> by compulsory membership.

## How this is examined

**Fire following an earthquake is covered** by the standard policy.

**Earthquake deductibles are a percentage of the limit**, and multiple shocks
in 72 hours are one occurrence.

**Mobile homes settle at actual cash value.**

**A farm is ineligible for a homeowners policy**, and why.

**Livestock perils** — electrocution, attack by animals, accidental shooting,
drowning.

**Residual markets** exist because of correlated catastrophe exposure, and are
funded by the insurers writing in the state.

## Check yourself

1. An earthquake cracks a gas line and the resulting fire destroys the house.
   What is covered under a standard homeowners policy without an earthquake
   endorsement?
2. A $500,000 dwelling carries earthquake coverage with a 10% deductible. A
   quake causes $70,000 of damage. What is paid?
3. Why is a mobile home not written on a homeowners policy?
4. A farmer keeps a herd of cattle, farms 400 acres and lives in a house on
   the property. What policy?
5. Cattle are killed by lightning. Covered under a farmowners policy?
6. Why is windstorm excluded on the coast when it is covered inland?

## Answers

1. **The fire damage.** Ensuing fire is not excluded by the earth movement
   exclusion. The shake damage itself is not covered.
2. **$20,000.** The deductible is 10% of the **limit** — $50,000 — not of the
   loss.
3. It is built to different standards, depreciates rather than appreciates,
   and can be moved. A mobile homeowners policy settles on **actual cash
   value** and addresses transportation.
4. A **farmowners** policy — a package covering the residence and the farming
   operation. A farm is ineligible for homeowners.
5. **Yes.** Lightning is a standard peril and electrocution is among the
   perils livestock coverage typically names.
6. Because the exposure is **correlated** — a single hurricane damages an
   entire coastline at once, which defeats the law of large numbers. A
   residual market fills the gap.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'f2a692e9-7a38-5c5c-938c-371af3cfcd0f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
