-- Texas Exam Prep — content seed, chunk 11 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Commercial General Liability',
       'commercial-general-liability', 'Three coverages, four exposures, six limits — the form most commercial liability questions are built on.', 1,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', c.id, $lesson$# The business's liability policy

The CGL covers a business's liability to **third parties** — customers,
visitors, passers-by, the users of its products. Not its employees (workers'
compensation), not its vehicles (commercial auto), not its professional
advice (professional liability).

## The four exposures

Traditionally grouped as **premises and operations**, **products and completed
operations**, **contractual**, and **personal and advertising injury**. The
blueprint names the first two explicitly.

**Premises** — somebody is injured on the insured's property. A customer
slips in a supermarket aisle.

**Operations** — somebody is injured by the insured's work **while it is in
progress**, whether at the insured's premises or elsewhere. A plumber floods
a client's kitchen mid-job.

**Products** — injury or damage caused by a product the insured made or sold,
**after it has left the insured's possession**.

**Completed operations** — injury or damage arising from the insured's work
**after it is finished** and handed over. A deck collapses two years after the
builder left.

**Products and completed operations are grouped together** because they share
a characteristic: the loss happens when the insured is no longer there, often
long afterwards. They also share **their own separate aggregate limit**.

The dividing line is tested directly: **work in progress is operations;
work handed over is completed operations.**

## The three coverages

### Coverage A — Bodily Injury and Property Damage Liability

The core. Pays sums the insured becomes **legally obligated to pay as
damages** because of bodily injury or property damage caused by an
**occurrence** in the coverage territory.

**An occurrence is an accident, including continuous or repeated exposure to
substantially the same general harmful conditions.** The word does the work
of excluding the deliberate: intentional injury is not an occurrence.

**Bodily injury** means bodily injury, sickness or disease, including death.
**Property damage** means physical injury to tangible property, including loss
of use, **and** loss of use of tangible property that is not physically
injured.

#### Occurrence versus claims-made

**An occurrence form** responds to injury or damage **taking place during the
policy period**, whenever the claim arrives.

**A claims-made form** responds to claims **first made during the policy
period**, and adds two mechanisms:

- **The retroactive date.** Injury or damage before it is not covered, no
  matter when claimed. A retroactive date that moves forward on renewal
  quietly destroys years of coverage — the thing to watch for.
- **Extended reporting periods.** A **basic** tail is automatic and short; a
  **supplemental** tail is bought, usually unlimited in time, and must be
  purchased within a short window after the policy ends.

Claims-made exists for long-tail exposures — where injury may not appear for
decades — because an insurer cannot price a promise whose claims will arrive
forty years later.

### Coverage B — Personal and Advertising Injury Liability

Covers injury arising from a list of **offences**, not from an accident. The
list:

- **false arrest, detention or imprisonment**
- **malicious prosecution**
- **wrongful eviction**, wrongful entry, or invasion of the right of private
  occupancy
- **slander or libel** — oral or written publication disparaging a person or
  organisation, or their goods
- **violation of a person's right of privacy**
- **use of another's advertising idea**
- **infringement of copyright, trade dress or slogan** in the insured's
  advertisement

Two exam points: **these are offences, not occurrences**, so the trigger is
the committing of the offence; and **patent and trademark infringement are
generally not covered** — the list names copyright, trade dress and slogan.

### Coverage C — Medical Payments

Pays medical expenses for bodily injury on the insured's premises or arising
from operations, **regardless of fault**, provided the expenses are incurred
within a stated period — commonly **three years** — of the accident.

It exists to settle small injuries quickly and goodwill intact, before they
become liability claims. It **does not apply to the insured, employees, or
tenants**, and it does not apply where the injured person is covered by
workers' compensation.

## Supplementary payments

Paid **in addition to the limits**: defence costs, the cost of bonds to
release attachments, **premiums** on appeal bonds and bail bonds (commonly up
to $250), reasonable expenses at the insurer's request including lost earnings
(commonly up to $250 a day), court costs, and **post-judgment interest**.

## Who is an insured

The form defines it by the insured's structure:

- **Sole proprietor** — the individual and their spouse, for the conduct of
  the business.
- **Partnership or joint venture** — the partners and their spouses.
- **Limited liability company** — members and managers.
- **Corporation** — executive officers, directors and stockholders, acting
  within their duties.
- **Employees and volunteer workers**, for acts within the scope of their
  employment — **but not for bodily injury to a fellow employee**, and not for
  professional services.
- **Real estate managers** acting for the insured.
- **Newly acquired organisations**, automatically, for a limited period —
  commonly **90 days** or until the policy ends, whichever is first.

**The first named insured** has the distinct duties met in Module 2: it
receives notices, pays premium, may cancel, and handles the **premium audit**.

**Additional insureds** are added by endorsement, for liability arising out of
the named insured's work or premises.

## The six limits

The CGL's limit structure is examined more often than anything else in the
form.

| Limit | What it caps |
| --- | --- |
| **Each occurrence** | All damages from one occurrence, under A and C combined |
| **General aggregate** | Everything paid in the policy period **except** products-completed operations |
| **Products–completed operations aggregate** | Its own separate annual cap |
| **Personal and advertising injury** | Per person or organisation, under Coverage B |
| **Damage to premises rented to you** | Fire (and in later editions, certain other) damage to premises the insured rents |
| **Medical expense** | Per person, under Coverage C |

The points that get tested:

- **Products-completed operations has its own aggregate**, separate from the
  general aggregate. Exhausting one does not exhaust the other.
- **The aggregate is annual.** Once exhausted, the policy is finished for that
  period even though months remain — and the duty to defend ends with it.
- **Damage to premises rented to you** is the exception to the property damage
  exclusion for property in the insured's care: a tenant who burns the
  landlord's building has this, and nothing else.

## Key exclusions

- **Expected or intended injury.**
- **Contractual liability** — except for an **insured contract**, a defined
  list including leases, sidetrack agreements, easements, and the part of any
  contract assuming another's tort liability. This is a broad exception that
  effectively restores most commercial hold-harmless agreements.
- **Workers' compensation and employer's liability** — employees' injuries
  belong elsewhere.
- **Pollution**, with narrow exceptions.
- **Aircraft, auto and watercraft** — but **mobile equipment is covered**.
- **Damage to your product** and **damage to your work** — the policy covers
  the harm the product does, not the cost of the defective product itself.
  This is the **business risk** principle: replacing your own bad work is a
  cost of doing business, not an insurable accident.
- **Damage to property in your care, custody or control**, except the rented
  premises limit.
- **Recall of products** — the "sistership" exclusion.
- **Liquor liability**, for those in the business of serving alcohol.
- **Professional services.**

## Mobile equipment versus auto

**Mobile equipment** — bulldozers, farm machinery, forklifts, vehicles
maintained solely on the insured's premises, and vehicles whose purpose is to
carry permanently mounted equipment like drills or cranes — is **covered by
the CGL**.

**Autos** — vehicles subject to compulsory registration and used on public
roads — are **excluded** and belong on the commercial auto policy.

The line moves in one notable case: **self-propelled vehicles carrying
permanently attached equipment are mobile equipment, unless they are subject
to registration**, in which case they become autos.

## How this is examined

**Operations versus completed operations.**

**The two aggregates**, and that exhausting one does not exhaust the other.

**"Damage to your work" and "damage to your product"** — the product that
injures somebody is covered; the product itself is not.

**Coverage B's list of offences**, especially that patent and trademark are
absent.

**Medical payments pays without fault** and not to employees.

**Insured contract** as the exception to the contractual liability exclusion.

**Mobile equipment versus auto.**

## Check yourself

1. A contractor installs a faulty water heater. It leaks two years later,
   ruining a floor. Which exposure, and is the water heater itself covered?
2. A CGL has a $1m occurrence limit, $2m general aggregate and $2m
   products-completed operations aggregate. Premises claims have exhausted the
   general aggregate in July. A products claim arrives in September. Covered?
3. A visitor trips in the insured's lobby. The insured is plainly not
   negligent, but the visitor has a $3,000 hospital bill. Anything payable?
4. An employee is injured by a colleague's negligence. Does the CGL respond?
5. A restaurant's advertisement copies a competitor's slogan. Which coverage?
6. A tenant's negligence causes a fire that damages the landlord's building.
   Is that covered, given the care, custody or control exclusion?

## Answers

1. **Completed operations** — the work was finished and handed over. The
   **floor damage is covered**; the **water heater itself is not**, under the
   damage-to-your-product and damage-to-your-work exclusions.
2. **Yes.** Products-completed operations has its **own separate aggregate**,
   untouched by the premises claims.
3. **Yes** — Coverage C, medical payments, pays regardless of fault, for
   expenses incurred within the stated period.
4. **No.** Employee injuries are excluded; workers' compensation and
   employers' liability respond.
5. **Coverage B**, personal and advertising injury — infringement of slogan in
   an advertisement.
6. **Yes, up to the "damage to premises rented to you" limit**, which is the
   express exception to that exclusion.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '28241cd6-2d64-5c0d-8297-9e242c3e931a', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Personal Auto',
       'personal-auto', 'Four parts, several definitions of "your covered auto", and the uninsured motorist coverage that catches everybody.', 2,
       'draft', 18
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', c.id, $lesson$# The most widely owned policy there is

A personal auto policy is a package of four separately purchased coverages,
each with its own limit and its own set of insureds.

## The four parts

| Part | Coverage |
| --- | --- |
| **A** | **Liability** — bodily injury and property damage to others |
| **B** | **Medical payments** |
| **C** | **Uninsured motorists** (and, where written, underinsured) |
| **D** | **Damage to your auto** — collision and other than collision |

## Part A — Liability

Pays damages the insured is legally responsible for, from an auto accident.
It includes **defence**, and **defence costs are in addition to the limit**.

### Split limits and combined single limit

**Split limits** are written as three numbers: **bodily injury per person /
bodily injury per accident / property damage per accident.** Under 100/300/50:

- **$100,000** is the most for any one injured person;
- **$300,000** is the most for all bodily injury in one accident;
- **$50,000** is the most for property damage in one accident.

A four-claimant accident with $90,000 of injury each: each claim is within the
$100,000 per-person limit, but the $360,000 total exceeds the $300,000
per-accident limit, so **$300,000** is paid.

**A combined single limit** is one figure covering bodily injury and property
damage in any proportion. A $300,000 CSL can pay $250,000 of injury and
$50,000 of damage, or any other split. It is more flexible and generally more
expensive.

### Who is an insured under Part A

- **The named insured and any family member**, for any auto — including cars
  they do not own.
- **Any person using "your covered auto"** with permission. This is
  **permissive use**, and it is why lending the car lends the insurance.
- **Any person or organisation legally responsible** for an insured's use of a
  covered auto — a passenger's employer, for example.

### Key exclusions

- **Intentional injury.**
- **Property owned by or in the insured's care, custody or control** — you
  cannot use your liability coverage to fix your own garage.
- **Vehicles with fewer than four wheels**, and vehicles used as a **public or
  livery conveyance** — the ride-hailing exclusion, now commonly bought back
  by endorsement.
- **Employees covered by workers' compensation.**
- **Using a vehicle without a reasonable belief of being entitled to.**
- **Vehicles available for regular use** that are not covered autos — the
  reason a company car you drive daily is not covered by your personal policy.
- **Business use of vehicles**, other than a private passenger auto, pickup or
  van.

## Part B — Medical payments

Pays **reasonable and necessary medical and funeral expenses**, for bodily
injury caused by an accident, **regardless of fault**, incurred within a
stated period — commonly **three years** — of the accident.

Who is covered:

- **The named insured and family members**, while occupying **any** auto, or
  as pedestrians struck by a motor vehicle.
- **Any other person occupying "your covered auto."**

It is a small limit, often $5,000 or $10,000 per person, and it is primary:
it pays quickly without waiting for a liability determination.

## Part C — Uninsured and underinsured motorists

The coverage the exam loves, because its logic runs backwards from the rest of
the policy.

**UM pays the insured what the *other* driver's liability policy would have
paid, had they had one.** The insured must be **legally entitled to recover**
— the other driver must be at fault. This is the crucial point: **UM is not
no-fault coverage.** If the insured caused the accident, UM pays nothing.

**Uninsured motorist** applies where the at-fault driver:

- has **no insurance**;
- is a **hit-and-run** driver who cannot be identified; or
- has insurance from an insurer that is **insolvent** or **denies coverage**.

**Underinsured motorist** applies where the at-fault driver **has insurance,
but not enough** to cover the loss. It pays the difference between the other
driver's limit and the insured's UIM limit.

Two further points:

- **UM bodily injury is standard; UM property damage is not** available in
  every state, and where it is, often carries a deductible.
- **Stacking** — combining the UM limits of several vehicles or policies — is
  permitted in some states and prohibited in others.

> Texas's rules on uninsured and underinsured motorists, and on personal
> injury protection, sit in Chapter 1952 of the Texas Insurance Code. The
> general mechanism is here; the Texas requirements, including which coverages
> must be offered and how they may be rejected, are examined in the Texas
> statutes module.

**Personal injury protection** is a broader first-party coverage found in
some states, paying medical expenses, lost wages and replacement services
regardless of fault — and, unlike UM, without requiring anybody to be at
fault.

## Part D — Damage to your auto

Physical damage to the vehicle itself, written with a deductible.

**Collision** — impact with another vehicle or object, or the vehicle
overturning. **Fault is irrelevant.** Hitting a wall is collision; so is
being hit.

**Other than collision** (comprehensive) — everything else: **fire, theft,
vandalism, glass breakage, falling objects, explosion, earthquake, windstorm,
hail, water, flood, riot, contact with a bird or animal, and missiles**.

The classic distinction: **hitting a deer is other than collision; swerving to
avoid a deer and hitting a tree is collision.**

**Specified (named) perils** is a cheaper third option, covering a named list
— fire, lightning, theft, windstorm, hail, explosion, earthquake, flood, riot,
and the like — rather than all non-collision causes.

Also in Part D:

- **Transportation expenses** — a modest daily amount for a rental car
  following a covered loss, subject to a maximum and, for theft, a waiting
  period.
- **Loss to non-owned autos** the insured is driving is covered to the same
  extent.
- **Excluded**: wear and tear, mechanical breakdown, road damage to tyres,
  freezing, electronic equipment not permanently installed, and custom
  furnishings in a pickup or van unless declared.

**Loss settlement is actual cash value** or the cost of repair, whichever is
less. **A total loss pays ACV, which is why a new car can be worth
substantially less than its loan** — the gap that GAP coverage fills.

## Types of auto

The blueprint names these explicitly, and they matter more in commercial auto:

- **Owned** — titled to the insured and listed on the policy.
- **Non-owned** — not owned by, hired by or borrowed by the insured, but used
  in the insured's business, typically an employee's own car.
- **Hired** — leased, rented or borrowed.
- **Temporary substitute** — used while a covered auto is out of service for
  breakdown, repair, servicing, loss or destruction. **Covered
  automatically.**
- **Newly acquired auto** — covered automatically, usually for **14 or 30
  days** depending on whether it is an addition or a replacement and on the
  coverage; the insured must notify the insurer within that window. An
  **additional** vehicle generally gets broader automatic coverage than a
  **replacement**, which inherits only the coverage the replaced vehicle had.
- **Trailers** owned by the insured are usually covered for liability.

## Duties after an accident

Beyond the general duties: **notify the police in a hit-and-run** (UM
requires it, usually within 24 hours), **submit to physical examination** and
to **examination under oath**, and **allow inspection of the vehicle before
repair**.

## How this is examined

**Split limit arithmetic** with several claimants.

**Collision versus other than collision** — the deer.

**UM requires the other driver to be at fault**, and covers hit-and-run and
insolvent insurers.

**UIM pays the difference**, not the whole loss again.

**Permissive use** — the borrowed car.

**Newly acquired auto** notification periods, and addition versus
replacement.

**Public or livery conveyance** exclusion for ride-hailing.

## Check yourself

1. Under 250/500/100, three people are injured with claims of $200,000,
   $200,000 and $150,000. What is paid for bodily injury?
2. The insured hits a deer. Collision or other than collision?
3. The insured is at fault in an accident and is badly injured. The other
   driver is uninsured. Does UM pay the insured's injuries?
4. An at-fault driver carries $30,000 of bodily injury coverage. The insured's
   damages are $90,000 and their UIM limit is $100,000. Roughly what does UIM
   pay?
5. A friend borrows the insured's car and causes an accident. Whose policy is
   primary?
6. The insured's car is totalled. It was bought last year for $38,000, is now
   worth $26,000, and the loan balance is $31,000. What does Part D pay?

## Answers

1. Each claim is within the $250,000 per-person limit, but they total
   $550,000 against the $500,000 per-accident limit. **$500,000** is paid.
2. **Other than collision.** Contact with an animal is a comprehensive loss.
3. **No.** UM requires the insured to be **legally entitled to recover** from
   the other driver — the other driver must be at fault.
4. **$60,000** — the difference between the at-fault driver's $30,000 and the
   insured's $90,000 of damages, within the $100,000 UIM limit.
5. **The car owner's.** Liability follows the car; the permissive user is an
   insured.
6. **$26,000** less the deductible — actual cash value. The **$5,000 gap** to
   the loan is the insured's, unless GAP coverage was bought.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '05b35e14-99ac-5dac-89c9-c53c92c33fc5', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
