-- Texas Exam Prep — content seed, chunk 12 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Business Auto',
       'business-auto', 'The numbered symbols that decide what is covered, plus garagekeepers and drive other car.', 3,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', c.id, $lesson$# Same risks, different machinery

The business auto policy covers the same exposures as a personal auto policy —
liability, medical payments, uninsured motorists, physical damage — for a
business. What is different is **how it describes which vehicles are
covered**, and that mechanism is what gets examined.

## Covered auto designation symbols

Rather than listing vehicles, the declarations put a **number next to each
coverage**. The number says which class of autos that coverage applies to.

| Symbol | Meaning |
| --- | --- |
| **1** | **Any auto** — the broadest available |
| **2** | Owned autos only |
| **3** | Owned **private passenger** autos only |
| **4** | Owned autos **other than** private passenger |
| **5** | Owned autos subject to **no-fault** laws |
| **6** | Owned autos subject to **compulsory uninsured motorist** law |
| **7** | **Specifically described** autos |
| **8** | **Hired** autos only |
| **9** | **Non-owned** autos only |
| **19** | Mobile equipment subject to compulsory or financial responsibility law |

The consequences:

- **Symbol 1 is available only for liability.** It is the broadest, covering
  owned, hired and non-owned autos alike, including vehicles acquired after
  the policy began.
- **Physical damage cannot use symbol 1**, because an insurer will not insure
  the hull of a vehicle it has never seen. Physical damage uses **2, 3, 4, 7**
  or a combination.
- **A business that owns no vehicles but whose staff drive their own** needs
  **symbols 8 and 9** — hired and non-owned — with no owned-auto coverage at
  all.
- **Symbol 7 covers only what is listed**, so a newly purchased vehicle must
  be reported. Symbols 2, 3 and 4 pick up newly acquired autos automatically.

A question describing a fact pattern and asking "which symbol?" is really
asking whether the vehicle is owned, hired or non-owned.

## Hired and non-owned

**Hired autos** are leased, rented, hired or borrowed — but **not** vehicles
borrowed from employees. Coverage is usually **excess** over the owner's own
insurance, and the premium is based on **cost of hire**.

**Non-owned autos** are vehicles used in the business but not owned, hired or
borrowed by it — chiefly **employees' own cars** used on company errands. The
business's liability arises because the employee was acting in the scope of
employment. Coverage is **excess** over the employee's own policy, which
remains primary.

**Hired and non-owned liability is the coverage a business with no vehicles
still needs**, and the one it most often forgets to buy.

## Physical damage

The same three options as personal auto — **collision**, **other than
collision** (comprehensive), and **specified causes of loss** — plus:

- **Towing and labour** at the place of disablement.
- **Loss of use** and **rental reimbursement**, by endorsement.
- **Transportation expenses** following theft.

## Auto dealers and garagekeepers

A vehicle dealer or repair shop has an exposure nobody else does: **it holds
other people's cars.** Two coverages address it.

**Garage liability** (now within the auto dealers coverage form) covers the
dealer's liability from **garage operations** — the premises, the operations,
and the autos.

**Garagekeepers coverage** covers **damage to customers' autos in the
insured's care, custody or control**. This is the exposure the CGL and the
business auto policy both exclude, and it is examined regularly.

It is written on one of three bases:

- **Legal liability** — pays only when the insured is **legally liable** for
  the damage. Cheapest.
- **Direct primary** — pays for damage to the customer's auto **regardless of
  fault**, and pays first, before the customer's own insurance.
- **Direct excess** — pays regardless of fault, but **only after the
  customer's own insurance** is exhausted.

The distinction to hold: **legal liability requires negligence; the two direct
forms do not. Primary pays first; excess pays after the customer's policy.**

A dealer also needs **dealer's physical damage** ("false pretense" and similar
coverages) for its own inventory.

## Drive other car

**Drive Other Car** is an endorsement for an individual — typically an
executive with a company car and **no personal auto policy of their own.**

The problem it solves: the business auto policy covers them while driving the
company car, but not while driving a rented car on holiday or borrowing a
friend's vehicle. Their personal exposure is uninsured because they own no
personal policy.

**DOC extends the business auto policy's liability, medical payments,
uninsured motorists and physical damage to the named individual and their
spouse while using autos they do not own** — other than the company car
itself, which is already covered.

It is named-individual coverage, added by endorsement for each person.

## Individual named insured

A related endorsement broadens a business auto policy for an **individual**
named insured — a sole proprietor whose business and personal use are the same
vehicles — to give something close to personal auto coverage for family
members and non-owned vehicles.

## Mobile equipment

The same line as in the CGL. **Mobile equipment** — bulldozers, farm
machinery, forklifts, vehicles maintained solely on premises, vehicles whose
purpose is to carry permanently mounted equipment — is covered by the **CGL**,
not the auto policy.

**But:** where such a vehicle is **subject to compulsory or financial
responsibility law** because it travels on public roads, it becomes an
**auto** for insurance purposes, which is what **symbol 19** addresses.

## Trucking and motor carriers

Businesses hauling goods for others carry additional requirements:

- **Federal filings** — endorsements guaranteeing public liability limits set
  by federal regulation for interstate carriers.
- **Motor truck cargo** — the carrier's liability for goods being hauled,
  written as inland marine.
- **Trailer interchange** — physical damage to trailers of others in the
  insured's possession under an interchange agreement.
- **Non-trucking liability** ("bobtail") — the owner-operator's liability
  while the truck is being used **outside** the motor carrier's business.

## How this is examined

**Symbol 1 is liability only**; physical damage cannot use it.

**A business with no owned vehicles** needs hired and non-owned — symbols 8
and 9.

**Garagekeepers: legal liability versus direct primary versus direct excess.**

**Drive Other Car is for an individual with no personal auto policy.**

**Non-owned coverage is excess** over the employee's own policy.

**Mobile equipment belongs on the CGL** unless registration makes it an auto.

## Check yourself

1. An accounting firm owns no vehicles, but its staff drive their own cars to
   clients. Which symbols does it need?
2. A repair shop damages a customer's car while test-driving it. Which
   coverage, and which basis would pay even if the shop were not negligent?
3. Why can physical damage not be written under symbol 1?
4. An executive drives a company car and owns no personal policy. She rents a
   car on holiday and causes an accident. What was needed?
5. A forklift is used only inside the insured's warehouse. Which policy covers
   liability arising from it?
6. An employee causes an accident driving their own car on a company errand.
   Which policy is primary?

## Answers

1. **8 and 9** — hired and non-owned autos.
2. **Garagekeepers**, on a **direct primary** or **direct excess** basis.
   Legal liability alone would require negligence.
3. Because symbol 1 means **any auto**, including vehicles the insurer has
   never seen or rated. An insurer will not cover the hull of an unknown
   vehicle.
4. A **Drive Other Car** endorsement on the business auto policy.
5. **The CGL.** It is mobile equipment, not an auto.
6. **The employee's own policy.** The business's non-owned coverage is
   **excess** over it.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '540f7c2a-82b7-5fd5-bb6b-01c592cdc2dc', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Workers'' Compensation and Employers'' Liability',
       'workers-compensation-and-employers-liability', 'The no-fault bargain, the three parts of the policy, and how the premium is actually calculated.', 4,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', c.id, $lesson$# A bargain struck a century ago

Before workers' compensation, an injured employee had to **sue the employer
and prove negligence** — and faced three defences that usually won:

- **Contributory negligence** — the worker's own carelessness contributed.
- **Assumption of risk** — the worker knew the job was dangerous and took it
  anyway.
- **The fellow servant rule** — the injury was caused by a co-worker, not the
  employer.

Injured workers rarely recovered, and when they did, employers faced ruinous
awards.

**Workers' compensation replaced that with a trade.** The employee gives up
the right to sue and the chance of a large damages award. The employer gives
up the three defences and accepts liability **without regard to fault**. The
employee gets certain, prompt, limited benefits; the employer gets
predictability.

## Exclusive remedy

**The benefits provided by the workers' compensation statute are the
employee's exclusive remedy against the employer for a work-related injury.**

This single sentence is the most examined fact in the topic. It is why the
CGL excludes employee injuries, why the employer cannot be sued for pain and
suffering, and why the arrangement works at all.

The exceptions where an employee may sue outside the system are narrow:
**intentional injury by the employer**, and in some states injury caused by
**gross negligence** or by the employer's failure to carry required coverage.

**Third parties are not protected.** An employee injured by a defective
machine still sues the manufacturer, and the compensation insurer subrogates
against it.

> **Texas is the notable exception in the United States.** It is the only
> state that does not compel most private employers to carry workers'
> compensation. An employer that opts out — a "non-subscriber" — **loses the
> three common law defences** and can be sued directly. That is Texas-specific
> and examined in the Texas statutes module; the blueprint explicitly notes
> that this general section does not deal with state law specifics.

## Who is covered

**An employee** — anybody the employer directs and controls as to the manner
of the work. The label on the relationship matters less than the control test.

**An independent contractor** is not an employee: they control how the work is
done, supply their own tools, and serve multiple clients. An employer using
uninsured subcontractors may nevertheless be treated as their statutory
employer.

Commonly excluded or optional, varying by state: **domestic servants, casual
labour, farm workers, sole proprietors, partners, and corporate officers**,
who may often elect in or out.

Separate **federal systems** cover workers the state acts do not:

- **The Federal Employers' Liability Act (FELA)** — railroad workers. Note
  that FELA is **not** a no-fault system; it preserves the right to sue but
  removes the common law defences.
- **The Longshore and Harbor Workers' Compensation Act** — maritime workers
  on navigable waters other than seamen.
- **The Jones Act** — seamen.
- **The Federal Employees' Compensation Act** — civilian federal employees.

## Compensability: arising out of and in the course of employment

An injury is compensable if it **arises out of** the employment (the work
caused it) **and occurs in the course of** the employment (during work, at the
workplace, doing work).

The recurring boundaries:

- **The commute is generally not covered** — the "going and coming" rule. But
  travel **on the employer's business** is.
- **A lunch break off premises** is usually outside; on premises, usually
  inside.
- **Horseplay** generally takes the injured instigator outside the system; an
  innocent bystander usually stays inside.
- **Occupational disease** is covered where it arises from conditions
  characteristic of the work — repetitive strain, hearing loss, exposure
  illnesses — even though there is no accident and the onset is gradual.

## The benefits

Set by statute, not by the policy. Four categories:

**Medical** — usually **unlimited**, with no deductible and no dollar cap.
This surprises candidates and is worth remembering.

**Disability income**, replacing lost wages at a percentage of the worker's
average weekly wage — commonly around **two-thirds** — subject to state
maximum and minimum amounts, and usually **after a short waiting period**,
which is often retroactive if the disability lasts beyond a set duration. Four
classes:

- **Temporary total** — cannot work at all, but will recover.
- **Temporary partial** — can work in a reduced capacity, will recover.
- **Permanent partial** — a lasting impairment; often paid on a **schedule**
  setting a number of weeks per body part.
- **Permanent total** — cannot return to any gainful employment.

**Rehabilitation** — medical and vocational, to return the worker to
employment.

**Death benefits** — burial expenses up to a stated amount, and income
benefits to surviving dependants.

## The policy's three parts

**Part One — Workers' Compensation.** The insurer pays **whatever the
statute requires**. There is **no dollar limit**, because the obligation is
the state's, not the policy's. The states listed in the declarations (Item
3.A) are where this applies.

**Part Two — Employers' Liability.** Covers the employer's liability for
work-related injury **that falls outside the compensation statute**. This is
where the limits live, commonly written as three: **bodily injury by accident
each accident / bodily injury by disease policy limit / bodily injury by
disease each employee.**

It answers exposures such as:

- **Third-party-over actions** — the injured employee sues a manufacturer,
  which then sues the employer for contribution.
- **Consequential bodily injury** to a family member.
- **Loss of consortium** claims by a spouse.
- **Dual capacity** — the employer is sued in a second role, such as the
  maker of the machine that caused the injury.

**Part Three — Other States Insurance.** Extends Part One to states listed in
Item 3.C where the insured **may** begin operations during the policy period.
A state named in **neither** 3.A nor 3.C has no coverage — and adding it after
an injury is too late. **Monopolistic states cannot be covered here at all**,
because in those states coverage must be bought from the state fund.

## Premium determination

Examined more often than candidates expect.

> **Premium = (payroll ÷ 100) × rate × experience modification factor**

- **Payroll** is per **$100** of remuneration, by **classification code**. A
  business with clerical and roofing staff pays very different rates on each.
- **The rate** reflects the hazard of the classification.
- **The experience modification factor** compares this employer's actual
  losses with those expected for its class and size. **Above 1.0 means worse
  than average and a higher premium; below 1.0 means better and a credit.**
  This is the mechanism that rewards safety.

Because payroll is not known in advance, the policy is written on an
**estimated** payroll and a **deposit premium** is paid at inception. At the
end of the period the insurer conducts a **premium audit** of the actual
payroll and issues an additional premium or a return. **The insured must
permit the audit and keep records** — a policy condition.

Larger employers may use **retrospective rating**, where the final premium
depends on the employer's own losses during the period, within a maximum and
minimum.

## How an employer obtains coverage

- **The voluntary market** — a standard insurer.
- **An assigned risk pool or state fund** — for employers the voluntary market
  will not write.
- **A monopolistic state fund** — in a handful of states, the only source, and
  employers' liability must then be bought separately by endorsement to the
  CGL.
- **Qualified self-insurance**, for employers with the financial capacity and
  the regulator's approval.

## How this is examined

**Exclusive remedy**, and the three defences the employer surrendered.

**Medical benefits are unlimited**; disability income is not.

**Part One has no limit; Part Two carries the limits.**

**Other States Insurance** — a state in neither 3.A nor 3.C is uncovered.

**The premium formula**, and what an experience modification above 1.0 means.

**Deposit premium and audit.**

**The going and coming rule.**

## Check yourself

1. An employee is injured by a co-worker's carelessness. Can the employer rely
   on the fellow servant rule?
2. An employee is hurt by a defective press. Who may be sued, and by whom?
3. Is there a dollar limit on medical benefits?
4. An employer with operations in Oklahoma has only Texas in Item 3.A and
   nothing in 3.C. An Oklahoma employee is injured. Covered?
5. An employer's experience modification factor is 1.25. What does that mean
   for the premium?
6. An employee slips in the car park on the way home from work. Compensable?

## Answers

1. **No.** The employer surrendered contributory negligence, assumption of
   risk and the fellow servant rule as part of the bargain, and pays without
   regard to fault.
2. The employee may sue **the press manufacturer** (a third party); the
   **employer may not be sued**, by exclusive remedy. The compensation insurer
   subrogates against the manufacturer.
3. **No.** Medical benefits are generally unlimited under the statute.
4. **No.** A state appearing in neither 3.A nor 3.C has no coverage, and it
   cannot be added retroactively.
5. It is **25% worse than expected** for its class, so the premium is
   increased by 25%.
6. **Usually yes** — the employer's own car park is generally treated as
   premises, so the going and coming rule does not bar it.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'e6d0d8ef-84b7-5b74-9c0e-4273d4262777', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
