-- Texas Exam Prep — content seed, chunk 13 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Crime',
       'crime', 'Five crimes the exam insists you distinguish, and the coverage that answers the one that costs most.', 5,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', c.id, $lesson$# Words that mean the same thing in conversation and different things here

Most of this topic is definitions. The exam tests them relentlessly, because
in ordinary speech burglary, robbery and theft are interchangeable and in
insurance they are not.

## The five definitions

**Theft** is the **broadest** term: the unlawful taking of property. Burglary
and robbery are both kinds of theft.

**Burglary** is **the taking of property from inside premises, by somebody who
unlawfully entered or left, with visible signs of forced entry or exit.**

Two elements: **forcible entry** and **visible marks**. No marks, no burglary.
A thief who walks through an unlocked door has not committed burglary for
insurance purposes, however obviously they have stolen something.

**Robbery** is **taking property from a person, by violence or the threat of
violence.**

The element is **a person put in fear**. Robbery requires a victim who is
present and threatened. A pickpocket is not committing robbery, because there
is no threat.

**Mysterious disappearance** is property that **vanishes with no explanation
and no evidence of how**. Not a crime so much as a category — property that
is simply gone.

The practical consequence: **an insured who cannot prove burglary or robbery
falls back on mysterious disappearance**, and many forms exclude or limit it
precisely because it cannot be investigated.

**Forgery and alteration** is the **signing of another's name without
authority**, or the altering of a financial instrument — cheques, drafts,
promissory notes.

### Holding them apart

| | Where | How | Proof needed |
| --- | --- | --- | --- |
| **Burglary** | Inside premises | **Forced entry or exit** | **Visible marks** |
| **Robbery** | From a **person** | **Force or threat of force** | A person put in fear |
| **Theft** | Anywhere | Any unlawful taking | Broadest |
| **Mysterious disappearance** | Anywhere | Unknown | None available |

One sentence that carries all four: **burglary breaks in, robbery threatens a
person, theft covers both and more, and mysterious disappearance is what is
left when you cannot say which.**

## Employee dishonesty

**The largest crime exposure most businesses have is not a stranger. It is an
employee.**

**Employee dishonesty coverage (fidelity)** covers **loss of money,
securities and other property caused by the dishonest acts of employees** —
theft, embezzlement, forgery.

What to know:

- **The employee must intend to cause the employer a loss and obtain a
  financial benefit.** Simple negligence, or a mistake, is not dishonesty.
- It is written on one of two bases: **per loss**, where the limit applies to
  each dishonest act or scheme regardless of how many employees were involved,
  or **per employee**, where it applies separately to each.
- **Discovery of a dishonest act by an employee ends coverage for that
  employee immediately**, since the risk is no longer fortuitous.
- **Coverage is generally excluded for loss proved only by an inventory
  computation or profit-and-loss comparison.** A shortage on the books is not
  by itself proof of theft — though such records may support a claim otherwise
  proved.

## Discovery and loss-sustained forms

The trigger question, and a favourite:

- **A loss-sustained form** covers losses **occurring during the policy
  period** and discovered during it or within a short period afterwards.
- **A discovery form** covers losses **discovered during the policy period**,
  whenever they occurred.

**The discovery form is broader**, because employee dishonesty is typically
found long after it began — the average embezzlement runs for years before
anybody notices.

## The crime coverage forms

Commercial crime is assembled from insuring agreements, bought individually:

- **Employee theft** (fidelity).
- **Forgery or alteration**.
- **Inside the premises — theft of money and securities**, covering theft,
  disappearance and destruction.
- **Inside the premises — robbery or safe burglary of other property.**
- **Outside the premises**, covering money, securities and property in the
  care of a **messenger**.
- **Computer fraud** and **funds transfer fraud**.
- **Money orders and counterfeit money.**

Two roles the forms define: a **custodian** is the insured, a partner, or an
employee with care and custody of property inside the premises; a
**messenger** is one of those people **outside** the premises. A **watchperson**
is retained specifically to guard the premises, and some coverages require one
to be on duty.

## What is excluded

- **Acts of the insured** — the owner cannot steal from himself and claim.
- **Loss proved only by inventory or profit-and-loss computation.**
- **Accounting or arithmetical errors.**
- **Trading losses** and **voluntary parting** — property handed over because
  the insured was tricked into it, which is why social engineering fraud
  became a separate insuring agreement.
- **War, nuclear hazard, governmental action.**
- **Vandalism** damage in some forms, and damage to the premises, unless
  specifically covered.

## Bonds versus crime insurance

Both address dishonesty, and they are different instruments — covered fully in
the bonds lesson. In short: **a fidelity bond guarantees the honesty of a
named person or position**, while **employee dishonesty insurance covers the
employer's loss** from employees generally.

## How this is examined

**Burglary requires visible marks of forced entry.** This is the single most
reliable crime question.

**Robbery requires a person threatened.**

**Discovery versus loss-sustained**, and which is broader.

**Employee dishonesty excludes loss proved only by inventory shortage.**

**Coverage for an employee ends on discovery of a dishonest act by them.**

## Check yourself

1. A thief enters through an unlocked window, steals a laptop and leaves no
   marks. Is this burglary?
2. A courier carrying the day's takings is threatened with a knife and hands
   over the bag. Which crime, and which insuring agreement?
3. A bookkeeper diverts $80,000 over four years. The scheme is discovered in
   year five, after the policy in force during the theft has expired. Which
   form responds?
4. An annual stocktake shows $30,000 of missing inventory and nothing else.
   Is that a covered employee dishonesty loss?
5. An employer discovers an employee stole $500 two years ago and keeps them
   on. The employee steals again. Covered?

## Answers

1. **No.** Burglary requires **visible signs of forced entry or exit**. It is
   theft, and may be a mysterious disappearance claim depending on the form.
2. **Robbery** — property taken from a person by threat of violence. The
   **outside the premises** insuring agreement, the courier being a
   **messenger**.
3. **A discovery form**, which covers losses **discovered** during the policy
   period whenever they occurred. A loss-sustained form would likely not
   respond.
4. **No.** Loss proved **only** by inventory computation is excluded.
5. **No.** Coverage for that employee ended on discovery of the first
   dishonest act.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '4760b3ca-72c7-5e8f-8c13-12aa4084dde5', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '9de6577b-bb16-5031-9916-7726f5831b08', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Bonds',
       'bonds', 'Why a bond has three parties and insurance has two, and what that changes.', 6,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '9de6577b-bb16-5031-9916-7726f5831b08', c.id, $lesson$# Not insurance, though it is sold by insurers

A bond and an insurance policy look similar and behave differently. The
difference is the whole topic.

## Two parties versus three

**An insurance policy has two parties**: the insurer and the insured. The
insurer accepts a risk and expects some losses; premiums are priced to pay
them.

**A bond has three**:

- **The principal** — the party whose performance or honesty is guaranteed.
- **The obligee** — the party protected, who required the bond.
- **The surety** — the party guaranteeing the principal to the obligee.

**The surety guarantees the principal's performance to the obligee. If the
principal fails, the surety pays the obligee — and then recovers from the
principal.**

That last clause is the crux. **A surety expects no losses.** Suretyship is
underwritten as a credit decision, not a risk decision: the surety is
satisfied the principal can and will perform, and treats any payment as an
advance to be repaid.

Two consequences follow directly, and both are examined:

- **The principal must indemnify the surety.** An insured never repays an
  insurer; a principal always repays a surety.
- **Bond underwriting examines the principal's character, capacity and
  capital** — credit, experience, financial statements, work in progress.

## Surety bonds

### Contract bonds

Used in construction, where an owner needs assurance the job will be finished.

- **Bid bond** — guarantees that if the contractor is awarded the job, they
  will **enter into the contract** at the bid price and furnish the required
  performance bond. Protects the owner against a contractor who bids low and
  walks away, leaving the owner with the next-lowest bid.
- **Performance bond** — guarantees the work will be **completed** per the
  contract. If the contractor defaults, the surety must complete the job,
  arrange for its completion, or pay the owner's cost of completing it.
- **Payment bond** (labour and material) — guarantees that **subcontractors
  and suppliers are paid**, so they do not file liens against the owner's
  property.
- **Maintenance bond** — guarantees the work against **defects** for a stated
  period after completion.
- **Supply bond** — guarantees delivery of materials per a supply contract.
- **Completion bond** — given to a **lender** rather than an owner,
  guaranteeing the project is finished free of liens.

The bid–performance–payment sequence is the most common exam question in this
lesson: **the bid bond gets you the contract, the performance bond finishes
the work, the payment bond pays the subcontractors.**

### Court bonds

- **Judicial bonds** guarantee a party in litigation will meet its
  obligations: **appeal bonds**, **attachment bonds**, **injunction bonds**,
  **replevin bonds**.
- **Fiduciary bonds** guarantee that a person appointed by a court to manage
  another's affairs — an **executor, administrator, guardian, trustee or
  receiver** — will do so faithfully.
- **Bail bonds** guarantee a defendant's appearance in court.

### Public official bonds

Guarantee that an elected or appointed official will **faithfully perform the
duties of office and account for public funds.**

### Licence and permit bonds

Required by a public authority before a licence issues. They guarantee the
holder will **comply with the law governing the activity** and compensate
those harmed by non-compliance. **Insurance producers in many states must
carry one**, which is the example closest to home.

## Fidelity bonds

**A fidelity bond guarantees the honesty of a person handling money or
property.** It is the one class of bond closest to insurance, and the exam
tests the difference from employee dishonesty coverage.

Three forms of coverage:

- **Name schedule** — covers **named individuals**, each with a stated
  amount. Adding a person requires notifying the surety.
- **Position schedule** — covers **positions** rather than people, so whoever
  occupies "head cashier" is covered.
- **Blanket** — covers **all employees**, without naming anybody.

Blanket forms come in two shapes: **commercial blanket**, where the limit
applies **per loss** however many employees were involved, and **blanket
position**, where the limit applies **to each employee**, so a three-employee
conspiracy has three limits available.

**Blanket position provides more coverage for the same limit** where several
employees collude, which is the distinction to remember.

## Bonds versus insurance, side by side

| | Insurance | Surety bond |
| --- | --- | --- |
| Parties | **Two** | **Three** |
| Expectation of loss | Losses expected, priced in | **No loss expected** |
| Repayment | Insured never repays | **Principal must indemnify the surety** |
| Underwriting | Risk selection | **Credit judgement** |
| Cancellation | Usually cancellable | Often non-cancellable for the bond's term |
| Premium | Rate for assumed risk | A **service fee** for the guarantee |

## How this is examined

**The three parties, and who is who** in a fact pattern. The contractor is the
principal; the project owner is the obligee; the bonding company is the
surety.

**The principal must reimburse the surety.**

**Bid versus performance versus payment bond.**

**Blanket position versus commercial blanket** where several employees are
involved.

**A bond is a credit instrument**, not a risk transfer.

## Check yourself

1. A contractor is bonded on a school project. Who is the principal, who the
   obligee, who the surety?
2. A contractor abandons a job half-finished. The surety pays the owner
   $400,000 to complete it. Does the contractor owe anything?
3. A contractor submits the low bid and then refuses to sign. Which bond, and
   what does it protect the owner against?
4. Subcontractors are unpaid and threaten liens on the owner's property. Which
   bond?
5. Four employees conspire to steal $200,000. The employer has a $75,000
   blanket position bond. Roughly what is available?
6. Why does a surety expect no losses?

## Answers

1. The **contractor** is the principal, the **school district** the obligee,
   the **bonding company** the surety.
2. **Yes — the full $400,000.** The principal must indemnify the surety.
3. The **bid bond**, protecting the owner against the extra cost of going to
   the next bidder.
4. The **payment bond** (labour and material).
5. **$300,000** — blanket position applies the limit **to each employee**, so
   four employees give four limits.
6. Because the bond is a **credit judgement**: the surety underwrites the
   principal's ability and willingness to perform, and any payment is
   recoverable from the principal.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '9de6577b-bb16-5031-9916-7726f5831b08', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
