-- Texas Exam Prep — content seed, chunk 14 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '858d9378-6837-5721-8736-5adc0bb90504', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Professional Liability',
       'professional-liability', 'The coverages that answer for advice, expertise and decisions — all excluded from the CGL.', 7,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '858d9378-6837-5721-8736-5adc0bb90504', c.id, $lesson$# When the injury is caused by judgement, not by an accident

**The CGL excludes professional services.** It covers accidents — a customer
slipping, a product failing. It does not cover the consequences of getting
professional advice wrong, because that is not an accident and cannot be
priced like one.

Professional liability fills the gap, and it differs from the CGL in three
structural ways:

- **The trigger is usually claims-made**, not occurrence, because professional
  claims surface years later.
- **It commonly covers economic loss**, not just bodily injury and property
  damage. A negligent audit causes no physical harm at all.
- **Many forms require the insured's consent to settle**, because a settlement
  implies professional failure and may be reportable.

## The standard of care

The insured is judged against **what a reasonably prudent member of that
profession would have done in the same circumstances**. This is a higher and
more specific standard than the ordinary reasonable-person test of general
negligence, and it is why the profession's own practices are usually decisive.

## Errors and omissions

**E&O covers financial loss suffered by a client because of the insured's
negligent act, error or omission in performing professional services.**

The general-purpose form, used for professions whose failures cost money
rather than health: **insurance agents and brokers**, real estate agents,
accountants, architects and engineers, consultants, technology providers,
lawyers (usually "lawyers professional liability").

**An insurance producer's own E&O** is the closest example. The claim that
brings it: failing to place requested coverage, placing the wrong limit,
letting a policy lapse, or giving advice on coverage that turns out wrong.

## Medical malpractice

**Covers physicians, surgeons, dentists, nurses and other health care
providers** for injury arising from professional services.

Two related forms:

- **Professional liability** for the individual practitioner.
- **Hospital or health care facility professional liability** for the
  institution, plus a **general liability** part for ordinary premises
  accidents.

Points that appear:

- **Consent to settle is common**, because settlements are reported to
  national practitioner databanks and affect licensure.
- **Tail coverage matters enormously**, because a claim may arise many years
  after treatment — particularly where a child was the patient, since the
  limitation period may not begin until they reach majority.
- **Medical payments under a CGL** is a different thing entirely: it pays a
  visitor's medical bills without fault and has nothing to do with
  malpractice.

## Directors and officers

**D&O covers the personal liability of directors and officers for wrongful
acts in managing the organisation** — breaches of duty, misstatements,
misleading statements, neglect or errors in their capacity as officers.

Who sues: **shareholders, employees, competitors, customers, regulators**.
The claims are typically about decisions rather than accidents — a
misrepresentation in a prospectus, a sale at an inadequate price, a failure to
supervise.

The three standard insuring agreements:

- **Side A** — pays the **individual directors and officers** where the
  company cannot or does not indemnify them, such as in insolvency or where
  indemnification is legally barred.
- **Side B** — reimburses **the company** for indemnifying its directors and
  officers.
- **Side C** — covers **the entity itself** for securities claims.

**Side A is the coverage a director personally cares about**, because it is
the one that survives the company's failure. That is the examinable point.

## Employment practices liability

**EPLI covers claims by employees and applicants arising from the employment
relationship**: wrongful termination, discrimination, harassment, retaliation,
failure to promote, wrongful discipline, defamation in the employment context.

It exists because **the CGL excludes it** and **workers' compensation does not
reach it** — these are not bodily injuries at work, they are employment
decisions. It is claims-made, and usually carries a deductible or retention the
employer bears on every claim, since small claims are frequent.

## Cyber liability and data breach

**The third-party half of cyber**, complementing the first-party coverage in
the commercial property lesson.

It covers what the insured **owes others** after a cyber event:

- **Liability for a privacy breach** — claims by individuals whose personal
  data was exposed.
- **Regulatory defence and penalties**, where the law permits them to be
  insured.
- **Network security liability** — where the insured's compromised systems
  harmed a third party.
- **Media liability** — defamation or infringement in the insured's online
  content.

**Funds transfer fraud** and **social engineering** — where an employee is
deceived into wiring money to a fraudster — sit on the first-party side, and
are often sub-limited because the exposure is large and the control is human
rather than technical.

Why cyber is bought separately: standard forms respond to **physical damage to
tangible property**, and **data is generally not tangible property**. Many
forms now also carry express cyber exclusions.

## Liquor liability

**Covers those in the business of manufacturing, distributing, selling,
serving or furnishing alcohol** for liability arising from that activity.

**The CGL excludes it for those in the business.** The exclusion does not
apply to a host who is not in the alcohol business, so an ordinary company
holding a party retains **host liquor liability** under its CGL.

The exposure arises from **dram shop laws** — statutes making a server liable
for injury caused by a patron served while obviously intoxicated, or served
under age. Where a state has a dram shop act, a restaurant or bar without
liquor liability coverage is running an uninsured exposure.

The exam wants two things: **the CGL covers host liquor liability but excludes
those in the alcohol business**, and **dram shop laws are the reason.**

## Claims-made mechanics, once more

Because nearly every form here is claims-made:

- **The retroactive date** bars acts before it, whenever the claim arrives.
  Watch for a renewal that advances it.
- **A basic extended reporting period** is automatic and short.
- **A supplemental extended reporting period** — the "tail" — is purchased,
  must be bought within a short window after expiry, and is what a
  professional retiring or changing insurer needs.
- **Prior acts coverage** on a new policy, with the retroactive date preserved,
  is the alternative to buying a tail.

## How this is examined

**The CGL excludes professional services** — which is why every one of these
exists.

**Side A D&O** protects individuals when the company cannot indemnify them.

**Host liquor liability is covered by the CGL; those in the business are
excluded.**

**Consent to settle** is a professional liability feature.

**Claims-made retroactive dates and tails.**

**EPLI covers employment decisions, which are neither CGL nor workers'
compensation claims.**

## Check yourself

1. An insurance agent fails to add a newly purchased building to a client's
   policy and it burns. Which coverage responds?
2. A company holds a Christmas party; a guest drinks too much and injures
   somebody driving home. Does the CGL respond?
3. A corporation becomes insolvent and cannot indemnify its directors, who are
   personally sued. Which D&O insuring agreement?
4. An employee sues for wrongful termination. CGL, workers' compensation, or
   something else?
5. A surgeon retires. Claims may arise for years. What must be arranged?
6. A hacker steals customer records and the customers sue. First-party or
   third-party cyber coverage?

## Answers

1. The agent's **errors and omissions** policy.
2. **Yes** — the company is not in the alcohol business, so **host liquor
   liability** remains covered by the CGL.
3. **Side A**, which pays the individuals directly where the company cannot.
4. **Employment practices liability.** The CGL excludes it and workers'
   compensation does not reach employment decisions.
5. A **supplemental extended reporting period** (tail), bought within the
   window after the policy ends — or prior acts coverage on a new policy with
   the retroactive date preserved.
6. **Third-party** — cyber liability. The customers' claims are what the
   insured owes others.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '858d9378-6837-5721-8736-5adc0bb90504', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '88047c29-a279-5436-aa7a-24977ea5abb2', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'Umbrella and Excess Liability',
       'umbrella-and-excess-liability', 'More limit on top of what you have — and, in an umbrella, some coverage the underlying policies never had.', 8,
       'draft', 12
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '88047c29-a279-5436-aa7a-24977ea5abb2', c.id, $lesson$# Two things that look the same and are not

Both sit above a primary policy. Only one of them broadens coverage.

## Excess liability

**An excess policy provides additional limits over specified underlying
policies, following their terms.**

It is described as **"following form"** — it covers what the underlying policy
covers, no more and no less, and it begins where the underlying limit ends.
If the primary policy excludes something, so does the excess.

An excess policy buys **height**, not **breadth**.

## Umbrella liability

**An umbrella does three things**, and the third is what distinguishes it:

1. **It provides excess limits** over the underlying policies — like an
   excess policy.
2. **It drops down** to replace an underlying policy whose aggregate has been
   exhausted by other claims.
3. **It covers some losses the underlying policies exclude**, subject to a
   **self-insured retention**.

That third function is the examined one. **Where a claim is covered by the
umbrella but not by any underlying policy, the umbrella pays — after the
insured bears the self-insured retention.**

### The self-insured retention

**The SIR is the amount the insured pays on a claim the umbrella covers but no
underlying policy does.** Commonly $10,000 or $25,000.

It is not a deductible in the ordinary sense: **it applies only where there is
no underlying coverage.** Where an underlying policy does respond, the
umbrella simply sits above its limit and the SIR is irrelevant.

What an umbrella typically covers beyond the underlying policies: **personal
injury offences** not in the underlying form, **worldwide coverage**,
**liability assumed under contract** beyond the underlying's insured contract
definition, and certain **watercraft and aircraft** exposures.

## Underlying limit requirements

An umbrella requires the insured to **carry and maintain stated underlying
limits** — commonly $1,000,000 per occurrence on general liability,
$1,000,000 on auto, and $500,000 or $1,000,000 on employers' liability.

**If the insured lets an underlying policy lapse or carries less than
required, the umbrella responds as though the required underlying limit were
in place**, and the insured absorbs the shortfall. That is a reliable exam
point: the umbrella does not become primary just because the primary vanished.

## Personal umbrella

The personal version sits above homeowners and personal auto, typically
requiring $300,000 or $500,000 of underlying liability on each.

- **Limits start at $1,000,000** and are bought in millions.
- It covers **personal injury** offences — libel, slander, false arrest,
  invasion of privacy — which a homeowners policy typically does not.
- It **excludes business and professional exposures**, intentional acts, and
  the insured's own injuries.
- It is cheap relative to its limit, because the underlying policies absorb
  the frequent small claims and the umbrella sees only the rare severe one.

## How the layers stack

A commercial programme might read:

| Layer | Limit |
| --- | --- |
| **Primary CGL** | $1,000,000 |
| **Umbrella** | $5,000,000 excess of the primary |
| **Excess (first layer)** | $10,000,000 excess of $6,000,000 |
| **Excess (second layer)** | $25,000,000 excess of $16,000,000 |

A $4,000,000 judgment: the CGL pays $1,000,000, the umbrella pays $3,000,000,
the excess layers pay nothing. Each layer is only reached when everything
beneath it is exhausted.

## How this is examined

**Umbrella broadens; excess does not.**

**The self-insured retention applies only where no underlying policy
responds.**

**An insufficient or lapsed underlying policy leaves the insured to fill the
gap**, not the umbrella.

**Drop-down** where the underlying aggregate is exhausted by other claims.

**Layering arithmetic** with a judgment spread across policies.

## Check yourself

1. A claim is excluded by the CGL but covered by the umbrella. The SIR is
   $25,000 and the loss is $300,000. What does the umbrella pay?
2. The same insured's CGL aggregate is exhausted in October by earlier claims.
   A new covered claim arrives in November. What does the umbrella do?
3. An umbrella requires $1,000,000 of underlying auto liability. The insured
   carries $500,000 and has a $3,000,000 loss. What is the insured's share?
4. Does an excess policy cover a loss the primary excludes?
5. A personal umbrella insured is sued for slander. The homeowners policy does
   not cover it. Is the umbrella likely to?

## Answers

1. **$275,000** — the loss less the $25,000 self-insured retention, which
   applies because no underlying policy responds.
2. It **drops down** to respond in place of the exhausted underlying
   aggregate.
3. **$500,000.** The umbrella responds as though the required $1,000,000 were
   in place, so the insured absorbs the shortfall between the $500,000
   actually carried and the $1,000,000 required.
4. **No.** An excess policy follows form — it adds limit, not breadth.
5. **Yes.** Umbrellas typically cover personal injury offences such as
   slander, subject to the self-insured retention.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '88047c29-a279-5436-aa7a-24977ea5abb2', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'c7b0a9e9-5837-5a19-a830-e1c77b9bda93', '2071512a-2630-55ae-b69b-68d3232b7633', c.id, 'The Business Owners Policy',
       'the-business-owners-policy', 'A pre-packaged commercial policy for small businesses — and the eligibility rules that decide who gets one.', 9,
       'draft', 12
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'c7b0a9e9-5837-5a19-a830-e1c77b9bda93', c.id, $lesson$# The homeowners policy of commercial insurance

The commercial package policy in Module 3 is assembled part by part. That
suits a large or unusual risk and is wasted effort on a dry cleaner.

**A BOP is a pre-packaged policy combining commercial property and general
liability for small and medium businesses**, with terms already chosen, often
broader than the equivalent CPP, and cheaper.

It appears in the blueprint twice — under types of policies and again under
casualty — which tells you it is examined.

## What it contains

**Property**, on an **open peril** basis in the standard form:

- **Buildings**, including additions, fixtures, permanently installed
  machinery, and outdoor fixtures.
- **Business personal property**, at the described premises and within a
  short distance of them.
- **Business income and extra expense — included, not optional.** This is the
  headline difference from a CPP, where both must be bought.

**Liability**:

- **Bodily injury and property damage** liability.
- **Personal and advertising injury.**
- **Medical payments.**

## What makes it different from a CPP

These are the examined distinctions:

- **Business income and extra expense are built in**, commonly with **no
  dollar limit and no coinsurance**, payable for a stated maximum period —
  often **12 months** — after a waiting period.
- **No coinsurance clause** on the property coverage. Instead the form relies
  on an **automatic increase** in the building limit and a requirement to
  insure to full value. This removes the single most common source of
  underpayment on a small commercial claim.
- **Replacement cost is the standard** loss settlement basis, with actual cash
  value available as an option.
- **Seasonal automatic increase** in business personal property — commonly 25%
  — covering the stock build-up before a busy season.
- **Terms are largely fixed.** Less can be negotiated, which is the trade for
  the price.

Coverages commonly included in modest amounts without extra premium: **debris
removal, fire department service charge, money and securities, employee
dishonesty, forgery, glass, outdoor signs, valuable papers, accounts
receivable, pollutant clean-up**, and **newly acquired property** for a
limited period.

## Eligibility

The rules are the part most likely to be asked about, because they are what a
producer applies first.

**Generally eligible**: small **offices**, **retail stores**, **apartment
buildings**, **wholesalers**, small **processing and service businesses**,
**restaurants** within limits, and **contractors** within limits — subject to
insurer-specific caps on:

- **Building size** — commonly up to a stated square footage;
- **Annual revenue** — a stated maximum; and
- **Number of storeys**.

**Generally ineligible**:

- **Automobile dealers, repair shops and service stations** — the garage
  exposure needs its own form.
- **Banks and financial institutions.**
- **Insurance agents** — professional exposure.
- **Bars and taverns**, and many places of amusement.
- **Manufacturers**, beyond limited light manufacturing.
- **Condominium associations** above stated sizes, and **one- to four-family
  dwellings**, which belong on personal lines forms.

A useful way to hold it: **a BOP suits a business whose risk is ordinary and
whose size is small. Anything with a specialised exposure — vehicles, alcohol,
professional advice, heavy manufacturing — is sent to a form built for it.**

## What is not in a BOP

Even where a business is eligible, several exposures must be bought
separately:

- **Workers' compensation** — always a separate policy.
- **Commercial auto** — the BOP covers no vehicles.
- **Professional liability.**
- **Liquor liability**, for those in the business.
- **Flood and earthquake.**
- **Employment practices liability** and **cyber**, though both are now
  commonly available by endorsement.

## How this is examined

**Business income and extra expense are included**, with no coinsurance.

**There is no coinsurance clause** on BOP property.

**Which businesses are ineligible** — auto dealers, banks, bars,
manufacturers.

**Workers' compensation and commercial auto are never part of a BOP.**

**BOP versus CPP** — a fixed package for a small ordinary risk versus an
assembled one for a large or unusual risk.

## Check yourself

1. A small accounting practice wants property and liability coverage in one
   policy. Eligible for a BOP? Is anything missing?
2. A restaurant's kitchen fire closes it for four months. Does a BOP pay for
   the lost trading?
3. A retailer insures a building for $400,000 when it is worth $600,000 and
   suffers a $100,000 loss. How does the BOP settle it, compared with a CPP at
   80% coinsurance?
4. A business buys a BOP and employs six people. What must it still buy?
5. Why is an auto repair shop ineligible?

## Answers

1. **Eligible for the property and general liability**, yes — but the firm's
   **professional liability (E&O)** is excluded from a BOP and must be bought
   separately, along with workers' compensation.
2. **Yes.** Business income is **included** in a BOP, typically for up to 12
   months after a waiting period.
3. The **BOP has no coinsurance clause**, so the loss is paid in full subject
   to the limit. Under a **CPP at 80% coinsurance**, "should" is $480,000 and
   "did" is $400,000, so the payment is reduced to about 83% — roughly
   $83,333 less the deductible.
4. **Workers' compensation**, and **commercial auto** if any vehicles are
   used. Neither is ever part of a BOP.
5. The **garage exposure** — customers' vehicles in its care — needs an auto
   dealers coverage form with garagekeepers coverage, which a BOP does not
   provide.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'c7b0a9e9-5837-5a19-a830-e1c77b9bda93', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.IV'
on conflict (lesson_id, topic_id) do nothing;

commit;
