-- Texas Exam Prep — content seed, chunk 15 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '91b3d873-84de-514a-9dc7-fa8c3f0093fc', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'The Commissioner and the Department',
       'the-commissioner-and-the-department', 'Who regulates insurance in Texas, where their power comes from, and how a rule differs from a statute.', 1,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '91b3d873-84de-514a-9dc7-fa8c3f0093fc', c.id, $lesson$# The regulator

Everything in this module is Texas law. Where the general-knowledge modules
described how insurance works, this one describes what Texas requires — and
the answers are numbers and citations rather than principles.

> **Every statement in this module cites the section it came from**, and every
> citation was checked against the text of the Texas Insurance Code rather
> than recalled. Where a figure is not cited, it is not in this course.

## Two codes, and the difference between them

**The Texas Insurance Code (TIC)** is statute — law passed by the
Legislature.

**The Texas Administrative Code (TAC), Title 28** is rules — made by the
Commissioner under authority the statute grants. A rule has the force of law
but cannot exceed the statute it rests on.

The exam cites both. When a question says "under Department rules", it means
the TAC; "under the Insurance Code", the TIC.

## The Department and the Commissioner

**The Texas Department of Insurance (TDI)** administers the Insurance Code.
**The Commissioner of Insurance** is its chief executive.

**§31.002, "DUTIES OF DEPARTMENT"**, lists five. Verbatim, the department
shall:

> "(1) regulate the business of insurance in this state; (2) administer the
> workers' compensation system of this state as provided by Title 5, Labor
> Code; (3) ensure that this code and other laws regarding insurance and
> insurance companies are executed; (4) protect and ensure the fair treatment
> of consumers; and (5) ensure fair competition in the insurance industry in
> order to foster a competitive market."

Two things follow. **Consumer protection and fair competition are both
statutory duties** (4) and (5), so the Department is directed to pursue them
together rather than trade one against the other. And duty (2) is the reason
Texas workers' compensation appears in an insurance exam at all: **TDI
administers the workers' compensation system**, under the Labor Code rather
than the Insurance Code.

**§31.021(a)** — "The commissioner is the department's chief executive and
administrative officer" and "shall administer and enforce this code, other
insurance laws of this state, and other laws granting jurisdiction or
applicable to the department or the commissioner." **§31.021(b)** extends the
same to Title 5 of the Labor Code.

### Rulemaking

**Chapter 36** is the Commissioner's rulemaking authority. The Commissioner
may adopt reasonable rules **necessary to effect the purposes** of the code —
which is the limit as well as the grant. A rule that goes beyond what the
statute authorises can be challenged.

### Hearings and appeals

**Chapter 40** assigns contested hearings to the **State Office of
Administrative Hearings (SOAH)**, an agency independent of TDI. The point is
structural: the regulator that brings the charge does not also decide it.

**Government Code §2001.051** — cited by the blueprint — is the
Administrative Procedure Act's guarantee of an opportunity for hearing and
for the presentation of evidence.

Orders are appealed to the courts under **Subchapter D, Chapter 36**.

## Examination and investigation

**Chapter 38** gives the Department its information-gathering powers, and
**Chapter 401** covers examination of insurers' records. The Commissioner may
examine the affairs of any person engaged in the business of insurance in
Texas.

**§541.101** states it for trade practices specifically: the Department **may
examine and investigate the affairs of a person engaged in the business of
insurance** in this state to determine whether the person has engaged in a
prohibited act or practice.

The sequence that follows is the same throughout the code and is worth
learning once, because several chapters repeat it:

1. **Investigation** — the Department examines.
2. **Statement of charges and notice of hearing** — **§541.102**.
3. **Hearing** — **§541.103**, at which the person is entitled to be heard
   and to present evidence.
4. **Determination** — **§541.107**, whether the conduct is a violation.
5. **Order** — **§541.108**, a cease and desist order.
6. **Penalty** for disobeying it — **§541.110** and **§541.111**.
7. **Appeal** to the courts.

**Step 3 is the one candidates forget.** Except in the emergency procedure
covered in the next lesson, **the Department must hold a hearing before it
sanctions anybody.**

## Public access and confidentiality

**Chapter 39** governs public access to Department information, and
**§521.003–.004** the Department's handling of complaints and consumer
information. The general position: the Department's records are public unless
a statute makes them confidential, and investigation materials generally are
confidential while an investigation is live.

## How this is examined

**TIC versus TAC** — statute versus rule.

**The Department's five statutory duties** under §31.002, especially that
consumer protection and fair competition are both named, and that TDI
administers workers' compensation.

**SOAH hears contested cases**, not the Department itself.

**The order of the enforcement sequence**, and that a hearing precedes a
sanction.

## Check yourself

1. A question refers to "28 TAC § 21.203". Statute or rule, and who made it?
2. May the Commissioner adopt a rule imposing a duty the Insurance Code does
   not authorise?
3. Which body conducts a contested hearing against a licence holder?
4. Before the Department issues an ordinary cease and desist order under
   §541.108, what must happen first?
5. Name two of the Department's statutory duties under §31.002.

## Answers

1. A **rule**, in the Texas Administrative Code, adopted by the
   **Commissioner** under authority granted by the Insurance Code.
2. **No.** Rulemaking under Chapter 36 extends to rules necessary to effect
   the purposes of the code; it does not create new duties on its own.
3. The **State Office of Administrative Hearings**, under Chapter 40 — not
   the Department that brought the charge.
4. A **hearing**, under §541.102–.103, following investigation, with a
   determination under §541.107.
5. Any two of the five: regulate the business of insurance; administer the
   workers' compensation system under Title 5, Labor Code; ensure the code
   and other insurance laws are executed; protect and ensure the fair
   treatment of consumers; ensure fair competition to foster a competitive
   market.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '91b3d873-84de-514a-9dc7-fa8c3f0093fc', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '01ab26e9-4312-59b9-86ce-36df1d0aa6f1', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Enforcement and Penalties',
       'enforcement-and-penalties', 'Cease and desist orders, the emergency procedure, administrative penalties and the dollar figures attached to each.', 2,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '01ab26e9-4312-59b9-86ce-36df1d0aa6f1', c.id, $lesson$# What the Department can do to you

Four instruments, in rough order of severity: a **cease and desist order**, an
**administrative penalty**, a **sanction against the licence**, and
**restitution**. Criminal prosecution sits outside all four.

## Ordinary cease and desist — Chapter 541, Subchapter C

The sequence from the previous lesson, with the figures attached.

**§541.108** — after a hearing and a determination of violation, the
Department **shall** make written findings and issue a cease and desist order.
Note "shall": on finding a violation, the order is not discretionary.

**§541.109** — the Department may modify or set aside the order at any time
before an appeal is filed.

### Penalties for disobeying the order

Two different penalties, for two different forums, and the exam separates
them:

| | Imposed by | Cap |
| --- | --- | --- |
| **Administrative penalty, §541.110** | the Department | **$1,000 per violation**, and **$5,000 for all violations** |
| **Civil penalty, §541.111** | a court, in an action by the state | **$50**, or **$500 if the court finds the violation wilful** |

Those are small numbers, and they are small on purpose: they punish
*disobeying the order*, not the underlying conduct. The underlying conduct is
punished under Chapter 84.

## Administrative penalties — Chapter 84

The general penalty power, and the number most likely to be asked.

**§84.021** — the Commissioner may impose an administrative penalty on a
person licensed or regulated under the code who violates the code, another
insurance law, or a rule or order adopted under either.

**§84.022(a)** — **"The penalty for a violation may not exceed $25,000,
unless a greater or lesser penalty is specified by this code or another
insurance law of this state."**

**$25,000 per violation is the headline figure**, and the trailing clause is
what makes §541.110's $1,000 cap possible: a specific provision displaces the
general one.

**§84.022(b)** lists what the amount is based on — seriousness, the hazard
created, economic harm to the public interest, history of previous
violations, the amount necessary to deter, efforts to correct, and **whether
the violation was intentional**.

### The procedure, with its clocks

- **§84.041(a)** — the Department issues a **report** to the Commissioner
  stating the facts and recommending a penalty and its amount.
- **§84.041(b)** — the Department must give the affected person **written
  notice of the report not later than the 14th day** after it is issued. The
  notice states the alleged violation, the recommended amount, and the right
  to a hearing.
- **§84.042(a)** — **not later than the 20th day after receiving the
  notice**, the person may in writing accept the determination and penalty,
  or request a hearing on the violation, the amount, or both.
- **§84.045** — once the Commissioner's order is final, the person has **30
  days** to pay the penalty or file a petition for judicial review.

**14, 20, 30** — those three are the likely question.

## Emergency cease and desist — Chapter 83

The exception to "a hearing comes first", and therefore heavily tested.

**§83.051(a)** — the Commissioner **ex parte** may issue an emergency cease
and desist order. *Ex parte* means without the other side present: **no
hearing beforehand.**

It is available where the Commissioner believes an authorized person engaging
in the business of insurance is committing an unfair act or is in a hazardous
financial condition, **and** the conduct:

- **is fraudulent**;
- **is hazardous or creates an immediate danger to the public safety**; or
- **is causing or can reasonably be expected to cause public injury** that is
  likely to occur at any moment, is incapable of being repaired, and has or is
  likely to have influence or effect.

It is also available against an **unauthorized person** engaging in the
business of insurance in violation of Chapter 101.

### The clocks

- **§83.052** — the order is served by **registered or certified mail, return
  receipt requested**, to the last known address, and requires the person to
  cease **immediately**.
- **§83.053(b)** — the person must request a hearing **not later than the 60th
  day** after being served.
- **§83.051(b)** — **the order is final on the 61st day** after service unless
  a hearing is requested.
- **§83.055** — pending the hearing, **the order stays in effect**. Requesting
  a hearing does not suspend it.

The shape to remember: **act first, hear later, and the order bites throughout.**

**§83.101–.104** — a person who violates an emergency order faces an
administrative penalty and may be ordered to make restitution.

## Sanctions against the authorization — Chapter 82

"Authorization" is defined at **§82.001** to include a permit, licence or
certificate of authority — so this chapter reaches both companies and
producers.

**§82.051** — **after notice and opportunity for a hearing**, the Commissioner
may cancel or revoke an authorization.

**§82.052** — instead of, or in addition to, revocation the Commissioner may
impose other sanctions.

**§82.053** — **restitution**. The Commissioner may order a person to make
restitution to a party harmed. Restitution is not a penalty: it returns money
to the person who lost it, and it can be ordered alongside a penalty that goes
to the state.

**§82.056** — the Commissioner **shall give notice to other states** of an
action taken. A Texas revocation follows a producer across state lines, which
is why an administrative action in any state must be reported everywhere the
producer is licensed.

## Criminal enforcement — Chapter 85

**§85.001** — a person who violates a provision of the code for which no
other punishment is provided commits an offence.

**§85.052** — a person who commits an offence under the code **may be
prosecuted under this code or any other law of this state**. The Insurance
Code's criminal provisions do not displace the Penal Code; theft and fraud
remain available.

## Putting the numbers together

| Instrument | Citation | Figure |
| --- | --- | --- |
| Administrative penalty, general | §84.022(a) | **$25,000** per violation |
| Violating a §541.108 order, administrative | §541.110(c) | **$1,000** each / **$5,000** all |
| Violating a §541.108 order, civil | §541.111(b) | **$50**, or **$500** if wilful |
| Notice of penalty report | §84.041(b) | **14 days** |
| Response to that notice | §84.042(a) | **20 days** |
| Pay or appeal after a final order | §84.045 | **30 days** |
| Request hearing on an emergency order | §83.053(b) | **60 days** |
| Emergency order becomes final | §83.051(b) | **61st day** |

## How this is examined

**$25,000** as the general administrative penalty cap, and that a specific
provision can set a different one.

**The emergency order needs no prior hearing**, stays in effect pending the
hearing, and becomes final on the 61st day.

**Restitution is distinct from a penalty** — one compensates, the other
punishes.

**Notice to other states** of an administrative action.

## Check yourself

1. May the Commissioner issue an emergency cease and desist order without a
   hearing?
2. A producer is served with an emergency order and requests a hearing on day
   20. May they carry on the conduct until the hearing?
3. What is the general cap on an administrative penalty, and where does it
   allow for exceptions?
4. A person disobeys a cease and desist order issued under §541.108. What is
   the maximum administrative penalty for all violations?
5. The Commissioner orders a producer to repay $40,000 taken from clients and
   separately imposes a penalty. What is the $40,000 called, and who receives
   it?
6. A Texas licence is revoked. Does that stay in Texas?

## Answers

1. **Yes** — §83.051(a) authorises it **ex parte**, on the grounds listed
   there. It is the exception to the hearing-first rule.
2. **No.** Under §83.055 the order continues in effect pending the hearing.
3. **$25,000** per violation under §84.022(a), "unless a greater or lesser
   penalty is specified by this code or another insurance law of this state."
4. **$5,000** — §541.110(c) caps it at $1,000 per violation and $5,000 for
   all violations.
5. **Restitution**, under §82.053. It goes to the **harmed parties**, not to
   the state.
6. **No.** Under §82.056 the Commissioner shall notify other states of the
   action.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '01ab26e9-4312-59b9-86ce-36df1d0aa6f1', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
