-- Texas Exam Prep — content seed, chunk 16 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'f55672f5-bcf6-53e5-90d9-cfcecc6ae951', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Licensing and Appointment',
       'licensing-and-appointment', 'Who needs a licence, what a temporary one allows, and the rule against getting licensed to insure your own family.', 3,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'f55672f5-bcf6-53e5-90d9-cfcecc6ae951', c.id, $lesson$# Getting and holding the licence

## Licence and appointment are two different things

**§4001.201** — a person who obtains a licence **may not engage in business as
an agent unless the person has been appointed** to act as an agent by an
insurer authorised to do business in Texas.

So the licence says the state permits you to sell insurance. **The
appointment says a particular insurer permits you to sell theirs.** You need
both, and the exam checks that you know a licence alone is not enough.

**§4001.202(a)** — an agent may represent **more than one insurer**, except
where the code specifically prohibits it.

**§4001.202(b)** — **not later than the 30th day after the effective date of
the appointment**, the agent and the insurer must notify the Department of any
additional appointment, on the prescribed form and with a non-refundable fee
for each.

## Intent to engage in business for the general public

**§4001.104** is the "controlled business" rule, and it is one of the most
reliably examined provisions in the Texas section.

**§4001.104(a)** — the Department **may not** issue an agent's licence unless
it determines that:

1. the applicant **is or intends to be actively engaged in soliciting or
   writing insurance for the general public**; and
2. the application **is not made to evade the laws against rebating and
   discrimination**.

**§4001.104(b)** explains the purpose in terms worth reading directly. The
subchapter does **not** prohibit an applicant from insuring property they own
or have an interest in. What it prohibits is licensing somebody

> "to engage in the business of insurance principally to handle business that
> the applicant controls only through ownership, mortgage, sale, family
> relationship, or employment."

It also states two aims: **to prohibit coercion of insurance**, and **to
preserve to each individual the right to choose their own agent or insurer.**

The distinction the exam tests: **insuring your own house is fine. Getting
licensed so that you can collect the commission on your own house, your
relatives' houses and your employer's fleet is not.** The test is whether the
controlled business is the *principal* purpose.

Failing this is also an independent ground for discipline —
**§4005.101(b)(10)** and **(11)**, below.

## Temporary licences

**§4001.151** — the Department may issue a **temporary agent's licence** to an
applicant who **is being considered for appointment** by an agent, an insurer
or an HMO.

The features, each its own likely question:

- **§4001.152 — no written examination is required.** This is the point of a
  temporary licence: it lets somebody start while they prepare for the exam.
- **§4001.153(a)** — the Department **shall issue it immediately** on receipt
  of a properly completed application, the non-refundable filing fee, and a
  certificate signed by the prospective appointing agent, insurer or HMO.
- **§4001.153(b)** — it may be denied on any ground for denial or discipline
  under §4005.101 or Chapter 53, Occupations Code.
- **§4001.154** — **if the temporary licence has not arrived by the eighth day**
  after the application, fee and certificate were delivered or mailed, and no
  denial has been notified, the appointing agent or insurer **may assume the
  licence will be issued**.
- **§4001.155 — a temporary licence is valid for 180 days** after issuance.
- **§4001.156(b)** — it may **not** be issued to somebody who does not intend
  to apply for a licence to sell to the general public. The same principle as
  §4001.104.

> **One caution on "not renewable".** The Pearson VUE candidate handbook
> describes the temporary licence as 180 days and not renewable. The section
> headed "RESTRICTION ON ISSUANCE OR RENEWAL OF TEMPORARY LICENSE" had
> **subsection (a) repealed** effective 1 September 2021 (H.B. 2819 and
> H.B. 4030), leaving only the issuance restriction in (b). **Answer 180 days
> with confidence; treat "not renewable" as what the handbook says rather
> than as something this course has confirmed in the current statute.**

### Commissions a temporary licence holder may not take

**§4001.157** closes the obvious loophole — a temporary licence needs no exam,
so without this it would be a fast route to controlled business.

**§4001.157(a)** — a temporary licence holder **may not obtain a commission on
a sale to a person who has a family, employment or business relationship with
them.**

**§4001.157(b)** — neither an agent, insurer nor HMO may knowingly pay, and
the temporary licence holder may not accept, a commission on a contract
covering:

1. **the temporary licence holder** themselves;
2. a person **related by consanguinity or affinity** (blood or marriage);
3. a person who **is, or has been within the past six months**, their
   employer; or
4. certain further related persons.

**The six-month look-back on a former employer** is the detail most likely to
be asked.

## Duties while licensed

**§4001.252(a)** — an individual licensed as an agent shall notify the
Department **on a monthly basis** of:

1. **a change of mailing address**;
2. **a felony conviction**; and
3. **an administrative action taken against them** by a financial or insurance
   regulator of Texas, another state, or the United States.

Three things worth noting. The obligation is **monthly**, not immediate. It
covers **any state's** regulator, not just Texas — which connects directly to
§82.056, under which Texas notifies other states of its own actions. And a
**felony conviction** must be reported whether or not it involved insurance.

**§4001.252(b)** — a licensed corporation or partnership must file sworn
biographical information for its executive officers, directors, unlicensed
administering partners, controlling shareholders, and the individuals
controlling any parent entity.

**§4001.255 — an agent shall maintain all insurance records, including
records relating to customer complaints, separate from the records of any
other business** the agent is engaged in.

That last one sounds administrative and is not. An agent who also sells real
estate or prepares taxes must keep the insurance files apart, so that the
Department can examine them without reaching into an unrelated business — and
so that premium money is traceable.

## Licence types named by the blueprint

The blueprint lists these under TX.I.C.1. Chapters **4001** and **4051** cover
agent and agency licensing and property and casualty agents respectively, and
are the basis of this lesson.

The remaining types — **non-resident** (Ch. 4056), **managing general agent**
(28 TAC §19.1201–.1206), **surplus lines** (§981.202), **adjuster**
(Ch. 4101), **risk manager** (Ch. 4153), **limited** (§4051.101) and
**emergency** (§4051.054) licences — are named here so you know they are
examined. **Their specifics are not taught in this course yet**, because the
chapters have not been obtained. See `docs/module-5-source-gaps.md`.

## How this is examined

**A licence is not enough — an appointment is required** before acting.

**30 days** to notify an additional appointment.

**Controlled business**: insuring your own property is permitted; being
licensed principally to handle controlled business is not.

**Temporary licence: no exam, 180 days, issued immediately, 8-day
assumption.**

**The six-month former-employer commission bar** on temporary licence
holders.

**Monthly notification** of address change, felony conviction and
administrative action.

**Records kept separate** from any other business.

## Check yourself

1. A newly licensed agent has not yet been appointed by any insurer. May they
   write business?
2. An agent takes on a second insurer. By when must the Department be told?
3. An applicant wants a licence mainly to write insurance on buildings they
   own and on their brother's business. Permitted?
4. Does a temporary licence holder have to pass the examination first?
5. A temporary licence holder sells a policy to somebody who employed them
   four months ago. May they take the commission?
6. An agent is convicted of a felony unrelated to insurance. Must the
   Department be told?
7. An agent also runs a tax practice. What does §4001.255 require?

## Answers

1. **No.** §4001.201 requires an appointment by an authorised insurer before
   engaging in business as an agent.
2. **Not later than the 30th day** after the effective date of the
   appointment — §4001.202(b).
3. **No.** §4001.104 bars licensing somebody principally to handle business
   they control through ownership or family relationship. Insuring their own
   property is fine; being licensed *for* that is not.
4. **No** — §4001.152 requires no written examination for a temporary
   licence.
5. **No.** §4001.157(b)(3) bars a commission where the person is, or has been
   **within the past six months**, the licence holder's employer.
6. **Yes** — §4001.252(a)(2), on a monthly basis, whatever the felony was.
7. That all insurance records, **including customer complaint records**, be
   kept **separate** from the records of the other business.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'f55672f5-bcf6-53e5-90d9-cfcecc6ae951', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '15b0bfa2-b658-5f96-932e-319ed4c30f1d', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Licence Renewal and Discipline',
       'licence-renewal-and-discipline', 'The two-year term, the 90-day and one-year cliffs after expiry, and the eleven grounds for losing a licence.', 4,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '15b0bfa2-b658-5f96-932e-319ed4c30f1d', c.id, $lesson$# Keeping the licence, and losing it

## Expiration

**§4003.001(a)** — a licence expires on **the second anniversary** of the date
it was issued or renewed, for a licence holder that is **not an individual**.
For an **individual**, expiry is tied to the licence holder's birthday, in an
even- or odd-numbered year according to when the licence was issued or
renewed.

Either way the period is **two years**. **§4003.001(b)** lets the
Commissioner change that by rule to keep Texas licence periods uniform with
other states.

## Renewing on time

**§4003.004(a)** — renew an **unexpired** licence by filing a completed
renewal application and paying the renewal fee.

**§4003.004(b)** — **a licence that has been suspended or revoked may not be
renewed.**

**§4003.006** — once a renewal application has been properly filed, **the
original licence remains in effect** until the Department issues the renewal,
or the licence is not renewed for want of continuing education, or the
Commissioner revokes it. So a producer who applies on time does not go
unlicensed while the Department processes the paperwork.

## Renewing late — the two cliffs

This is the most tested part of the chapter. **§4003.007** sets three bands.

| Expired for | What is possible | Cost |
| --- | --- | --- |
| **90 days or less** | **Renew** normally | Renewal fee **plus one-half** of it |
| **More than 90 days, less than one year** | **Cannot renew.** May obtain a **new licence without re-examination** | Licence fee **plus one-half** of it |
| **One year or more** | **Cannot renew.** Must obtain a new licence, **submitting to re-examination** and meeting all original-licence requirements | Original licence process |

Two cliffs, then: **90 days** ends the right to renew, and **one year** ends
the exemption from re-examination.

The word to watch in a question is **"renew"**. Between 90 days and a year
the licence cannot be renewed at all — a *new* licence is issued, which
happens to spare the applicant the exam. Candidates who read that band as
"renew with a bigger fee" get it wrong.

**§4003.008** — an agent who was licensed in Texas, **moved to another
state**, and is currently licensed and has been in continual practice there,
may have an expired Texas licence **renewed without re-examination** on paying
a fee equal to the licence application fee.

## Continuing education

Continuing education is a condition of renewal — **§4003.006(2)** refers to a
licence not being renewed under **§4004.055**.

**Chapter 4004 sets the requirement, and this course does not yet teach its
figures**, because the chapter has not been obtained. See
`docs/module-5-source-gaps.md`. Do not learn CE hours from this course; get
them from the statute or from TDI.

## Grounds for denial or discipline

**§4005.101(b)** lists eleven. The Department may deny an application or
discipline a licence holder — individually or **through an officer, director
or shareholder** — where the person:

1. has **wilfully violated** an insurance law of this state;
2. has **intentionally made a material misstatement** in the licence
   application;
3. has **obtained or attempted to obtain a licence by fraud or
   misrepresentation**;
4. has **misappropriated, converted or illegally withheld money** belonging to
   an insurer, an HMO, or an insured, enrollee or beneficiary;
5. has engaged in **fraudulent or dishonest acts or practices**;
6. has **materially misrepresented the terms or conditions** of a policy or
   contract;
7. has made a statement **misrepresenting or making incomplete comparisons**
   of a contract to induce the owner to forfeit, surrender or lapse it in
   order to **replace** it — that is, **twisting**;
8. has been **convicted of a felony**;
9. has **offered or given a rebate** of premium or commission;
10. is **not actively engaged in soliciting or writing insurance for the
    public generally**, as §4001.104(a) requires; or
11. has obtained or attempted to obtain a licence **primarily to cover
    themselves or their relatives** rather than to hold themselves out to the
    general public — controlled business again.

Notice the pattern. Grounds 1–3 are about **how the licence was obtained**,
4–7 and 9 about **how the producer behaves**, 8 about **character**, and
10–11 about **controlled business**. Two of the eleven — a third of the
substance — exist to enforce §4001.104.

Note also the phrase **"individually or through an officer, director, or
shareholder"**: an agency cannot escape discipline by pointing at the
individual who did it.

## What the Department may do

**§4005.102** — in addition to any remedy under Chapter 82, the Department
may:

1. **deny** an application for an original licence;
2. **suspend, revoke, or deny renewal** of a licence;
3. **place on probation** a person whose licence has been suspended;
4. **assess an administrative penalty**;
5. **reprimand** a licence holder; or
6. require a licence holder to **qualify or re-qualify** for a product-line
   certificate under Chapter 4008.

The range matters: **the Department is not limited to revocation.** A
reprimand, a penalty and probation are all available, which is why a question
offering "the Commissioner must revoke the licence" is usually wrong.

**§4005.103** — where a suspension is **probated**, the Commissioner may
require the licence holder to report regularly to the Department, to limit
their practice to prescribed areas, or to **continue professional education**
until their skill is satisfactory.

## How this is examined

**Two-year term**, and that a suspended or revoked licence cannot be renewed.

**The 90-day and one-year cliffs**, and that between them the licence is
*replaced*, not renewed — without an exam.

**One year or more expired means re-examination.**

**The original licence continues** while a timely renewal is pending.

**Twisting** as ground (7), and **felony conviction** as ground (8).

**Probation, reprimand and penalty** exist alongside revocation.

## Check yourself

1. How long does an agent licence run?
2. An agent's licence expired 60 days ago. What must they do?
3. An agent's licence expired seven months ago. Can they renew it? Must they
   re-sit the exam?
4. An agent's licence expired 14 months ago. What now?
5. An agent files a timely renewal application and the Department is slow. Is
   the agent unlicensed in the meantime?
6. A producer persuades a client to surrender a policy and replace it, using
   an incomplete comparison. Which ground, and what is the practice called?
7. May the Commissioner respond to a violation with anything short of
   revocation?

## Answers

1. **Two years** — §4003.001(a), to the second anniversary for a
   non-individual, and on a birthday cycle for an individual.
2. **Renew normally** — within 90 days the licence may still be renewed, on
   payment of the renewal fee **plus one-half** of it (§4003.007(a)).
3. **No, they cannot renew.** Between 90 days and one year they may obtain a
   **new licence without re-examination**, paying the licence fee plus half
   (§4003.007(b)).
4. **A new licence with re-examination**, meeting all the requirements for an
   original licence — §4003.007(c).
5. **No.** §4003.006 keeps the original licence in effect until the renewal
   issues.
6. **§4005.101(b)(7)**, and the practice is **twisting**.
7. **Yes** — §4005.102 allows denial of renewal, suspension, probation, an
   administrative penalty, a reprimand, or re-qualification.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '15b0bfa2-b658-5f96-932e-319ed4c30f1d', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.I'
on conflict (lesson_id, topic_id) do nothing;

commit;
