-- Texas Exam Prep — content seed, chunk 18 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6aea89e0-bdfe-572e-9221-7381c152533c', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Declination, Cancellation and Non-renewal',
       'declination-cancellation-and-nonrenewal', 'Chapter 551''s notice periods, the grounds an insurer is limited to, and the different rules for commercial and personal lines.', 7,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6aea89e0-bdfe-572e-9221-7381c152533c', c.id, $lesson$# When a Texas insurer may walk away

Module 2 gave the general pattern — 10 days for non-payment, 30 for other
reasons, 30 for non-renewal. **Texas sets its own numbers, and they are not
those.** Chapter 551 is what a Texas question is testing.

The chapter splits by line of business, and the two halves have different
rules. Read the question for which one it is.

| | Subchapter B | Subchapter C |
| --- | --- | --- |
| Covers | **Liability and commercial property** | **Personal auto, homeowners, farm/ranch owners, standard fire on a dwelling or duplex, and government property/casualty** |
| Cancellation notice | **10 days** | **10 days** |
| Non-renewal notice | **60 days** | **60 days** |

## What counts as a cancellation

**§551.103** — for the personal lines subchapter, an insurer has cancelled a
policy if, **without the insured's consent**, it:

1. **terminates coverage**;
2. **refuses to provide additional coverage** the insured is entitled to; or
3. **reduces or restricts coverage by endorsement or other means**.

**Point 3 is the one that catches people.** Quietly narrowing a policy
mid-term is a cancellation and carries the cancellation rules with it.

**§551.004** — **transferring a policy** to another insurer within the same
group **is not** a refusal to renew.

## Commercial and liability lines — Subchapter B

### The rule against mid-term cancellation

**§551.052(a)** — an insurer **may not cancel** a liability or commercial
property policy **that is a renewal or continuation policy**. Once it has been
renewed once, it is cancellable only on the grounds below.

**§551.052(b)** — during the **initial policy term**, an insurer may not
cancel **after the 60th day** following issuance. So there is a 60-day
underwriting window and then the door closes.

### The four grounds that survive

**§551.052(c)** — notwithstanding either rule above, the insurer may cancel
**at any time** for:

1. **fraud in obtaining coverage**;
2. **failure to pay premiums when due**;
3. **an increase in hazard within the control of the insured** that would
   produce a rate increase; or
4. **loss of the insurer's reinsurance** covering all or part of the risk.

**§551.052(d)** adds a fifth: where the insurer is placed in **supervision,
conservatorship or receivership** and the cancellation is approved or directed
by the supervisor, conservator or receiver.

### Notice

**§551.053 — not later than the 10th day before** the cancellation takes
effect, written notice must be delivered or mailed **to the first-named
insured at the address shown on the policy**.

**§551.054(a)–(b)** — non-renewal requires written notice to the first-named
insured **not later than the 60th day before the policy expires**. And there
is a consequence for missing it: **if the notice goes out later than that, the
coverage remains in effect until the 61st day after the notice is delivered or
mailed.** Late notice does not void the non-renewal; it postpones it.

**§551.054(c)** — earned premium for the extended period is computed **pro
rata based on the previous year's rate.**

**§551.055** — a notice to a policyholder must **state the reason** for the
declination, cancellation or non-renewal.

## Personal lines — Subchapter C

**§551.102** lists what this subchapter covers: a **personal automobile**
policy (other than one written through **TAIPA**), a **homeowners or farm or
ranch owners** policy, a **standard fire** policy on a one-family dwelling or
duplex or their contents, and property and casualty coverage for **the state
and its political subdivisions**.

### When an insurer may cancel

**§551.104(a)** — an insurer may cancel **only as provided by this section**.
That is the frame: the grounds are a closed list.

**§551.104(b) — any policy**, for:

1. **non-payment** of any portion of the premium when due;
2. **a fraudulent claim** submitted by the insured; or
3. the **Department determining** that continuing the policy would violate the
   code or another insurance law.

**§551.104(c) — any policy other than personal auto**, for an **increase in
hazard within the insured's control** that would raise the rate.

**§551.104(d) — personal auto only**, where the **driver's licence or vehicle
registration** of the named insured, or of any operator resident in the same
household or who customarily drives a covered auto, is **suspended or
revoked**. But the insurer **may not** cancel on this ground **if the named
insured consents to an endorsement excluding that person.**

**§551.104(e) — cancellation under (b), (c) or (d) does not take effect until
the 10th day after the insurer mails notice.**

### The new-business windows

**§551.104(g)** sets three different periods, and the exam separates them:

| Policy | May cancel if in effect less than |
| --- | --- |
| Any policy other than personal auto or homeowners | **90 days** |
| **Personal automobile** | **60 days** |
| **Homeowners** | **60 days**, and only on the two further conditions below |

For **homeowners** within that 60 days, the insurer must also either:

1. **identify a condition** that creates an increased risk of hazard, **was
   not disclosed in the application**, and **is not the subject of a prior
   claim**; or
2. before the effective date, **not accept** a required **inspection report**
   completed by an inspector licensed by the Texas Real Estate Commission or
   otherwise authorised, and **dated not earlier than the 90th day** before
   the policy's effective date.

**§551.104(h)** — an inspection report is **considered accepted if the insurer
does not reject it before the 11th day** after receiving it. Silence is
acceptance.

### The 12-month anniversary rule

**§551.104(f)** — an insurer may cancel a **personal automobile** policy
effective on **any 12-month anniversary** of the original effective date, if
it mails written notice **not later than the 60th day before** the
cancellation takes effect.

This is the escape hatch: outside the 60-day new-business window and the
listed grounds, a personal auto policy can only be ended at an anniversary, on
60 days' notice.

### Non-renewal

**§551.105** — **unless the insurer has mailed written notice of non-renewal**
(or of renewal with a change in coverage under §2002.001) **not later than the
60th day before the policy expires, the insurer must renew the policy at the
insured's request.**

The default runs the other way from most states: **silence means renewal.**

**§551.1041** — the Commissioner must adopt rules requiring an insurer that
cancels comprehensive or collision coverage on a vehicle **subject to a
purchase money lien** to notify the **lienholder**, if known.

## Reasons, records and consequences

**§551.002** — the Commissioner **shall require** an insurer that declines,
cancels or refuses to renew to give a **written statement of the reasons**.
The statement must **fully explain** the adverse decision, **state the precise
incident, circumstance or risk factors** that violate the insurer's
guidelines, and **state the source of the information** relied on.

**§551.003 and §551.110** — an insurer, agent or employee is **immune from
liability** for statements made in good faith in giving those reasons. Without
it, no insurer would give a candid reason.

**§551.108** — insurers must maintain records.

**§551.111** — **a cancellation made in violation of this subchapter is
ineffective.** The policy stays in force.

**§551.113** — declination, non-renewal or cancellation is **prohibited** on
certain grounds relating to the **consideration of consumer information** —
the Texas counterpart to the FCRA material in Module 2.

**§551.152** — an insurer **may not cancel or refuse to renew** a policy
because the insured is an **elected official**.

> **Recent amendments.** H.B. 2067 (89th Legislature, 2025) took effect
> **1 January 2026** and added **§551.007** (a commercial-lines declination
> notice goes to the applicant's **agent**, who must then disclose it to the
> applicant), **§551.008** (electronic delivery of these notices) and
> **§551.0521** (written notice of declination for liability and commercial
> property). They are in force for an exam taken under the September 2026
> outline, and material written before 2026 does not contain them.

## How this is examined

**10 days for cancellation, 60 days for non-renewal** — the Texas numbers, not
the generic 10/30/30.

**Late non-renewal notice extends coverage to the 61st day after it is sent.**

**Silence means renewal** under §551.105.

**The 60/60/90-day new-business windows**, and which line gets which.

**Suspended licence** as a personal auto ground — and the endorsement that
defeats it.

**A cancellation in violation of the subchapter is ineffective.**

**Reducing coverage by endorsement is a cancellation.**

## Check yourself

1. A commercial property policy is in its first term, issued 100 days ago. The
   underwriter wants out because the risk looks worse than expected. May the
   insurer cancel?
2. Same policy, but the insured has not paid the premium. May the insurer
   cancel, and with how much notice?
3. A homeowners insurer mails non-renewal notice 30 days before expiry. What
   happens?
4. A personal auto policy has been in force 8 months. The named insured's son,
   who lives at home, has his licence revoked. What are the insurer's options?
5. A homeowners policy is 40 days old. The insurer received an inspection
   report 20 days ago and said nothing. May it now cancel relying on that
   report?
6. An insurer cancels a homeowners policy on a ground not listed in §551.104.
   What is the effect?

## Answers

1. **No.** §551.052(b) bars cancellation after the **60th day** of the initial
   term, and second thoughts about the risk is not one of the §551.052(c)
   grounds.
2. **Yes** — failure to pay premium is a §551.052(c) ground, available at any
   time, with **10 days'** written notice under §551.053.
3. Notice was late, so under **§551.054(b)** the coverage **remains in effect
   until the 61st day after the notice was delivered or mailed**. Earned
   premium for the extension is pro rata at the previous year's rate.
4. Cancel under **§551.104(d)**, on **10 days'** notice — **unless the named
   insured consents to an endorsement terminating coverage for the son**, in
   which case the insurer may not cancel on that ground.
5. **No.** Under §551.104(h) the report is **considered accepted** because the
   insurer did not reject it before the 11th day after receiving it.
6. **The cancellation is ineffective** — §551.111. The policy remains in
   force.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6aea89e0-bdfe-572e-9221-7381c152533c', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'd2d75fa2-1270-52a0-ae05-a23ebb7d15c9', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Surplus Lines',
       'surplus-lines', 'Placing business with an insurer Texas has not authorised — the diligent effort, the separate licence, and the warning that must appear on the document.', 8,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'd2d75fa2-1270-52a0-ae05-a23ebb7d15c9', c.id, $lesson$# Buying from an insurer the state has not licensed

Some risks no admitted insurer will write. Surplus lines is the regulated
route to an unauthorised insurer for those risks — regulated, but much more
lightly, and the difference is the point of the whole chapter.

## Why the chapter exists

**§981.001(b)** lists six purposes, and reading them tells you what the
regulator is balancing:

1. requiring standards and reports on placement;
2. making regulation reasonably complete and effective;
3. providing **orderly access** to eligible surplus lines insurers;
4. ensuring **fair and honest markets**;
5. **protecting the revenues of this state** — the premium tax; and
6. **protecting authorized insurers from unfair competition by unauthorized
   insurers.**

Purpose (6) is the one candidates miss. Surplus lines exists to fill a gap,
**not** to let anybody escape the rules that admitted insurers must meet.
Everything else in the chapter follows from keeping that gap narrow.

**§981.003** — the chapter applies where the **home state of the insured is
Texas**.

## The three conditions for a placement

**§981.004(a)** — an eligible surplus lines insurer may provide the coverage
**only if**:

1. **the full amount of required insurance cannot be obtained, after a
   diligent effort**, from an insurer **authorized to write and actually
   writing** that kind and class of insurance in Texas;
2. **the insurance is placed through a surplus lines agent**; and
3. the insurer **meets the eligibility requirements** as of the inception date
   and each annual anniversary.

**§981.004(b)** — the surplus lines insurer may provide coverage **only in the
amount that exceeds** what is obtainable from authorized insurers. It tops up;
it does not replace.

### The diligent effort

This is the heart of it, and the most examined phrase in the chapter.

Two qualifiers in condition (1) do real work. The authorized insurer must be
**authorized to write** that class **and actually writing** it. An insurer
that holds the authority but has stopped writing the class does not count as
an available market.

**Declinations from the admitted market are what evidence the diligent
effort**, and §981.215–.216 require the agent to keep records and report.

### The exempt commercial purchaser exception

**§981.004(c)** — the diligent effort requirement **does not apply** to
insurance procured for an **exempt commercial purchaser**, provided the agent:

1. **discloses** that comparable insurance may be available from the admitted
   market, which is subject to **more regulatory oversight**, and that an
   admitted policy **may provide greater protection**; and
2. receives the purchaser's **written request** to place it in the surplus
   lines market anyway.

The logic: a large, sophisticated commercial buyer can weigh the trade-off
themselves, provided it is spelled out in writing.

## The agent needs a separate licence

**§981.202** — **an agent licensed by Texas may not issue, or cause to be
issued, a contract with an eligible surplus lines insurer unless the agent
holds a surplus lines licence issued by the Department.**

A general lines licence is not enough. This is the single most likely
licensing question on the topic.

## Who qualifies as an eligible surplus lines insurer

**§981.057(a)** — an eligible surplus lines insurer must maintain **capital
and surplus of at least $15 million**.

**§981.057(b)** — that does not apply to **alien** surplus lines insurers
listed on the **Quarterly Listing of Alien Insurers** maintained by the NAIC's
International Insurers Department.

**§981.210** — an agent may not place coverage with an insurer unless it meets
the chapter's requirements, and **§981.211** obliges the agent to attend to
the insurer's financial condition.

## What must appear on the document

**§981.101** is where the consumer protection actually lives, and it is
protection by **warning** rather than by supervision.

**§981.101(b)** — the document must state, **in 11-point type**, that:

- the contract is **with an insurer not licensed to transact insurance in this
  state**, issued as surplus line coverage;
- **the Texas Department of Insurance does not audit the finances or review
  the solvency** of that insurer;
- **the insurer is not a member of the property and casualty insurance
  guaranty association** created under Chapter 462; and
- **Chapter 225 requires payment of a stated percentage tax on gross
  premium.**

**The guaranty association point is the one to carry.** If a surplus lines
insurer fails, **there is no guaranty fund behind the policy.** That is the
real price of the wider market, and it is a reliable exam answer.

**§981.101(c)** — the document must also show the **description and location**
of the subject insured; the **coverage, conditions and term**; the **premium
and rate** and the **premium taxes** to be collected from the insured; the
**name and address** of the insured, the insurer and the agent; and, where
more than one insurer takes the risk, **each insurer's name and the proportion
assumed**.

**§981.101(d)** — where a contract covers a risk **located wholly in Texas**
and contains an **arbitration agreement**, the arbitration must be **conducted
in Texas and governed by Texas law**, and the contract interpreted under Texas
law — unless both agree to a different venue after written notice **and the
insurer gives a premium credit** for the policyholder's resulting costs.
**§981.101(e)** lets the parties agree otherwise by mutual consent where the
insured value exceeds **$2 million**. (S.B. 455, effective 1 September 2025.)

**§981.102** — a surplus lines policy form is limited in its use, and
**§981.103–.104** require the documents, and any revised documents, to be
**delivered to the insured**.

## Filing and tax

**§981.105(a)** — **not later than the 60th day** after the later of the
effective date or the issue date of new or renewal surplus lines insurance,
the responsible agent must **file with the stamping office** a copy of the
policy, or of the certificate, cover note or confirmation delivered to the
insured.

**§981.214** — the agent must comply with the **stamping office's plan of
operation**.

**Chapter 225** imposes the **premium tax on gross premium**, which the agent
collects from the insured and remits. The rate is stated on the document
itself under §981.101(b).

**§981.215** — the agent must keep records; **§981.216** requires an annual
report.

## How this is examined

**The diligent effort** — and that the admitted insurer must be both
authorized **and actually writing** the class.

**A separate surplus lines licence** is required.

**No guaranty association protection** behind a surplus lines policy.

**$15 million** minimum capital and surplus, with the alien-insurer
exception.

**60 days** to file with the stamping office.

**The exempt commercial purchaser** may waive the diligent effort, in writing,
after disclosure.

**Surplus lines covers only the excess** over what the admitted market will
write.

## Check yourself

1. A general lines agent finds an admitted market will write only $2m of a
   $5m exposure. What may they place in surplus lines, and what licence do
   they need?
2. An admitted insurer holds authority for the class but stopped writing it
   two years ago. Does it count for the diligent effort?
3. A surplus lines insurer becomes insolvent. Does the Texas guaranty
   association pay the claim?
4. What is the minimum capital and surplus for an eligible surplus lines
   insurer, and who is exempt?
5. By when must the agent file the policy with the stamping office?
6. A large manufacturer wants a surplus lines placement without the agent
   canvassing the admitted market. Possible?

## Answers

1. Only the **$3m that exceeds** what the admitted market will write —
   §981.004(b). They need a **surplus lines licence** in addition to their
   general lines licence — §981.202.
2. **No.** §981.004(a)(1) requires an insurer **authorized to write and
   actually writing** that kind and class.
3. **No.** §981.101(b) requires the document to state that the insurer **is
   not a member of the guaranty association** created under Chapter 462.
4. **$15 million** — §981.057(a). **Alien** insurers on the NAIC
   International Insurers Department's Quarterly Listing are exempt.
5. **Not later than the 60th day** after the later of the effective or issue
   date — §981.105(a).
6. **Yes, if it is an exempt commercial purchaser** — §981.004(c) — after the
   agent discloses that the admitted market has more oversight and may offer
   greater protection, and the purchaser **requests the placement in
   writing**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'd2d75fa2-1270-52a0-ae05-a23ebb7d15c9', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
