-- Texas Exam Prep — content seed, chunk 19 of 19
--
-- GENERATED by scripts/import-content.mjs — do not edit by hand.
--
-- The whole seed is supabase/seed_content.sql. It is far too large to
-- paste into the Supabase SQL editor, so it is also split into these
-- chunks. Run them IN ORDER, after supabase/seed.sql.
--
-- These ARE safe to re-run: every insert carries an "on conflict"
-- clause. If you lose track, re-running a chunk changes nothing.

begin;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '78028eb3-4532-507a-92dd-92c431ad7184', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Texas Auto — Uninsured Motorists and PIP',
       'texas-auto-um-uim-and-pip', 'Two coverages Texas requires every auto insurer to offer, the written rejection that removes them, and the $2,500 and $250 figures.', 9,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '78028eb3-4532-507a-92dd-92c431ad7184', c.id, $lesson$# Two coverages the insurer must offer and the insured may refuse

Texas does not compel a driver to buy uninsured motorist coverage or personal
injury protection. **It compels the insurer to include them unless the named
insured rejects them in writing.** That structure — mandatory offer, written
rejection — is the single most examined thing in Chapter 1952.

## Uninsured and underinsured motorists

### The mandatory offer

**§1952.101(b)** — an insurer **may not deliver or issue for delivery** in
Texas an automobile liability policy — **including a policy provided through
the Texas Automobile Insurance Plan Association** — unless it **provides
uninsured or underinsured motorist coverage in the policy or supplemental to
it**.

**§1952.101(c)** — the requirement **does not apply if any insured named in
the policy rejects the coverage in writing.**

Read that carefully. **"Any insured named in the policy"** — one named
insured's written rejection is enough.

And the rejection carries forward: unless the named insured later **requests
the coverage in writing**, the insurer need not provide it on a **reinstated
or renewal** policy where the coverage was rejected on that policy, or on a
policy previously issued **by the same insurer or an affiliated insurer**.

**Three things must be true for UM to be absent: the rejection was by a named
insured, it was in writing, and nothing since has requested it back in
writing.** A question describing an oral rejection, or a rejection by somebody
who is not a named insured, is testing exactly this.

### What counts as uninsured

**§1952.101(a)** — the coverage protects insureds **legally entitled to
recover** from owners or operators of uninsured or underinsured vehicles, for
**bodily injury, sickness, disease or death, or property damage**, in at least
the limits prescribed by **Chapter 601, Transportation Code**.

**"Legally entitled to recover" is the qualifier from Module 4**: the other
driver must be at fault. UM is not no-fault coverage.

**§1952.102(a)** — **"uninsured motor vehicle" includes an insured vehicle
whose liability insurer is unable, because of insolvency, to pay** within its
limits. An insolvent insurer on the other side turns the claim into a UM
claim.

**§1952.103** — an **"underinsured motor vehicle"** is one carrying
collectible liability coverage whose limits were **originally lower than**, or
**have been reduced by payment of claims arising from the same accident to**,
an amount less than the insured's own UIM limit.

That second branch matters: a policy with adequate limits can become
underinsured **during the same accident**, once other claimants have drawn it
down.

### Limits

**§1952.105(a)** — bodily injury limits must be offered **in the amounts the
insured desires**, but **not greater than the bodily injury liability limits
of the insured's own policy.**

**§1952.105(b)** — **property damage UM coverage is subject to a $250
deductible**, and again may not exceed the policy's own property damage
liability limits.

**§1952.105(c)** — neither may be offered **in amounts less than those
prescribed by Chapter 601, Transportation Code.**

**The $250 UM property damage deductible is a reliable exam number.** Note
that it applies to property damage only — there is no deductible on UM bodily
injury.

### Aggregate limits

**§1952.104(1)** — whatever the number of insureds, policies, vehicles or
claims, **the total aggregate limit to any one person for a single occurrence
may not exceed the policy's stated limit**, and the total to all claimants may
not exceed the per-occurrence limit.

This is the anti-stacking provision within a single policy.

## Personal injury protection

### What it pays

**§1952.151** — PIP provides payment to **the named insured, members of the
insured's household, and any authorized operator or passenger of the named
insured's vehicle, including a guest occupant**, of all reasonable expenses
that:

1. **arise from an accident**;
2. **are incurred not later than the third anniversary** of the accident; and
3. are for **necessary medical, surgical, x-ray or dental services**,
   including prosthetic devices, and **necessary ambulance, hospital,
   professional nursing or funeral services**; or, **for an income producer,
   replacement of lost income**.

Three features distinguish it from the medical payments coverage in Module 4:
it covers **guest occupants**, it runs for **three years**, and it pays **lost
income**, not only medical bills.

### The mandatory offer, again

**§1952.152(a)–(b)** uses **exactly the same structure** as UM: the insurer
must provide PIP in or supplemental to the policy — TAIPA policies included —
**unless any named insured rejects it in writing**, with the same carry-forward
to reinstated and renewal policies and the same written-request route back.

### The $2,500 figure

**§1952.153** — the subchapter **does not require** an insurer to provide PIP
**in an amount exceeding $2,500 for all benefits, in the aggregate, for each
person.**

Note the shape: **$2,500 is the maximum an insurer can be compelled to
offer**, not a cap on what may be bought. Higher limits are available; the
statute simply does not require them.

**§1952.154** — an insurer paying **loss of income** benefits may require
**reasonable medical proof** of the injury causing the loss.

### No fault, no collateral source, no subrogation

**§1952.155(a)** — PIP benefits are payable **without regard to**:

1. **the fault or non-fault** of the named insured or recipient; and
2. **any collateral source** of medical, hospital or wage continuation
   benefits.

So PIP pays even where the insured caused the crash, and pays **on top of**
health insurance rather than behind it.

**§1952.155(b)** — an insurer paying PIP **has no right of subrogation** and
no claim against another person or insurer to recover those benefits by reason
of the other's fault.

**§1952.155(c)** is the exception, and it is a pointed one: the insurer
**does** have subrogation and a claim against a person causing or contributing
to the collision **if, on the date of loss, that person had not established
financial responsibility as required by Chapter 601, Transportation Code.**

**An uninsured driver gets no protection from the no-subrogation rule.** That
is the clearest single contrast in the subchapter, and a likely question.

## What is not taught here

The blueprint also cites, under TX.II.E:

- **Transportation Code Chapter 601** — financial responsibility and the
  **required minimum liability limits**. Chapters 1952.101 and 1952.105 both
  defer to it for the floor, and **this course does not state those figures**
  because the Transportation Code has not been obtained.
- **TIC Chapter 2151** — the Texas Automobile Insurance Plan Association, the
  auto residual market.
- **TIC Chapter 1954** — transportation network companies (rideshare).
- **28 TAC §5.204** and **§5.7002** — auto coverage, and renewal, non-renewal
  and cancellation rules.

See `docs/module-5-source-gaps.md`. **Do not learn the Texas minimum liability
limits from this course** — get them from Chapter 601.

## How this is examined

**Mandatory offer, rejection in writing by a named insured** — for both UM and
PIP.

**The rejection carries forward** to renewals and to affiliated insurers until
the insured asks in writing.

**$250 deductible** on UM **property damage** only.

**$2,500** is the most PIP an insurer must offer, per person, in aggregate.

**PIP pays regardless of fault and regardless of other coverage**, and covers
guest occupants and lost income, for **three years**.

**No PIP subrogation — except against a driver without financial
responsibility.**

**An insolvent liability insurer makes the other vehicle "uninsured".**

## Check yourself

1. A Texas insurer issues an auto policy with no UM coverage and no paperwork
   about it. Is that permitted?
2. One of two named insureds signs a written UM rejection. Is the coverage
   removed?
3. The policy renews the following year. Must the insurer offer UM again?
4. The insured's UM property damage claim is $4,000. What is paid, before
   limits?
5. An insured causes a crash and is injured, and has health insurance. Does
   PIP pay?
6. A passenger in the insured's car — a friend, not a household member — is
   injured. Does PIP cover them?
7. The at-fault driver had no insurance at all. May the PIP insurer recover
   what it paid from them?
8. The at-fault driver's insurer is insolvent. Which coverage responds?

## Answers

1. **No.** §1952.101(b) requires the coverage unless a named insured
   **rejected it in writing** — the rejection must exist.
2. **Yes.** §1952.101(c) says the requirement does not apply if **any insured
   named in the policy** rejects it in writing.
3. **No** — the rejection carries forward to a reinstated or renewal policy,
   and to a policy from the same or an affiliated insurer, **unless the named
   insured requests the coverage in writing.**
4. **$3,750** — UM property damage is subject to a **$250 deductible** under
   §1952.105(b).
5. **Yes.** §1952.155(a) — payable without regard to fault and without regard
   to any collateral source.
6. **Yes.** §1952.151 covers **any authorized operator or passenger of the
   named insured's vehicle, including a guest occupant.**
7. **Yes.** §1952.155(c) — the no-subrogation rule does **not** protect a
   person who had not established financial responsibility under Chapter 601.
8. **Uninsured motorist.** §1952.102(a) treats a vehicle whose liability
   insurer cannot pay because of insolvency as uninsured.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '78028eb3-4532-507a-92dd-92c431ad7184', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'f2f83e58-1313-5d36-b18f-242354a7ab5c', '62edc60d-a12f-5d1f-80b7-2adce32c4394', c.id, 'Windstorm and the FAIR Plan',
       'windstorm-and-the-fair-plan', 'Texas''s two residual property markets — who each one covers, the declination counts, and the limits.', 10,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'f2f83e58-1313-5d36-b18f-242354a7ab5c', c.id, $lesson$# Two markets of last resort, and the line between them

Module 3 gave the general idea: where a catastrophe exposure is concentrated,
the private market withdraws and a state-created residual market fills the
gap. Texas has **two**, and the exam's favourite question is which one applies.

**§2211.156 draws the line in a single sentence: the FAIR Plan may not provide
windstorm and hail coverage for a risk eligible for that coverage under
Chapter 2210.**

So: **wind and hail on the coast is TWIA. Everything else that the voluntary
market will not write is the FAIR Plan.** They do not overlap.

| | **TWIA** (Ch. 2210) | **FAIR Plan** (Ch. 2211) |
| --- | --- | --- |
| Covers | **Windstorm and hail** | **Residential property**, generally |
| Where | The **seacoast territory** | **Underserved areas**, designated by rule |
| Declinations needed | **One** | **Two** |
| Excluded | — | **Wind/hail eligible under Ch. 2210** |

**One declination versus two** is the contrast most likely to be tested.

## The Texas Windstorm Insurance Association

### What it is

**§2210.001** — TWIA is **"a residual insurer of last resort for windstorm and
hail insurance in the seacoast territory"**, and **"shall function in such a
manner as to not be a direct competitor in the private market."**

**§2210.051** — membership is **compulsory**. The association comprises **all**
property insurers authorised to write property insurance in Texas, and
membership is **"a condition of the insurer's authority to engage in the
business of insurance in this state."**

That is how a residual market is funded: the insurers that decline the risk
collectively carry it.

**§2210.003(4) and (11)** define the **first-tier** and **second-tier coastal
counties** — fourteen of each — which with parts of Harris County make up the
catastrophe area.

### Getting a policy

**§2210.202(a)** — eligibility turns on **one declination** from an insurer
authorised to write, and actually writing, windstorm and hail insurance in the
seacoast territory. For **renewal**, a declination is required only **every
three calendar years**.

**§2210.203(a-1)** — for structures built or altered on or after 1 September
2009 and located in **Flood Zone V**, **flood insurance is required** as a
condition of the windstorm policy.

**§2210.203(b)–(c)** — a **one-year** policy term, renewable while the property
remains insurable.

**§2210.203(c-1)** — a renewal payment **grace period of not more than 10
days**.

**§2210.2032** — TWIA must **accept credit cards** and must **offer
instalments**.

### What it pays

**§2210.207(c)** — where the amount of insurance equals **80% or more** of the
full replacement cost, or the policy limit, TWIA pays the **replacement cost**
of the damaged part.

**§2210.207(d)** — **below 80%**, liability is limited as the section
provides. This is the insurance-to-value rule familiar from coinsurance in
Module 1, written into statute.

**§2210.208(a)** — a dwelling policy must cover **wind-driven rain "regardless
of whether an opening is made by the wind."** That is a deliberate departure
from the usual property form, which requires an opening, and it is a reliable
exam point.

**§2210.210** — **wind turbines are not insurable** by the association.

### Maximum limits — §2210.501(b)

| Property | Limit |
| --- | --- |
| A **dwelling**, including an individually owned townhouse unit, and its contents | **$350,000** |
| A building **at least 75% occupied by a governmental entity** | **$2,192,000** |
| **Individually owned contents** in an apartment, condominium or townhouse unit | **$125,000** |
| **Any other structure** and its contents | **$1,500,000** |

**§2210.502** — adjusted annually for inflation by reference to the **BOECKH
Index**, in $1,000 increments. So the figures above move; learn their shape
and order of magnitude rather than trusting them for ever.

**§2210.259** — a **15% surcharge** applies in the circumstances that section
describes (**10%** under §2210.258(c)).

### Claims

- **§2210.205(a)(1) and §2210.573(a)** — file a claim **not later than the
  first anniversary** of the date the damage occurred. **§2210.205(b)** — the
  commissioner may extend for good cause, **up to 180 days**.
- **§2210.573(d)** — TWIA must notify the claimant **in writing within 60
  days** that it accepts in full, accepts in part and denies in part, or
  denies in full.

### The trap: no Chapter 541 or 542 action against TWIA

**§2210.014 and §2210.572** — **there is no private cause of action under
Chapter 541 or Chapter 542 against the association.** The statute provides its
own claim procedure instead.

This connects to **§541.152(c)** from the trade practices lesson: **treble
damages do not apply to an action against TWIA.** A fact pattern inviting you
to apply the ordinary bad-faith remedies to a windstorm claim is testing this.

> **The funding structure changed in 2025.** H.B. 3689 (89th Legislature)
> replaced the Class 1/2/3 public-securities ladder with state-funded
> financing arrangements. Subchapter B-1 and much of Subchapter M are repealed
> **effective 1 September 2027**, and several sections carry two texts. Study
> material written before 2025 describes a structure on its way out. Check
> which text is current before relying on the funding layers.

## The Texas FAIR Plan Association

**FAIR** = **Fair Access to Insurance Requirements**.

### When it exists

**§2211.051(a)** — the commissioner **may** establish the plan, **after a
public hearing**, on determining that:

1. residential property insurance **is not reasonably available in the
   voluntary market** to a substantial number of insurable risks in all or
   part of the state; **or**
2. **at least 25 percent** of qualified applicants to the residential property
   market assistance program **have not been placed with an insurer in the
   preceding six months.**

**§2211.152** — the commissioner **by rule designates the underserved areas**.

### Who runs it

**§2211.052(b)** — a governing committee of **11 members appointed by the
commissioner**:

- **five** representing the interests of insurers;
- **four public members** resident in Texas; and
- **two general property and casualty agents.**

**§2211.052(c)** — the commissioner or a designated employee serves **ex
officio**. **§2211.052(e)** — the commissioner may **remove a member without
cause**.

**§2211.057** — the commissioner supervises the association and the inspection
bureau, with free access to its books and power to summon and examine
witnesses.

### Getting a policy

**§2211.151** — the association **shall** make residential property insurance
available to each applicant **in an underserved area** whose property is
insurable under reasonable underwriting standards but who, **after diligent
efforts, is unable to obtain it in the voluntary market, as evidenced by two
declinations** from insurers authorised to write, and actually writing,
residential property insurance in Texas.

**Two declinations** — against TWIA's one. And note the same "authorized **and
actually writing**" qualifier met in surplus lines.

**§2211.1515** (H.B. 998, 2023) extends the plan to **property owners'
association insurance** in an area the commissioner designates, which must so
far as practicable be **not more than 10 miles beyond the TWIA catastrophe
area**. Two declinations again.

**§2211.154–.155** — the inspection bureau **inspects** the property, and
there is a **reinspection** procedure.

### How the association operates

**§2211.055(a)** — the association may issue policies **in its own name**,
collect premiums, issue cancellations, and pay commissions, losses, judgments
and expenses, **acting on behalf of all participating insurers**.

**§2211.055(b)** — this is the provision to remember: **notice, proof of loss
and legal process must be served on the association**, and **a claim action
may be brought only against the association**, which is "the proper party for
all purposes." **§2211.055(c)** requires the policy to say so.

So a FAIR Plan insured does not sue the member insurers behind it. They sue
the association.

**§2211.054** — the plan of operation must, among other things, **require all
insurers writing residential property insurance to participate**, provide for
**immediate binding of eligible risks**, allow **premium instalment plans**,
establish **maximum limits**, set **agents' commissions**, and provide for
**assessment of all members** in amounts sufficient to operate the
association.

**§2211.056** — the association files proposed **rates** with the commissioner,
who must approve or disapprove **within 60 days**, extendable by **30 days** on
notice. **§2211.056(b)** — rates must be sufficient to **carry all claims to
maturity** and meet expenses. **§2211.056(e)** — **no policy may be issued
until the rates are approved.**

**§2211.002** — **immunity**: no cause of action arises against an insurer, the
inspection bureau, the association or its agents for acts performed under the
chapter.

**§2211.059** — on dissolution, the association's assets go as that section
provides.

## How this is examined

**Which market?** Wind and hail on the coast → **TWIA**. Other residential
property the market will not write → **FAIR Plan**. §2211.156 forbids overlap.

**One declination for TWIA, two for the FAIR Plan.**

**Wind-driven rain is covered by TWIA regardless of an opening made by the
wind.**

**The 80% insurance-to-value rule** in §2210.207.

**$350,000** dwelling limit, indexed.

**No Chapter 541 or 542 action, and no treble damages, against TWIA.**

**A FAIR Plan claim is brought only against the association.**

**11-member governing committee**: five insurer, four public, two agents.

## Check yourself

1. A homeowner in Galveston cannot get windstorm coverage. Which association,
   and how many declinations?
2. A homeowner in an inland underserved area cannot get any residential
   property insurance. Which association, and how many declinations?
3. Could that inland homeowner get wind and hail from the FAIR Plan if their
   property were in a first-tier coastal county?
4. Rain is driven into a TWIA-insured dwelling by hurricane winds, without
   the wind making an opening. Covered?
5. A TWIA policyholder believes the association handled their claim in bad
   faith and wants treble damages under Chapter 541. Will that work?
6. A FAIR Plan insured wants to sue the member insurers who fund the plan. May
   they?
7. TWIA damage occurs on 1 March 2026. By when must the claim be filed?

## Answers

1. **TWIA**, on **one** declination — §2210.202(a). For renewal, a declination
   is needed only every three calendar years.
2. **The FAIR Plan**, on **two** declinations from insurers authorised to
   write and actually writing residential property insurance — §2211.151.
3. **No.** §2211.156 — the FAIR Plan may not provide windstorm and hail
   coverage for a risk eligible under Chapter 2210.
4. **Yes.** §2210.208(a) requires cover for wind-driven rain **"regardless of
   whether an opening is made by the wind."**
5. **No.** §2210.014 and §2210.572 bar a private action under Chapter 541 or
   542 against the association, and §541.152(c) excludes TWIA from treble
   damages.
6. **No.** §2211.055(b) — an action on the policy may be brought **only
   against the association**, which is the proper party for all purposes.
7. **By 1 March 2027** — the first anniversary of the date the damage occurred
   (§2210.205(a)(1), §2210.573(a)), extendable by the commissioner for good
   cause up to **180 days**.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'f2f83e58-1313-5d36-b18f-242354a7ab5c', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'TX.II'
on conflict (lesson_id, topic_id) do nothing;

commit;
