-- Texas Exam Prep — Phase 2, step 4 of 8
--
-- 20260201000300_topics.sql
--
-- Generated by scripts/build-deploy-sql.mjs. Do not edit by hand.
--
-- Run the steps IN ORDER. This one is a single transaction, so if it
-- fails nothing in it is applied and you can fix the cause and re-run
-- this step alone. Steps already applied must NOT be re-run: they are
-- not idempotent and will fail on an existing type or table.

begin;

-- ===========================================================================
-- Phase 2 / 04 — topics and lesson_topics
--
-- A topic is a node of the STATE'S exam blueprint, not of our course outline.
-- Modules are how we teach; topics are how the exam tests. Keeping them as
-- separate hierarchies is what makes "you are weak on Texas statutes" an
-- answerable question later -- if topics were just modules under another
-- name, a readiness score could only ever say "you are weak on chapter 4",
-- which is a fact about our book rather than about the exam.
-- ===========================================================================

create table public.topics (
  id              uuid primary key default gen_random_uuid(),
  course_id       uuid not null references public.courses (id) on delete cascade,

  -- Nullable self-reference. Deleting a parent that still has children is
  -- REJECTED rather than cascaded: a topic subtree is the spine of every
  -- historical score that references it, and losing one to a mis-clicked
  -- delete should require the author to say so explicitly, child by child.
  parent_topic_id uuid references public.topics (id) on delete restrict,

  -- The blueprint's own identifier, e.g. 'P&C.03.02'. Free-form text rather
  -- than a parsed structure: it comes from a published state document and its
  -- format is not ours to constrain.
  code            text not null,
  name            text not null,

  -- The published percentage weighting for this topic, where the blueprint
  -- gives one. Used later to weight a readiness score so that a 15%-of-the-
  -- exam topic counts for more than a 2% one.
  blueprint_weight numeric(5, 2),

  position        integer not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint topics_code_length check (char_length(code) between 1 and 60),
  constraint topics_name_length check (char_length(name) between 1 and 200),
  constraint topics_position_positive check (position > 0),
  constraint topics_weight_range check (
    blueprint_weight is null or (blueprint_weight >= 0 and blueprint_weight <= 100)
  ),

  -- A topic cannot be its own parent. Combined with the depth trigger below,
  -- this makes cycles impossible.
  constraint topics_no_self_parent check (
    parent_topic_id is null or parent_topic_id <> id
  ),

  constraint topics_course_code_key unique (course_id, code),

  -- FK target for lesson_topics.course_id.
  constraint topics_id_course_key unique (id, course_id)
);

comment on table public.topics is
  'Exam blueprint taxonomy, at most two levels deep. Orthogonal to modules: '
  'a module is how we teach, a topic is how the state tests.';

create index topics_course_position_idx on public.topics (course_id, position);
create index topics_parent_idx on public.topics (parent_topic_id);

create trigger topics_set_updated_at
  before update on public.topics
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Depth and cycle enforcement.
--
-- The design allows one level of nesting: a topic is either a root or the
-- child of a root. A check constraint cannot express this, because it cannot
-- read another row. A trigger can.
--
-- This is not tidiness for its own sake. A cycle (A parents B, B parents A)
-- makes any recursive walk of the taxonomy loop forever, and the readiness
-- calculation walks the taxonomy. The self-parent check constraint above rules
-- out a one-row cycle; requiring every parent to be a root rules out every
-- longer one, because a cycle of length two or more needs at least one parent
-- that is itself a child.
--
-- SECURITY INVOKER (the default), like every other trigger in this schema. It
-- needs no privileges of its own -- it reads one row of a table the caller can
-- already reach -- and a SECURITY DEFINER trigger here would repeat the Phase 1
-- mistake of rebinding current_user for no reason.
-- ---------------------------------------------------------------------------
create or replace function public.enforce_topic_depth()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  grandparent uuid;
begin
  if new.parent_topic_id is null then
    return new;
  end if;

  select t.parent_topic_id into grandparent
    from public.topics t
   where t.id = new.parent_topic_id;

  if grandparent is not null then
    raise exception
      'topics may nest one level deep; % already has a parent',
      new.parent_topic_id
      using errcode = '23514';
  end if;

  return new;
end;
$$;

comment on function public.enforce_topic_depth() is
  'Restricts the topic tree to two levels and, with topics_no_self_parent, '
  'makes cycles impossible.';

create trigger topics_enforce_depth
  before insert or update of parent_topic_id on public.topics
  for each row execute function public.enforce_topic_depth();

-- ---------------------------------------------------------------------------
-- lesson_topics — which lessons teach which blueprint topics.
--
-- Many-to-many on purpose. One lesson often covers several blueprint topics,
-- and one topic is usually taught across several lessons. This table is what
-- turns "your weakest topic is Texas statutes" into "read these four
-- lessons" -- i.e. what makes a readiness score actionable instead of
-- merely discouraging.
-- ---------------------------------------------------------------------------
create table public.lesson_topics (
  lesson_id uuid not null,
  topic_id  uuid not null,

  -- Carried so that BOTH composite foreign keys below can point at
  -- (id, course_id) pairs. The effect is that a lesson from one course
  -- physically cannot be tagged with a topic from another: there is no
  -- trigger to forget and no application check to bypass, because no such row
  -- satisfies both foreign keys at once.
  course_id uuid not null,

  created_at timestamptz not null default now(),

  constraint lesson_topics_pkey primary key (lesson_id, topic_id),

  constraint lesson_topics_lesson_fkey
    foreign key (lesson_id, course_id)
    references public.lessons (id, course_id)
    on update cascade
    on delete cascade,

  constraint lesson_topics_topic_fkey
    foreign key (topic_id, course_id)
    references public.topics (id, course_id)
    on update cascade
    on delete cascade
);

comment on table public.lesson_topics is
  'Many-to-many between lessons and blueprint topics. The composite foreign '
  'keys make cross-course tagging structurally impossible.';

create index lesson_topics_topic_idx on public.lesson_topics (topic_id);
create index lesson_topics_course_idx on public.lesson_topics (course_id);

commit;
