-- Texas Exam Prep — Phase 2, step 6 of 8
--
-- 20260201000500_content_rls.sql
--
-- Generated by scripts/build-deploy-sql.mjs. Do not edit by hand.
--
-- Run the steps IN ORDER. This one is a single transaction, so if it
-- fails nothing in it is applied and you can fix the cause and re-run
-- this step alone. Steps already applied must NOT be re-run: they are
-- not idempotent and will fail on an existing type or table.

begin;

-- ===========================================================================
-- Phase 2 / 06 — Row-Level Security for the content tables.
--
-- Same posture as Phase 1: RLS on for every table, and a table with no policy
-- denies everything.
--
-- `(select auth.uid())` stays wrapped in a scalar subquery so Postgres
-- evaluates it once per statement rather than once per row.
-- ===========================================================================

alter table public.modules         enable row level security;
alter table public.lessons         enable row level security;
alter table public.lesson_contents enable row level security;
alter table public.topics          enable row level security;
alter table public.lesson_topics   enable row level security;

-- ---------------------------------------------------------------------------
-- modules — public syllabus
-- ---------------------------------------------------------------------------

-- Published modules of an active course are public. This is marketing copy
-- and structure, not content: a visitor deciding whether to buy needs to see
-- what they would be buying, and a search engine indexing it is the point.
create policy modules_select_published
  on public.modules
  for select
  to anon, authenticated
  using (
    status = 'active'::public.content_status
    and exists (
      select 1
        from public.courses c
       where c.id = modules.course_id
         and c.status = 'active'::public.course_status
    )
  );

create policy modules_select_admin
  on public.modules for select to authenticated
  using (public.is_admin());

create policy modules_insert_admin
  on public.modules for insert to authenticated
  with check (public.is_admin());

create policy modules_update_admin
  on public.modules for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy modules_delete_admin
  on public.modules for delete to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- lessons — public syllabus (titles and structure only; see lesson_contents)
-- ---------------------------------------------------------------------------

-- The whole chain is checked, not just the lesson's own status, so that
-- unpublishing a module hides its lessons and archiving a course hides
-- everything beneath it -- without an author having to cascade the change by
-- hand and without a forgotten row staying visible.
create policy lessons_select_published
  on public.lessons
  for select
  to anon, authenticated
  using (
    status = 'active'::public.content_status
    and exists (
      select 1
        from public.modules m
        join public.courses c on c.id = m.course_id
       where m.id = lessons.module_id
         and m.status = 'active'::public.content_status
         and c.status = 'active'::public.course_status
    )
  );

create policy lessons_select_admin
  on public.lessons for select to authenticated
  using (public.is_admin());

create policy lessons_insert_admin
  on public.lessons for insert to authenticated
  with check (public.is_admin());

create policy lessons_update_admin
  on public.lessons for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy lessons_delete_admin
  on public.lessons for delete to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- lesson_contents — the paid half
-- ---------------------------------------------------------------------------

-- The only non-admin read policy in the content schema that asks who the
-- caller is rather than what the row's status is.
--
-- Both halves are required. Enrollment alone is not enough: a student enrolled
-- in a course must still not read a draft lesson an instructor is midway
-- through writing. Publication alone is obviously not enough: that is the
-- whole product.
--
-- There is deliberately no `to anon` variant. Anonymous visitors hold no
-- privilege on this table at all (see the grants migration), so the request
-- fails before reaching this policy.
create policy lesson_contents_select_enrolled
  on public.lesson_contents
  for select
  to authenticated
  using (
    public.lesson_is_published(lesson_id)
    and public.is_enrolled_in_course(course_id)
  );

create policy lesson_contents_select_admin
  on public.lesson_contents for select to authenticated
  using (public.is_admin());

create policy lesson_contents_insert_admin
  on public.lesson_contents for insert to authenticated
  with check (public.is_admin());

create policy lesson_contents_update_admin
  on public.lesson_contents for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy lesson_contents_delete_admin
  on public.lesson_contents for delete to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- topics — the published exam blueprint
-- ---------------------------------------------------------------------------

-- Public for an active course. The blueprint is a state publication; treating
-- our transcription of it as a secret would protect nothing and would forfeit
-- the most obviously useful page on the site ("what is actually on the Texas
-- exam?"). Topics of a draft course stay hidden, because an unreleased course
-- outline is a business decision rather than a public document.
create policy topics_select_published
  on public.topics
  for select
  to anon, authenticated
  using (
    exists (
      select 1
        from public.courses c
       where c.id = topics.course_id
         and c.status = 'active'::public.course_status
    )
  );

create policy topics_select_admin
  on public.topics for select to authenticated
  using (public.is_admin());

create policy topics_insert_admin
  on public.topics for insert to authenticated
  with check (public.is_admin());

create policy topics_update_admin
  on public.topics for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy topics_delete_admin
  on public.topics for delete to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------------
-- lesson_topics — which lessons teach which topics
-- ---------------------------------------------------------------------------

-- Visible whenever the lesson it points at is visible. A tag on a draft lesson
-- would otherwise disclose that the lesson exists, and what it covers, before
-- it is published.
create policy lesson_topics_select_published
  on public.lesson_topics
  for select
  to anon, authenticated
  using (public.lesson_is_published(lesson_id));

create policy lesson_topics_select_admin
  on public.lesson_topics for select to authenticated
  using (public.is_admin());

create policy lesson_topics_insert_admin
  on public.lesson_topics for insert to authenticated
  with check (public.is_admin());

create policy lesson_topics_update_admin
  on public.lesson_topics for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy lesson_topics_delete_admin
  on public.lesson_topics for delete to authenticated
  using (public.is_admin());

commit;
