-- Texas Exam Prep — Phase 2, step 7 of 8
--
-- 20260201000600_lesson_completions.sql
--
-- Generated by scripts/build-deploy-sql.mjs. Do not edit by hand.
--
-- Run the steps IN ORDER. This one is a single transaction, so if it
-- fails nothing in it is applied and you can fix the cause and re-run
-- this step alone. Steps already applied must NOT be re-run: they are
-- not idempotent and will fail on an existing type or table.

begin;

-- ===========================================================================
-- Phase 2 / 07 — lesson_completions
--
-- The first row a STUDENT is allowed to write.
--
-- Everything before this is authored by admins; a student's only writes were
-- their own first and last name. This table is different, and it is worth
-- being explicit about why it is safe: marking a lesson read grants nothing.
-- It unlocks no content, confers no entitlement, and changes no price. The
-- worst a dishonest student can do is lie to themselves about their own
-- progress, and a product whose threat model includes "the customer cheats at
-- their own revision" has misunderstood who it is for.
--
-- That is not a reason to skip the checks. The INSERT policy still requires
-- the lesson to be published AND the student to hold a live enrollment,
-- because a completion row for a lesson the student cannot read is not a lie,
-- it is corrupt data: it would count toward a progress percentage whose
-- denominator does not contain it.
-- ===========================================================================

create table public.lesson_completions (
  student_id   uuid not null references public.profiles (id) on delete cascade,
  lesson_id    uuid not null,

  -- Denormalised, and held true by the composite foreign key below, exactly
  -- as on lessons and lesson_contents. The INSERT policy needs a course id to
  -- check enrollment against, and joining to reach one on every row of a
  -- policy evaluation is the cost this column exists to avoid.
  course_id    uuid not null,

  completed_at timestamptz not null default now(),

  -- One row per student per lesson. Re-marking is a no-op rather than a
  -- second row, so "how many lessons has this student finished?" is a count
  -- and never a count of distinct values.
  constraint lesson_completions_pkey primary key (student_id, lesson_id),

  constraint lesson_completions_lesson_fkey
    foreign key (lesson_id, course_id)
    references public.lessons (id, course_id)
    on update cascade
    on delete cascade
);

comment on table public.lesson_completions is
  'A student marking a lesson read. Self-service: students insert and delete '
  'their own rows. Marking a lesson complete grants no access to anything.';

-- Every progress query filters by student and course together.
create index lesson_completions_student_course_idx
  on public.lesson_completions (student_id, course_id);

-- "How many students finished this lesson?" for the later reporting phase.
create index lesson_completions_lesson_idx
  on public.lesson_completions (lesson_id);

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
revoke all on table public.lesson_completions from anon, authenticated;
grant select, insert, delete on table public.lesson_completions to authenticated;
-- No UPDATE, for anyone. A completion has nothing mutable on it: the student
-- id and lesson id are its identity, and `completed_at` is a fact about when
-- something happened. Un-marking is a DELETE, and re-marking inserts a fresh
-- row with a fresh timestamp — which is the honest record of what occurred.
-- No grants at all to `anon`.

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------
alter table public.lesson_completions enable row level security;

create policy lesson_completions_select_own
  on public.lesson_completions
  for select
  to authenticated
  using (student_id = (select auth.uid()));

create policy lesson_completions_select_admin
  on public.lesson_completions
  for select
  to authenticated
  using (public.is_admin());

-- The one self-service write in the schema.
--
-- WITH CHECK, not USING: an INSERT has no existing row to test. All three
-- conditions matter:
--   * student_id must be the caller, or one student could fabricate another's
--     progress record.
--   * the lesson must be published, or a student could mark a draft lesson
--     that no progress denominator counts.
--   * the enrollment must be live, or completions accumulate against a course
--     the student cannot read, and a later re-enrollment inherits progress
--     they never made.
create policy lesson_completions_insert_own
  on public.lesson_completions
  for insert
  to authenticated
  with check (
    student_id = (select auth.uid())
    and public.lesson_is_published(lesson_id)
    and public.is_enrolled_in_course(course_id)
  );

-- Un-marking deliberately does NOT require publication or a live enrollment.
-- A student whose access lapsed, or whose lesson was unpublished beneath
-- them, must still be able to clear their own row; the alternative is data
-- they own and cannot remove.
create policy lesson_completions_delete_own
  on public.lesson_completions
  for delete
  to authenticated
  using (student_id = (select auth.uid()));

-- Deliberately absent: any admin INSERT, UPDATE or DELETE policy. Progress is
-- the student's own record of their own study. An admin who could edit it
-- would make every readiness score arguable, and no support request needs it.

commit;
