-- GENERATED by scripts/import-content.mjs — do not edit by hand.
-- Source of truth is content/. Re-run the script after editing a lesson.
--
-- Lessons whose front matter still says UNREVIEWED are written as
-- drafts, which RLS hides from students entirely, body included.

insert into public.modules (id, course_id, title, position, status)
select '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Insurance Fundamentals', 1, 'active'
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set title = excluded.title;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Risk, Peril and Hazard',
       'risk-peril-and-hazard', 'Three words the exam treats as distinct and everyday speech does not.', 1,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', c.id, $lesson$# Three words, three meanings

In ordinary speech *risk*, *peril* and *hazard* are near-synonyms. You could
say "the risk of fire", "the peril of fire" or "a fire hazard" over coffee and
nobody would stop you.

The exam stops you. It treats them as three separate ideas, and a run of
questions turns on nothing harder than telling them apart. They are worth ten
minutes now because every later topic assumes them.

The one-line version:

- **Risk** is the uncertainty.
- **Peril** is the thing that causes the loss.
- **Hazard** is what makes the peril more likely, or worse when it happens.

## Risk

**Risk is uncertainty about loss.**

Notice what that does *not* say. It does not say the loss is likely, or large,
or imminent. It says the outcome is not known in advance. A building with
sprinklers, an alarm and a spotless history still carries risk, because nobody
can promise it will not burn.

The exam cares about one division above all others, because only one side of
it is insurable.

**Pure risk** offers two outcomes: a loss, or no loss. A house either burns or
it does not. A driver either has a collision or does not. There is no version
of the story where you come out ahead. **Pure risk is insurable.**

**Speculative risk** offers three: a loss, no loss, or a *gain*. Opening a
restaurant. Buying shares. Betting on a horse. **Speculative risk is not
insurable.**

> If a person could profit from the event, an insurer will not cover it.

That single sentence answers a surprising number of questions. When a stem
describes a situation and asks whether it is insurable, find out whether
anyone stands to gain. If they do, the answer is no.

The reason is not squeamishness about gambling. It is that insurance works by
pooling many similar exposures and predicting the total — which only holds if
losses happen *to* people rather than being chosen *by* them.

## Peril

**A peril is the cause of loss itself.**

Fire. Windstorm. Hail. Theft. Collision. Vandalism. When a policy sets out
what it covers, it is listing perils, and two structures recur:

- **Named perils.** The policy lists the causes it covers. If a cause is not
  on the list, there is no coverage. The burden sits with the insured to show
  the loss came from a listed peril.
- **Open perils** (you will also see "all risk" or "special form"). Every
  cause is covered *except* those the policy excludes. The burden flips: the
  insurer must show the loss came from an excluded cause.

That reversal of burden is the point, and it is tested. Open-perils coverage is
broader not because the list of covered causes is longer but because the
policy stops trying to list them.

A related idea travels with perils: **proximate cause** — the unbroken chain
of events from the peril to the damage. If a windstorm breaks a window and
rain then ruins the carpet, the proximate cause is the windstorm, even though
water did the visible damage. Coverage follows the proximate cause, not the
last thing that happened.

## Hazard

**A hazard is a condition that makes a peril more likely, or a loss worse.**

A hazard is not itself the cause. Oily rags in a basement do not damage
anything. They make fire — the peril — more likely, and worse when it comes.

The exam expects three categories, and the last two are where people lose
marks.

**Physical hazard** is a tangible condition of the property or its use. Oily
rags. An icy front step. Storing fireworks in a shop. Anything you could point
at.

**Moral hazard** is *dishonesty in the insured*. A person who has arranged a
convenient fire before, or who would inflate a claim, or who insures a
business that has stopped making money. The insurer's exposure rises because
of who this person is, not because of anything on the premises.

**Morale hazard** is *indifference caused by being insured*. Not dishonesty —
carelessness. Leaving a car unlocked because the policy will pay. Skipping the
roof repair because it is covered anyway. The person is not planning to cause
a loss; they have simply stopped trying hard to prevent one.

The distinction in one line: **moral is dishonesty, morale is carelessness.**

Some texts add a fourth, **legal hazard** — conditions in the legal
environment, such as a jurisdiction whose courts award unusually large
verdicts, that increase the size of losses independently of anything the
insured does.

## Loss

Rounding out the set: a **loss** is the reduction, decrease or disappearance
of value. It is what actually happened, after the hazard made the peril more
likely and the peril occurred.

## How this is examined

Questions in this area are rarely difficult once the vocabulary is straight.
They are usually one of four shapes.

**"Which of the following is a hazard?"** — with perils among the distractors.
Ask yourself: is this thing the *cause* of a loss, or a *condition that makes
a cause more likely*? Fire is a peril. A frayed extension cord is a hazard.

**"Moral or morale?"** — the most common trap in the whole section. Look for
intent. Dishonesty, fraud, a motive to cause a loss → moral. Laziness,
indifference, "it's insured anyway" → morale.

**"Is this insurable?"** — apply the profit test. Any chance of gain makes it
speculative and uninsurable.

**Named versus open perils** — ask who has to prove what. Named: the insured
proves the cause is covered. Open: the insurer proves it is excluded.

## Check yourself

Before moving on, answer these without looking back.

1. A restaurant owner whose business is failing takes out a large fire policy.
   Which kind of hazard is that, and why?
2. A homeowner stops locking the back door because they now have a theft
   policy. Which kind of hazard, and why?
3. Is the possibility that a stock you bought will fall in value a pure risk
   or a speculative risk? Is it insurable?
4. Under an open-perils form, who has to prove what?

## Answers

Work through the four above before reading these.

1. **Moral hazard.** The motive is dishonesty: a failing business is worth
   more to its owner burnt than trading, so the insurer's exposure rises
   because of who this person is.
2. **Morale hazard.** No intent to cause a loss — only carelessness that
   appeared once the policy did.
3. **Speculative**, because a gain is possible. Therefore not insurable.
4. **The insurer** must prove the cause of loss falls under an exclusion. The
   insured only has to show a loss occurred.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '8a2bf024-c5e6-543b-8512-a8ae2dea372b', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'How Insurance Works',
       'how-insurance-works', 'Why insurers can predict losses they cannot predict individually, and which risks they will not touch.', 2,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', c.id, $lesson$# The trick at the centre of insurance

An insurer cannot tell you whether *your* house will burn down this year.
Nobody can. Yet it will quite confidently tell you how many of one hundred
thousand similar houses will burn, and price your policy accordingly.

That is not a paradox, and the exam wants you to be able to say why.

## The law of large numbers

**The more similar exposures you observe, the closer actual losses come to
expected losses.**

Toss a coin four times and you might get four heads. Toss it four thousand
times and you will get close to half. Nothing about any individual toss became
more predictable; the *aggregate* did.

Insurance runs on exactly this. One house is unpredictable. A hundred thousand
similar houses are not. The insurer does not need to know which ones will
burn — only how many, near enough to set a price that covers the losses, the
expenses and a margin.

Two words in that sentence are doing heavy lifting. **Similar**: houses, not a
mixture of houses and oil refineries. **Many**: a handful of exposures gives
you no more certainty than one.

## What makes a risk insurable

The exam expects a list. Different textbooks phrase it differently, but the
substance is consistent, and each item is really a way of protecting the law
of large numbers.

**A large number of similar exposure units.** Without them the mathematics
does not work.

**The loss must be definite and measurable.** You must be able to say when it
happened, where, from what cause, and what it cost. "My business felt less
successful this year" is none of those things.

**The loss must be accidental** from the insured's standpoint — fortuitous,
outside their control. This is the same principle that makes speculative risk
uninsurable, seen from another angle.

**The loss must not be catastrophic to the insurer.** If a single event could
wipe out every exposure at once, pooling has not spread anything. This is why
flood and earthquake sit outside standard property policies, and why Texas
handles windstorm on the coast through a separate association.

**The chance of loss must be calculable.** You need data, or the price is a
guess.

**The premium must be economically feasible.** If the honest premium approaches
the value of the thing insured, nobody sensible buys it. A policy costing
$90,000 a year to insure a $100,000 building has no market.

## Adverse selection

**Adverse selection is the tendency of those most likely to suffer a loss to
be the most eager to buy insurance.**

People who live on a floodplain want flood cover more than people on a hill.
Someone who has just felt a lump wants health cover more urgently than someone
who has not. Left alone, an insurer's pool fills up with exactly the exposures
it can least afford, and the pool stops resembling the population the price
was based on.

Nearly every piece of underwriting machinery exists to resist this:
applications, inspections, waiting periods, exclusions, pre-existing condition
clauses, and the underwriter's right to decline.

Do not confuse it with **moral hazard**, which the exam likes to place
nearby. Adverse selection happens *before* the policy, in who chooses to buy.
Moral hazard happens *after*, in how the insured behaves once covered.

## Where the premium goes

A premium has to cover three things: expected losses, the insurer's expenses
(commissions, salaries, taxes), and a margin for profit and contingencies. The
loss portion is often called the **pure premium**, and the amount added for
expenses and profit the **loading**.

This is worth knowing because it explains an answer that otherwise looks
strange: an insurer can be paying out less than it collects and still be
losing money, once expenses are counted.

## Risk management before insurance

Insurance is one response to risk, not the only one. The exam tests the full
set, usually by asking which one a described action represents.

- **Avoidance** — do not take the risk at all. Do not buy the building.
- **Retention** — accept it and pay losses yourself. A deductible is retention.
- **Reduction** (or control) — lower the frequency or severity. Sprinklers,
  training, locks.
- **Transfer** — move it to someone else. Insurance is transfer; so is a hold
  harmless agreement in a contract.
- **Sharing** — spread it across a group, as partners or a pool do.

A common stem describes a business installing a sprinkler system and asks
which technique that is. It is *reduction*, not transfer — the sprinklers do
not move the risk to anybody, they make the loss smaller.

## How this is examined

**"Which of the following is not a characteristic of an insurable risk?"** —
usually with "the loss must be catastrophic" or "the insured must be able to
cause the loss" among the options. Work down the list.

**Law of large numbers questions** turn on the word *similar* or the word
*more*. The prediction improves with more exposures, and only if they resemble
one another.

**Adverse selection versus moral hazard** — ask when it happens. Before the
policy is written, it is adverse selection.

**Risk-management technique questions** describe an action and want the label.
Deductible → retention. Sprinklers → reduction. Buying a policy → transfer.
Not opening the business → avoidance.

## Check yourself

1. An insurer writes one hundred thousand homeowners policies instead of one
   hundred. What has improved, and what has not?
2. Why are floods difficult to insure through an ordinary property policy?
3. A contractor adds a clause making the client responsible for certain
   losses. Which risk-management technique is that?
4. A homeowner chooses a $2,500 deductible instead of $500. Which technique?

## Answers

1. The *predictability of the total* has improved. The predictability of any
   single house has not changed at all — that is the whole point of the law of
   large numbers.
2. One event damages an enormous number of exposures simultaneously, so the
   losses are not independent and the pool does not spread them. It is the
   "not catastrophic to the insurer" condition failing.
3. **Transfer** — the risk is moved to another party by contract. Insurance is
   not the only form of transfer.
4. **Retention** — they have chosen to carry more of each loss themselves.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '42eb61d9-af5e-55d2-91a8-1bcce382c4ed', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Insurable Interest and Indemnity',
       'insurable-interest-and-indemnity', 'Who is allowed to insure what, and the rule that you may be made whole but never better off.', 3,
       'draft', 13
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', c.id, $lesson$# Two rules that stop insurance becoming gambling

Insurance moves money to people after bad things happen. Two principles keep
that from becoming a betting shop, and between them they decide a great many
exam questions.

**Insurable interest** decides *who may buy*.
**Indemnity** decides *how much they may collect*.

## Insurable interest

**You may only insure something you would genuinely lose by.**

That is the whole rule. Everything else follows from it.

### Why it exists

Without the rule, anyone could take out a fire policy on a stranger's
warehouse and then hope for a fire. That gives a stranger a financial reason
to want the warehouse to burn — and gives the insurer no way to distinguish a
customer from an arsonist. Requiring an interest removes the motive.

It is also what separates insurance from a wager in law. A bet creates a risk
that did not exist before. Insurance transfers one that already did.

### When it must exist — the detail that is tested

Property and life insurance answer this differently, and the difference is
examined constantly.

**Property and casualty: at the time of the loss.**

You can insure a building and later sell it. If it burns after the sale, the
claim fails — not because you never had an interest, but because you no longer
had one when the loss happened.

**Life: when the policy is taken out, and not necessarily after.**

A woman insures her husband's life. They divorce. She remains the beneficiary
and the policy pays. The interest existed at inception, which is all life
insurance requires.

A neat way to hold it: **property asks "do you lose by this now?"; life asks
"did you have reason to buy this then?"**

### Who has one

- An **owner**, in their own property.
- A **lender or mortgagee**, up to the amount still owed. A bank holding a
  $200,000 mortgage has an interest of $200,000, not the value of the house.
- A **business**, in a key employee, or in property it holds for others.
- A **spouse**, in the other spouse's life; a parent in a dependent child's.
- A **tenant**, in improvements they have paid for.
- A **bailee** — a garage, a dry cleaner — in customers' property in their
  care.

### How much interest

Your interest is limited to what you stand to lose. A part-owner of a building
cannot insure the whole of it for their own benefit, and a lender cannot
recover more than the outstanding balance. This flows straight into the second
principle.

## Indemnity

**Indemnity means restoring the insured to the financial position they were in
immediately before the loss — no worse, and no better.**

The second half is the part that gets tested. If a loss could leave you better
off, somebody eventually arranges a loss.

Several familiar policy mechanisms are indemnity doing its work:

- **Actual cash value** settlements, which deduct depreciation so a
  twenty-year-old roof is not replaced with a new one at the insurer's expense.
- **Policy limits**, capping recovery at the amount insured.
- **Deductibles**, leaving part of every loss with the insured.
- **Other insurance clauses**, so two policies covering the same loss share it
  rather than each paying in full.
- **Subrogation**, letting the insurer step into the insured's shoes and
  recover from whoever caused the loss — which stops the insured collecting
  twice, once from the insurer and again from the wrongdoer.

### Where indemnity is deliberately set aside

The exam likes exceptions, and there are three worth knowing.

**Valued policies** pay an agreed amount regardless of actual value, used where
value is hard to establish after the fact — fine art, antiques.

**Replacement cost** coverage pays to replace without deducting depreciation,
which technically leaves the insured better off. It is sold anyway because
underinsurance after a total loss is a worse problem than the one it creates.

**Life insurance** is not a contract of indemnity at all. A life has no
measurable value, so the policy pays a stated sum. This is why insurable
interest is only required at inception.

## How this is examined

**"When must insurable interest exist?"** — the single most common question in
this area. Property: at the time of loss. Life: at inception.

**Fact patterns about lenders.** A mortgagee's interest is the balance
outstanding, not the property's value.

**"Which of these is not a contract of indemnity?"** — the answer is life
insurance, or a valued policy.

**Questions about collecting twice.** Subrogation and other-insurance clauses
both exist to prevent it; recognise them as indemnity in action.

## Check yourself

1. A man insures his house, then sells it. Two months later it burns. Does his
   policy respond? Why?
2. A bank holds a $150,000 mortgage on a $400,000 home. What is the extent of
   its insurable interest?
3. A woman insures her husband's life. They divorce, and she keeps paying the
   premiums. He dies. Does the policy pay?
4. An insurer pays a claim, then sues the driver who caused it. What is that
   called, and which principle does it serve?

## Answers

1. **No.** Property insurance requires an insurable interest **at the time of
   the loss**, and he no longer had one.
2. **$150,000** — the amount outstanding. A lender's interest is what it stands
   to lose, not what the property is worth.
3. **Yes.** Life insurance requires the interest only **when the policy is
   taken out**. It does not have to survive the marriage.
4. **Subrogation**, and it serves **indemnity** — without it the insured could
   recover twice for the same loss.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '707e2d75-4394-5463-9f46-d9cedf43df3f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select 'e1d24da3-2f83-5484-8008-27456a1c9f05', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Valuing a Loss',
       'valuing-a-loss', 'Actual cash value, replacement cost and agreed value — and why the difference decides what a claim pays.', 4,
       'draft', 14
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select 'e1d24da3-2f83-5484-8008-27456a1c9f05', c.id, $lesson$# What was it worth?

Two houses burn on the same street, insured for the same amount, by the same
company. One owner is paid enough to rebuild. The other is paid considerably
less and cannot.

The difference is usually not the limit. It is the **valuation method** printed
on the declarations page, and it is the single most practical thing in this
module.

## Actual cash value

**Actual cash value is replacement cost minus depreciation.**

Depreciation is the loss in value from age, wear and obsolescence. A roof with
a twenty-year expected life, destroyed in year fifteen, has used up most of
its life. Under ACV the insurer pays for what was lost — a fifteen-year-old
roof — not a new one.

This is indemnity being strict. The insured is restored to where they were,
which is to say owning a worn roof, not upgraded to where they would like to
be.

The arithmetic is usually straightforward:

> A roof costs $20,000 to replace new. Expected life 20 years, current age 15.
> Depreciation is 15/20 = 75%, so $15,000. **ACV = $20,000 − $15,000 =
> $5,000.**

Some jurisdictions also recognise the **broad evidence rule**, under which a
court may consider anything relevant to value — market value, replacement cost
less depreciation, the property's use and remaining life — rather than
mechanically applying one formula.

## Replacement cost

**Replacement cost pays to replace with property of like kind and quality,
with no deduction for depreciation.**

The same roof is paid at $20,000.

This is a deliberate departure from indemnity, and insurers manage the
exposure in two ways you should recognise:

- **A coinsurance or insurance-to-value requirement**, obliging the insured to
  carry a limit close to full replacement cost.
- **Paying ACV first, then the difference once repairs are actually made.**
  The insured cannot simply pocket the replacement value and not rebuild —
  that would be the profit motive the whole system avoids.

## Market value

**Market value is what the property would sell for** — and it is neither of the
above.

It includes the land, location and demand. A house may cost $300,000 to
rebuild and sell for $180,000 in a declining area, or sell for $900,000 in a
desirable one on the same construction cost. Property policies insure the
building, not the neighbourhood, so market value rarely governs a property
claim.

The exam uses this as a distractor. If a stem mentions what a house "would sell
for", be suspicious.

## Agreed value and stated value

**Agreed value** (a *valued policy*) fixes the amount payable when the policy
is written, and pays it on a total loss without argument about depreciation.
It is used where value is genuinely contentious after the fact: fine art,
antiques, collectibles, some commercial property.

**Stated amount** is a related idea, common on specialised equipment: the
insured declares a value, and the policy pays the lesser of that amount, ACV,
or the cost to repair.

## Functional replacement cost

Sometimes replacing like with like is absurd. A Victorian building with
plaster mouldings and hand-cut joinery could be rebuilt to modern equivalent
standards for far less. **Functional replacement cost** pays to replace with
modern materials serving the same function.

## Depreciation, recoverable and not

Two terms turn up in claims and occasionally on exams.

**Recoverable depreciation** is the gap between the ACV payment and the
replacement cost, released to the insured once the work is done under a
replacement-cost policy.

**Non-recoverable depreciation** is the gap under an ACV policy, which is never
paid because ACV is all the policy promised.

## How this is examined

**Calculation questions.** Straightforward, and worth practising until they are
automatic: find the depreciation percentage from age over expected life, apply
it to replacement cost, subtract.

**"Which valuation method pays the most?"** Replacement cost, because nothing
is deducted for age.

**Market value as a distractor.** A stem that tells you the sale price is
usually testing whether you know that property claims are not settled on it.

**Why an insurer would pay ACV first.** To ensure the property is actually
repaired, so the insured is indemnified rather than enriched.

## Check yourself

1. A five-year-old air-conditioning unit with a ten-year life is destroyed. A
   new one costs $8,000. What is the ACV?
2. The same unit, insured on a replacement cost basis. What does the policy
   pay, and when?
3. A house would cost $250,000 to rebuild but would sell for $175,000. On which
   figure is a property claim normally based, and why?
4. Why might a collector prefer an agreed value policy for a painting?

## Answers

1. Depreciation is 5/10 = 50%, so $4,000. **ACV = $8,000 − $4,000 = $4,000.**
2. **$8,000**, though typically as $4,000 (the ACV) now and the remaining
   $4,000 once the unit has actually been replaced.
3. **$250,000, the replacement cost.** The policy insures the building, not the
   land or the state of the local market. Market value is a distractor.
4. Because the value of a painting is contentious and hard to establish after
   it has been destroyed. An agreed value settles the argument in advance,
   while it can still be appraised.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select 'e1d24da3-2f83-5484-8008-27456a1c9f05', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '2f93978e-6aca-5ed1-99ea-e672f8e06e7f', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Deductibles, Coinsurance and Limits',
       'deductibles-coinsurance-and-limits', 'The arithmetic questions — and the coinsurance formula that catches people who insure for too little.', 5,
       'draft', 16
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '2f93978e-6aca-5ed1-99ea-e672f8e06e7f', c.id, $lesson$# The three numbers that decide what a claim pays

A limit, a deductible and a coinsurance percentage look like fine print. They
are the arithmetic of almost every calculation question on the exam, and
coinsurance in particular catches people who have not practised it.

## Deductibles

**A deductible is the portion of each loss the insured keeps.**

It is risk retention, chosen deliberately. It exists for three reasons: it
removes small claims whose handling cost exceeds their value, it reduces the
premium, and it leaves the insured with a stake in preventing losses — a
direct answer to morale hazard.

Forms you should recognise:

- **Flat** (or straight) — a fixed sum subtracted from each loss. $1,000.
- **Percentage** — a proportion of the insured value rather than of the loss.
  Common for wind and hail, and this is the one that surprises people: 2% of a
  $400,000 dwelling is $8,000 whatever the damage came to.
- **Aggregate** — the insured absorbs losses until a total is reached, after
  which the policy pays in full.
- **Disappearing** (vanishing) — reduces as the loss grows and disappears
  above a threshold.
- **Waiting period** — a deductible measured in time rather than money, used
  in business interruption and disability.

## Limits of liability

**A limit is the most the policy will pay.** The exam tests which limit applies
to what.

- **Per occurrence** — the most for any one event.
- **Aggregate** — the most for all events in the policy period. Once
  exhausted, the policy is finished even though the period has not ended.
- **Split limits**, written as three numbers such as 100/300/50 (in
  thousands): **$100,000 bodily injury per person**, **$300,000 bodily injury
  per accident**, **$50,000 property damage per accident**.
- **Combined single limit** — one figure covering bodily injury and property
  damage together, in any proportion.
- **Per person / per occurrence** — the first caps what any one claimant
  receives, the second what the whole event can produce.

A classic stem: under 100/300/50, four people are injured, each with $90,000 of
bodily injury. Each claim is under the $100,000 per-person limit, so each is
paid in full — but the total, $360,000, exceeds the $300,000 per-accident
limit. The policy pays **$300,000**.

## Coinsurance

This is the one to practise.

**A coinsurance clause requires the insured to carry a limit equal to at least
a stated percentage of the property's value.** Carry less, and the policy pays
less than the loss — even when the loss is far below the limit.

The reason is that most property losses are partial. Somebody insuring a
$1,000,000 building for $200,000 is not buying a fifth of the protection; they
are buying most of it, because a total loss is rare. Coinsurance makes the
premium correspond to the exposure.

### The formula

> **(Did ÷ Should) × Loss − Deductible = Payment**

- **Did** — the limit actually carried.
- **Should** — the coinsurance percentage × the property's value at the time
  of loss.
- The result is capped at the policy limit, and never exceeds the loss.

### Worked example

A building is worth **$500,000**. The policy carries an **80% coinsurance**
clause, a limit of **$300,000** and a **$1,000 deductible**. A fire causes
**$100,000** of damage.

- **Should** = 80% × $500,000 = **$400,000**
- **Did** = **$300,000**
- $300,000 ÷ $400,000 = **0.75**
- 0.75 × $100,000 = $75,000
- Less the deductible: **$74,000**

The insured is $26,000 short on a loss well inside the limit. That is
coinsurance working exactly as intended and feeling exactly as unfair as it
always does.

### The details that get tested

- Value is measured **at the time of the loss**, not when the policy was
  written. A building that appreciates can leave a once-compliant insured
  underinsured.
- Meet or exceed the requirement and the fraction is 1 or more; the loss is
  paid in full, less the deductible, up to the limit. **Over-insuring does not
  pay more than the loss.**
- Coinsurance applies to **partial** losses. On a total loss the limit governs.
- An **agreed value** endorsement suspends the clause, the insurer having
  already accepted the value.

## How this is examined

**Coinsurance calculations**, most often with the insured underinsured. Write
down Did, Should, Loss and the deductible before touching the arithmetic.

**Split limit questions** with several claimants, testing whether you apply the
per-person limit to each and then the per-accident limit to the total.

**Percentage deductible questions**, testing whether you take the percentage of
the *insured value* rather than of the loss.

**"Why does coinsurance exist?"** Because most losses are partial, so a low
limit buys nearly full protection at a fraction of the premium.

## Check yourself

1. A building worth $800,000 carries 80% coinsurance and a $500,000 limit. A
   $200,000 loss occurs, deductible $2,500. What is paid?
2. A homeowner has a 2% wind deductible on a dwelling insured for $350,000.
   Hail causes $12,000 of damage. What is paid?
3. Under split limits of 250/500/100, three people are injured with bodily
   injury claims of $200,000, $200,000 and $150,000. What does the policy pay
   for bodily injury?
4. Does carrying a limit above the coinsurance requirement increase what a
   partial loss pays?

## Answers

1. Should = 80% × $800,000 = $640,000. Did = $500,000. 500/640 = 0.78125.
   × $200,000 = $156,250. Less $2,500 = **$153,750**.
2. The deductible is 2% of the **insured value**: 2% × $350,000 = $7,000.
   $12,000 − $7,000 = **$5,000**.
3. Each claim is within the $250,000 per-person limit, so each is payable in
   full — but they total $550,000 against a $500,000 per-accident limit. The
   policy pays **$500,000** for bodily injury.
4. **No.** Once the fraction reaches 1 the loss is paid in full less the
   deductible. Insurance never pays more than the loss.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '2f93978e-6aca-5ed1-99ea-e672f8e06e7f', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.II'
on conflict (lesson_id, topic_id) do nothing;

insert into public.lessons
  (id, module_id, course_id, title, slug, summary, position, status,
   estimated_minutes)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', '34b6c5a1-202f-5d9f-b12a-d98a335b2916', c.id, 'Negligence and Liability',
       'negligence-and-liability', 'The four elements a claimant must prove, the defences against them, and the kinds of damages a court can award.', 6,
       'draft', 15
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (id) do update set
  title = excluded.title, summary = excluded.summary,
  position = excluded.position, status = excluded.status,
  estimated_minutes = excluded.estimated_minutes;

insert into public.lesson_contents (lesson_id, course_id, body)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', c.id, $lesson$# Being at fault, precisely

Property insurance asks what something was worth. Liability insurance asks a
harder question: **were you legally responsible?**

Almost all of casualty insurance rests on negligence, and the exam tests it as
a checklist. Learn the checklist.

## The four elements

**A claimant must prove all four. Miss one and there is no negligence.**

**1. A duty owed.** The defendant owed the claimant a duty of care. Drivers owe
it to other road users; shopkeepers to customers; property owners to lawful
visitors.

**2. A breach of that duty.** They failed to act as a reasonable person would
in the circumstances. The standard is not perfection — it is reasonableness.

**3. Proximate cause.** The breach actually caused the harm, in an unbroken
chain. If something else intervened and caused it, the chain is broken.

**4. Damages.** The claimant actually suffered a loss. Carelessness that
injures nobody is not actionable.

A shop leaves a spill unmopped. A customer slips, breaks a wrist, and incurs
medical bills. Duty: the shop owes customers reasonable care. Breach: it left a
known hazard. Proximate cause: the spill caused the fall. Damages: the bills
and the injury. All four — negligence.

Change one fact. The customer sees the spill, walks round it, and goes home
unharmed. There is a duty and a breach, but no damages, and therefore no claim.

## Degrees and special forms of liability

**Gross negligence** — reckless indifference to others' safety, beyond ordinary
carelessness. It matters because it can expose a defendant to punitive damages.

**Absolute (strict) liability** — liability without any need to prove fault,
imposed on inherently dangerous activities: blasting, keeping wild animals,
some product defects. Workers' compensation is built on a related idea, the
employer being liable for workplace injury regardless of fault.

**Vicarious liability** — responsibility for somebody else's negligence
because of a relationship. An employer for an employee acting within the scope
of employment; a parent for a child in some circumstances. The employer was not
careless; it is liable because the employee was.

## Defences

These come up as often as the elements.

**Comparative negligence** — the claimant's own share of fault reduces their
recovery. Most states use some version, and the details vary by state, so treat
the general principle as the examinable point here.

**Contributory negligence** — the older and harsher rule, under which any fault
by the claimant bars recovery entirely. Very few states still apply it, but it
appears in exam questions as a contrast to comparative negligence.

**Assumption of risk** — the claimant knowingly and voluntarily accepted a
known danger. Spectators at a baseball game and foul balls.

**Intervening cause** — something unforeseeable broke the chain between the
breach and the harm.

**Statute of limitations** — the claimant waited too long to bring the claim.

## Damages

Getting these labels straight is worth easy marks.

**Compensatory damages** make the claimant whole, and split in two:

- **Special damages** — specific, provable, economic losses. Medical bills,
  lost wages, the cost of repairs. You can put a receipt to them.
- **General damages** — real but not itemisable. Pain and suffering,
  disfigurement, loss of consortium.

**Punitive (exemplary) damages** punish the defendant and deter others, awarded
for gross negligence or deliberate wrongdoing rather than ordinary
carelessness. They are not compensation, and many liability policies do not
cover them.

The memory hook that survives exam pressure: **special is specific**.

## Occurrence and claims-made

Liability policies come in two triggers, and the distinction decides which
policy answers a claim.

**Occurrence** — responds to injury or damage that *happened* during the policy
period, whenever the claim is made. A 2020 policy answers a 2026 claim for a
2020 injury.

**Claims-made** — responds to claims *first made* during the policy period,
usually subject to a **retroactive date** before which injuries are not
covered. Common in professional liability, where harm may surface years later.

Because a claims-made policy stops responding when it ends, **extended
reporting periods** — "tail" coverage — exist to cover claims made after it
expires for acts committed while it was in force.

## How this is examined

**"Which element is missing?"** — a fact pattern that fails on one of the four.
Most often damages, or proximate cause.

**Special versus general damages** — sort by whether a receipt exists.

**Vicarious liability** — a stem where the person sued was not the person who
was careless.

**Occurrence versus claims-made** — ask whether the question emphasises when
the injury *happened* or when the claim was *made*.

**Strict liability** — look for inherently dangerous activity, and for the
absence of any allegation of carelessness.

## Check yourself

1. A driver runs a red light. Nobody is nearby and nothing happens. Has any
   element of negligence been satisfied, and is there a claim?
2. A delivery driver rear-ends a car while working. The employer is sued
   although it did nothing careless. What is this called?
3. A claimant is awarded $40,000 for medical bills and lost wages, and $60,000
   for pain and suffering. Label each.
4. A surgeon's 2023 operation causes harm discovered in 2026. Which policy
   responds under an occurrence form, and which under claims-made?

## Answers

1. Duty and breach are present. **Proximate cause and damages are not**, so
   there is no negligence claim. Carelessness that harms nobody is not
   actionable.
2. **Vicarious liability** — responsibility for an employee's negligence
   committed within the scope of employment.
3. $40,000 is **special damages** (specific, provable, economic). $60,000 is
   **general damages** (real but not itemisable). Both are compensatory.
4. **Occurrence:** the 2023 policy, because the injury happened then.
   **Claims-made:** the 2026 policy, because that is when the claim was first
   made — provided the retroactive date precedes 2023.$lesson$
  from public.courses c where c.slug = 'texas-general-lines-property-casualty'
on conflict (lesson_id) do update set body = excluded.body;

insert into public.lesson_topics (lesson_id, topic_id, course_id)
select '6cb03304-a5e0-5bd8-95dc-ce7cc45d0458', t.id, t.course_id
  from public.topics t
  join public.courses c on c.id = t.course_id
 where c.slug = 'texas-general-lines-property-casualty' and t.code = 'GK.V'
on conflict (lesson_id, topic_id) do nothing;
