#!/usr/bin/env python3
"""Turn a statutes.capitol.texas.gov chapter PDF into reviewable plain text.

The PDFs are generated by the site and carry their chapter name in the PDF
title, which is used as the header here so a file can never be mistaken for a
different chapter. Text rather than the PDF is committed because text diffs
when the legislature amends a section, and a binary does not.
"""
import re, sys, zlib
from datetime import date

def streams(data):
    for m in re.finditer(rb'stream\r?\n', data):
        s = m.end()
        e = data.find(b'endstream', s)
        if e == -1:
            continue
        try:
            yield zlib.decompress(data[s:e])
        except Exception:
            continue

def unescape(b):
    return b.replace(rb'\(', b'(').replace(rb'\)', b')').replace(rb'\\', b'\\')

def text_of(data):
    out = []
    for blob in streams(data):
        if b'BT' not in blob:
            continue
        # NO newline is emitted for Td/TD/T*. These PDFs position every WORD
        # with its own operator, so treating a position change as a line break
        # put one word on each line and made the output unreadable. The text is
        # joined as a single stream and re-broken below, on section numbers,
        # which is the structure that actually matters in a statute.
        for tm in re.finditer(
            rb'\[(.*?)\]\s*TJ|\(((?:[^()\\]|\\.)*)\)\s*Tj',
            blob, re.S):
            if tm.group(1) is not None:
                parts = re.findall(rb'\((?:[^()\\]|\\.)*\)', tm.group(1), re.S)
                out.append(b''.join(unescape(p[1:-1]) for p in parts))
            else:
                out.append(unescape(tm.group(2)))
            out.append(b' ')
    return b''.join(out).decode('latin-1')

data = open(sys.argv[1], 'rb').read()
title = re.search(rb'/Title\s*\(([^)]{0,200})\)', data)
title = title.group(1).decode('latin-1') if title else 'UNKNOWN CHAPTER'

body = text_of(data)
# The site's PDF generator renders non-breaking spaces as a literal capital
# "A". Stripping every standalone A would be a disaster: it would destroy
# "SUBCHAPTER A.", the "(A)" subsection labels, and ordinary English such as
# "A person may not engage in...". Only the two positions where the filler
# actually occurs are targeted.
body = re.sub(r'Sec\.\s*A+\s*(\d)', r'Sec. \1', body)          # Sec. A 541.001.
body = re.sub(r'(\d\.)\s*A+\s+([A-Z]{2,})', r'\1 \2', body)    # 541.001. AA PURPOSE
body = re.sub(r'(\(\w{1,3}\))\s*A+\s+', r'\1 ', body)         # (1) AA "Knowingly"
body = re.sub(r'\s+', ' ', body)
# Re-break on the structure a statute actually has: subtitles, subchapters,
# section numbers, and the (a)/(b) subsections within them.
body = re.sub(r'\s*(SUBCHAPTER [A-Z]\.)', r'\n\n\1', body)
body = re.sub(r'\s*(Sec\.\s*\d[\d.]*\.)', r'\n\n\1', body)
body = re.sub(r'\s+(\([a-z]\))\s+', r'\n\1 ', body)
body = re.sub(r'\n{3,}', '\n\n', body).strip()

print(f'# {title}')
print()
print(f'Source: statutes.capitol.texas.gov, retrieved {date.today().isoformat()}.')
print('Texas statutes are public records. Extracted from the site\'s own PDF;')
print('verify any section against the source before relying on it in a lesson.')
print()
print('---')
print()
print(body)
