#!/usr/bin/env python3
"""Turn a statutes.capitol.texas.gov chapter PDF into reviewable plain text.

The PDFs are generated by the site and carry their chapter name in the PDF
title, which is used as the header here so a file can never be mistaken for a
different chapter. Text rather than the PDF is committed because text diffs
when the legislature amends a section, and a binary does not.
"""
import re, sys, zlib
from datetime import date

def streams(data):
    for m in re.finditer(rb'stream\r?\n', data):
        s = m.end()
        e = data.find(b'endstream', s)
        if e == -1:
            continue
        try:
            yield zlib.decompress(data[s:e])
        except Exception:
            continue

def unescape(b):
    return b.replace(rb'\(', b'(').replace(rb'\)', b')').replace(rb'\\', b'\\')

def text_of(data):
    out = []
    for blob in streams(data):
        if b'BT' not in blob:
            continue
        # NO newline is emitted for Td/TD/T*. These PDFs position every WORD
        # with its own operator, so treating a position change as a line break
        # put one word on each line and made the output unreadable. The text is
        # joined as a single stream and re-broken below, on section numbers,
        # which is the structure that actually matters in a statute.
        for tm in re.finditer(
            rb'\[(.*?)\]\s*TJ|\(((?:[^()\\]|\\.)*)\)\s*Tj',
            blob, re.S):
            if tm.group(1) is not None:
                parts = re.findall(rb'\((?:[^()\\]|\\.)*\)', tm.group(1), re.S)
                out.append(b''.join(unescape(p[1:-1]) for p in parts))
            else:
                out.append(unescape(tm.group(2)))
            out.append(b' ')
    return b''.join(out).decode('latin-1')


def clean(body):
    """Remove the PDF generator's filler glyph and restore statute structure.

    Kept as a function with no I/O so scripts/test-extract-statute.py can
    exercise it directly. The bug this guards against was invisible in the
    output: the filler rule silently deleted the real word "A" at the start of
    35 subsections across 9 chapters, turning "A person may not acquire..."
    into "person may not acquire...". Nothing tested the transform, so nothing
    caught it.
    """
    # The site's PDF generator renders non-breaking spaces as a literal capital
    # "A". Stripping every standalone A would be a disaster: it would destroy
    # "SUBCHAPTER A.", the "(A)" subsection labels, "A. M. Best", a financial
    # strength rating of "A- or better", and ordinary English such as "A person
    # may not engage in...".
    #
    # Across all 23 chapter PDFs obtained from the site, standalone runs of A
    # occur in exactly two lengths: 1 (1,060 times, nearly all real English)
    # and 2 (3,712 times, all filler). So the filler is removed by LENGTH, not
    # by guessing from the surrounding context. The one systematic single-A
    # filler is between "Sec." and the section number, which is unambiguous
    # because digits follow.
    body = re.sub(r'Sec\.\s*A\s*(\d)', r'Sec. \1', body)
    body = re.sub(r'(?<![A-Za-z(])A{2,}(?![A-Za-z)])', ' ', body)
    # One more single-A position, found by reading the output rather than by
    # reasoning about it: a lone filler after a section heading, as in
    # "NONRENEWAL OF POLICIES; NOTICE REQUIRED. A Unless the insurer has
    # mailed...". It occurs once across all 30 chapters, so the rule is kept
    # as narrow as the evidence: a standalone "A" is filler only when the next
    # word is one that CANNOT grammatically follow the indefinite article.
    # "A REFUSAL", "A MOTOR VEHICLE" and "A person" are all untouched.
    body = re.sub(
        r'(?<![A-Za-z])A (?=(?:Unless|Except|Notwithstanding|If|When|Whenever'
        r'|Repealed|This|That|These|Those|It|The|An|Shall|May|Must|Is|Are'
        r'|Was|Were)\b)',
        '', body)
    body = re.sub(r'\s+', ' ', body)
    # Re-break on the structure a statute actually has: subtitles, subchapters,
    # section numbers, and the (a)/(b) subsections within them.
    body = re.sub(r'\s*(SUBCHAPTER [A-Z]\.)', r'\n\n\1', body)
    body = re.sub(r'\s*(Sec\.\s*\d[\d.]*\.)', r'\n\n\1', body)
    body = re.sub(r'\s+(\([a-z]\))\s+', r'\n\1 ', body)
    return re.sub(r'\n{3,}', '\n\n', body).strip()


def main(path):
    data = open(path, 'rb').read()
    title = re.search(rb'/Title\s*\(([^)]{0,200})\)', data)
    title = title.group(1).decode('latin-1') if title else 'UNKNOWN CHAPTER'
    print(f'# {title}')
    print()
    print(f'Source: statutes.capitol.texas.gov, retrieved {date.today().isoformat()}.')
    print('Texas statutes are public records. Extracted from the site\'s own PDF;')
    print('verify any section against the source before relying on it in a lesson.')
    print()
    print('---')
    print()
    print(clean(text_of(data)))


if __name__ == '__main__':
    main(sys.argv[1])
